### ISSUE TITLE
Tuist command defaults to tuistenv

### ISSUE THREAD

**Issue by stherold** [tuist/tuist#4060] opened 2022-01-26 17:58 UTC
**Describe the bug**
From today (for some teason) the behavior of `tuist` changed. Now it prints:
```
OVERVIEW: Manage the environment tuist versions

USAGE: tuist <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  local                   Creates a .tuist-version file to pin the tuist version that should be used in the current directory. If the version is not specified, it prints the local versions
  bundle                  Bundles the version specified in the .tuist-version file into the .tuist-bin directory
  update                  Installs the latest version if it's not already installed
  install                 Installs a version of tuist
  uninstall               Uninstalls a version of tuist
  envversion              Outputs the current version of tuist env.

  See 'tuist help <subcommand>' for detailed help.
```

... and does not use the bundled version automatically anymore. 

**To Reproduce**

1. call `curl -Ls https://install.tuist.io | bash`
2. call `tuist`

**Expected behavior**
I would like the old behavior back so that I can call tuist generate...

**Comment by danyf90** [comment] 2022-01-26 18:11
Duplicate of #4059

**Closed by danyf90** 2022-01-26 18:11 UTC

**Comment by stherold** [comment] 2022-01-26 18:28
ooops
