### ISSUE TITLE
SPM: Adding Swift packages to static framework and then adding it as dependency for another static framework breaks build

### ISSUE THREAD

**Issue by Unknoob** [tuist/tuist#2751] opened 2021-03-30 21:20 UTC
**Describe the bug**
I've been trying to migrate a big project to tuist and got into a weird scenario.

Given an App and two static frameworks A and B where the dependency graph is the following

App -> Static Framework A -> Static Framework B -> SPM Dependency

Building the Static Framework B works fine, but when trying to build A I'm getting all kinds of errors related to the SPM dependency.

I'm not an expert in the iOS build system so I'm not sure if I'm trying to do something impossible.

**To Reproduce**
I have a test repo hosted here: https://github.com/Unknoob/TuistExample

All you have to do is clone the repo, run `tuist generate` amnd then try to build the targets.
The `YetAnotherModule` target should build correctly but the `AnotherModule` target that depends on it should fail.

**Expected behavior**
All targets and the app should build correctly.

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.7
- XCode: 12.4

**Additional context**
Declaring the targets as `.dynamicFrameworks` fixes the problem but may cause code duplication with the crazy dependency graphs in the project I'm trying to migrate.

**Comment by fortmarek** [comment] 2021-04-01 20:01
Hi @Unknoob!

Was the setup you are describing working for you before introducing tuist?

I have tried it locally and it behaves as you have described.

I think this scenario should be supported - and if you change `FirebaseCrashlytics` to some other dependency like [Composable Architecture](https://github.com/pointfreeco/swift-composable-architecture), it seems to work actually 🤔 

I wonder if this might be issue in SPM or Firebase directly. I'd also recommend checking out [this](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md) and double-check everything is set up correctly.

I'd probably try to chip away at this problem by creating a new project that will contain single `.xcodeproj` and will not be created by tuist. If it still does not work, the issue is probably somewhere else than in tuist.

**Comment by Unknoob** [comment] 2021-04-05 19:25
Our current setup uses the Firebase dependencies compiled as .framework so it's not quite the same. 

I've noticed that I can't manually recreate what tuist is doing. I manually create a workspace and then 3 projects: App, ModuleA and ModuleB. Then I add the SPM dependency to the App project. When I try to import the SPM dependency from either ModuleA or ModuleB the package is not listed. 

Should tuist really allow the behavior to import a SPM package from a different project?

**Comment by fortmarek** [comment] 2021-04-08 19:27
> Should tuist really allow the behavior to import a SPM package from a different project?

This works fine if you are using dynamic frameworks, so it's weird it'd be broken for static ones. Does the import of SPM dependencies work correctly if you do it manually (ie without tuist)?

As long as you use the dependency only in one of the static frameworks, I believe it should not be illegal but the current behavior does seem odd.

**Comment by Unknoob** [comment] 2021-04-12 13:11
Without Tuist I cannot add the SPM dependency to Static Framework B unless the package is added to the Static Framework B xcodeproj file, but when I do it works as expected.
[Here's an example project.](https://github.com/Unknoob/Example)

**Comment by danyf90** [comment] 2022-04-09 20:46
Closed in favor of Dependencies.swift

**Closed by danyf90** 2022-04-09 20:46 UTC
