### ISSUE TITLE
FR: Export Product

### ISSUE THREAD

**Issue by jesus-qt** [tuist/tuist#3233] opened 2021-07-27 13:42 UTC
## Context 🕵️‍♀️
Archive product and export as iPA o generate xcframeworks directly with Tuist

## What 🌱
I want to use export archive without use xcodebuild directly, only with Tuist like Tuist build

## Proposal 🎉
`tuist archive --scheme myScheme `
Using the archive configuration set on manifest.

**Comment by fortmarek** [comment] 2021-07-27 17:03
Hi @jesus-qt!

This would, indeed, be a great feature but it's a duplicate of this [issue](https://github.com/tuist/tuist/issues/2160).

I have posted my [answer](https://github.com/tuist/tuist/issues/2160#issuecomment-887678529) there as well. I'll close this and feel free to follow up in the issue attached above 🙂

**Closed by fortmarek** 2021-07-27 17:03 UTC
