### ISSUE TITLE
Infinite recursion with SWIFTPM_MODULE_BUNDLE in Obj-C packages

### ISSUE THREAD

**Issue by nickkhg** [tuist/tuist#5984] opened 2024-02-23 15:31 UTC
### What happened?

It seems that since #5945 was merged, tuist now synthesises `SWIFTPM_MODULE_BUNDLE` for Obj-C targets. The synthesised bundle for one of Stripe's Obj-C targets (Stripe3DS2) isn't generated correctly, and ends up in an infinite recursion. This happens as soon as one of their singletons is initialised (`STPPaymentHandler.sharedHandler`).

Tuist 4.2.5 seems to work perfectly fine since it doesn't generate `TuistBundle+Stripe3DS2`.

### How do we reproduce it?

[SpmBundleIssue.zip](https://github.com/tuist/tuist/files/14386889/SpmBundleIssue.zip)

1. Using a tuist version greater than 4.2.5, run `tuist install` and `tuist generate` in the sample project above
2. Open TuistBundle+Stripe3DS2 using Cmd+Shift+O
3. Add a breakpoint on line 4, and set it to ignore 10 times
4. Run the project (`STPPaymentHandler.sharedHandler` is called in `.onAppear`)

Steps 2&3 aren't required, but it takes a long time for the recursion stack to fill and crash, hence the breakpoint

### Error log

Uploaded crash log [here](https://github.com/tuist/tuist/files/14386949/crash.log)

### macOS version

14.0

### Tuist version

4.3.4

### Xcode version

15.2

**Comment by fortmarek** [comment] 2024-02-24 16:39
Hey 👋 

Closing as a duplicate of: https://github.com/tuist/tuist/issues/5959

We'll look into it 🙏

**Closed by fortmarek** 2024-02-24 16:39 UTC
Labels: type:bug
