### ISSUE TITLE
Tuist local is broken when it points to a commit

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#400] opened 2019-06-07 22:08 UTC
## Context 🕵️‍♀️
The `tuist local` command doesn't work when we are pinning a commit instead of a version. When the command tries to pull the source code and compile it, it fails.

## What 🌱
Figure out why the process is failing and fix it.

**Comment by ollieatkinson** [comment] 2019-06-08 17:23
Closing as duplicate of https://github.com/tuist/tuist/issues/326

**Closed by ollieatkinson** 2019-06-08 17:23 UTC
Labels: domain:tuistenv, type:bug, type:good-first-issue
