### ISSUE TITLE
Extra schemes generation for dependencies

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [tuist/tuist#4260] opened 2022-03-19 21:18 UTC
**Describe the bug**
I have created 3 targets (app, unitTests, unitTests) with dependencies and 3 schemes for targets separately.
After `tuist generate -x` command in resulted xcodeproj I get project with auto generated schemes for dependencies.

**To Reproduce**
Steps to reproduce the behaviour:
 
1. Download test project [MyApp.zip](https://github.com/tuist/tuist/files/8310134/MyApp.zip)
2. tuist fetch
3. tuist cache warm -x
4. tuist generate -x
5. In addition, you can create schemes for targets. 

**Expected behavior**
Project generates without additional schemes for dependencies.

**Screenshots**
<img width="182" alt="image" src="https://user-images.githubusercontent.com/39379705/159138547-8bf67967-6f76-4aab-bbd7-352defe4a559.png">

**Desktop (please complete the following information):**

OS: macOS 12.0.1
Tuist version 3.0.1
M1 Mac

**Comment by danyf90** [comment] 2022-03-20 11:40
I think it was intended, but maybe not generating them could be a better default, as if they are needed the schemes can always be manually generated.
WDYT @fortmarek @kwridan @adellibovi ?

**Comment by fortmarek** [comment] 2022-03-21 20:48
Hey @Bogdan-Belogurov 👋 

If you don't want to work on your dependencies, it's better to use them as binaries via `tuist cache warm` instead. From my point of view, you either:
- want to debug your external frameworks. Then you need them as sources and you need a scheme for them
- don't need to change or debug external frameworks -> they should be integrated as binaries as you will get all-around better build times and DX

I will close this but feel free to continue the discussion and we can re-open the issue if we decide to change the current default.

**Comment by Bogdan-Belogurov** [comment] 2022-03-22 08:04
Hi @fortmarek
I cache dependencies in the project, you can see an example in the issue description. And declare them as `external` to use the cache. But this leads to the creation of extra schemes.
```swift
let testTarget = makeTarget(
    name: "MyAppTests",
    product: .app,
    infoPlist:  .extendingDefault(with: infoPlist),
    sources: ["Targets/MyAppTests/Tests"],
    dependencies: [
        .external(name: "Nimble"),
        .external(name: "Quick")
    ]
)
```

**Comment by fortmarek** [comment] 2022-03-22 08:06
Hey @Bogdan-Belogurov!

Sorry, I missed that step. When you run `tuist cache warm`, does it also cache the external dependencies? If not, we should look into why those dependencies are considered not "cacheable".

**Comment by Bogdan-Belogurov** [comment] 2022-03-22 08:21
@fortmarek 
As I can see from the output
```
Storing 7 cacheable targets: Alamofire, CwlCatchException, CwlCatchExceptionSupport, CwlMachBadInstructionHandler, CwlPosixPreconditionTesting, CwlPreconditionTesting, QuickObjCRuntime
```
It looks like tuist caches dependensies from Quick and Nimble instead of whole libraries.
[Nimble Project.swift](https://github.com/Quick/Nimble/blob/main/Package.swift)

**Comment by danyf90** [comment] 2022-03-22 11:30
I think those are not cacheable because they depend on XCTest. Given that I think it's better to change the default to not generating the schemes 🤔  WDYT @fortmarek ?

**Comment by fortmarek** [comment] 2022-03-24 20:41
> Given that I think it's better to change the default to not generating the schemes 

How do we then generate the schemes? I am still in favor of keeping the default but wdyt about adding an API of disabling autogeneration of schemes for specific dependencies? Or is that something already possible @danyf90?

**Comment by danyf90** [comment] 2022-03-24 21:17
At the moment is not possible but it should be easy to add.
However the only use case I see is to try to build the dependency when you have problem, and I wouldn't complicate the API for such a niche use case, which you can cover creating the scheme for Xcode if needed once

**Comment by danyf90** [comment] 2022-03-26 13:37
Automatically disabled them here: https://github.com/tuist/tuist/pull/4282

**Closed** 2022-03-28 22:09 UTC
