### ISSUE TITLE
`tuist cache warm` crashes while having a physical device connected to Xcode

### ISSUE THREAD

**Issue by mihaicris-adoreme** [tuist/tuist#3711] opened 2021-11-22 09:43 UTC
**Bug Description**
`tuist cache warm` crashes while having a physical device connected to Xcode (cable/wifi)

**To Reproduce**

1. Run `tuist clean`
2. Connect a device to Xcode, wait for device to appear in Devices section.
2. Have a project with frameworks/dependencies that can be cached
3. Run `tuist cache warm`
4. Process crashes

Alternative
5. Disconnect device from Xcode
6. Run `tuist cache warm`
7. Works as expected, though --verbose is not working

**Expected behavior**
Targets are caches as expected.
If passing --verbose, logged steps should be seen in the console

**Actual behavior**
tuist crashes
TuistSupport/SystemEvent.swift:58: Fatal error: Unexpectedly found nil while unwrapping an Optional value
--verbose has no effect. Logs not shown. Was this option removed from command arguments?

- OS: macOS 12.0.1 (21A559)

**Additional context**
Running tuist from Xcode build from sources reveals that crash occurs on mapping xcodebuild messeges to Xcode event

```
Building cacheable targets
TuistSupport/SystemEvent.swift:58: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2021-11-21 12:13:07.705208+0200 tuist[27314:92146] TuistSupport/SystemEvent.swift:58: Fatal error: Unexpectedly found nil while unwrapping an Optional value```

**Comment by luispadron** [comment] 2022-01-25 04:47
This is more than likely related to `SimulatorController` not being able to locate an available device. We'll need to take a look at it to be sure, thanks for reporting.

**Comment by pepicrft** [comment] 2023-12-24 16:34
I haven't seen this being reported recently so I will close it. Please, if the issue is still relevant, don't hesitate to re-open it.

**Closed by pepicrft** 2023-12-24 16:34 UTC
Labels: type:bug, domain:cache
