### ISSUE TITLE
Website link to docs is broken

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#76] opened 2018-07-24 18:19 UTC
Link on website to docs does not work. Same for github etc.

**Comment by pepibumur** [comment] 2018-08-05 20:06
I double checked on the [website](https://tuist.io) and links seem to be working. Could you be more specific about the links that are not working for you?

**Comment by pepibumur** [comment] 2018-08-16 16:56
I'll close this use since we haven't got any input. If the problem is still there, feel free to open it.

**Closed by pepibumur** 2018-08-16 16:56 UTC
Labels: bug
