### ISSUE TITLE
Generated Graphs include all libraries pre-strippingc

### ISSUE THREAD

**Issue by ActuallyTaylor** [tuist/tuist#6171] opened 2024-04-10 15:39 UTC
### What happened?

This issue references the discussion #6136.

> I thought they would be because I was using the graph feature of Tuist and found that google libraries were all included instead of only the ones I use. Could this just be an issue with the graphing?
> 
> Very likely. I think the logic that strips some of the targets only runs when generating the project, not visualizing it. We could probably extend the graph command so that users can express things like "I want to visualize the project that you'll generate", or "I want to visualize the project with binaries from the cache".

### How do we reproduce it?

Create a project using a google library such as [GoogleAPIClientForREST](https://github.com/google/google-api-objectivec-client-for-rest). When you generate a project and then generate a graph, all of the libraries from GoogleAPIClientForREST will be shown.

### Error log

There is no error log, but the graphs generated include all libraries even ones that will be stripped in a generated project.

### macOS version

14.1

### Tuist version

4.9.0

### Xcode version

15

**Comment by fortmarek** [comment] 2024-04-11 07:08
> Create a project using a google library such as [GoogleAPIClientForREST](https://github.com/google/google-api-objectivec-client-for-rest). When you generate a project and then generate a graph, all of the libraries from GoogleAPIClientForREST will be shown.

Can you attach the reproducible project as a zip? It saves us a lot of time instead of trying to create a reproducer project on our own 🙏

**Comment by pepicrft** [comment] 2024-05-15 08:25
I'm closing this since it's been a while without a reproducible project. Don't hesitate to open a new issue with a reproducible project if the issue still persists in your end.

**Closed by pepicrft** 2024-05-15 08:25 UTC
Labels: type:bug

**Comment by ActuallyTaylor** [comment] 2024-05-20 18:21
Hi! Sorry for the long wait, but I have put together a sample project which shows how the Google dependencies result in a crazy graph. I hope this helps with troubleshooting! If there is anything I can do to help please let me know

[CrazyGoogleDep.zip](https://github.com/tuist/tuist/files/15380567/CrazyGoogleDep.zip)
