### ISSUE TITLE
Skip  warnings for External Dependencies on `tuist generate`

### ISSUE THREAD

**Issue by vijaytholpadi** [tuist/tuist#6223] opened 2024-04-23 02:45 UTC
### What happened?

I have Stripe as one of the external dependencies in my project. On running `tuist generate` I get the warning complaining about missing info.plist file within the external dependency.

### How do we reproduce it?

<Preparing a fixture to attach>

### Error log

```
No files found at: /Repo/Tuist/.build/checkouts/stripe-ios/StripeIdentity/StripeIdentity/Info.plist
```

### macOS version

14.3.1

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by fortmarek** [comment] 2024-04-23 06:58
Closing as a duplicate of: https://github.com/tuist/tuist/issues/5928

There's a PR up to fix the issue: https://github.com/tuist/tuist/pull/6069 I might take it on from the contributor, so we can get this in sooner as I agree it's annoying (and it's annoying for a lot of tuist users)

**Closed by fortmarek** 2024-04-23 06:58 UTC
Labels: type:bug
