### ISSUE TITLE
Tuist cannot cache MarkdownUI

### ISSUE THREAD

**Issue by nuomi1** [tuist/tuist#7153] opened 2024-12-11 16:08 UTC
### What happened?

Tuist cannot build MarkdownUI module but swift can build it.

### How do we reproduce it?

Tuist

1. Add `https://github.com/gonzalezreal/swift-markdown-ui.git@2.4.1` to package dependencies
2. Add `MarkdownUI` to project dependencies
3. Run `tuist install --update`
4. Run `tuist cache --external-only`
5. Build error

---

SPM

1. Run `git clone https://github.com/gonzalezreal/swift-markdown-ui gonzalezreal/swift-markdown-ui`
2. Run `cd gonzalezreal/swift-markdown-ui`
3. Run `swift build`
4. Build success

---

Sample code: https://github.com/nuomi1/TestTuist/tree/feat/MarkdownUI

### Error log

```bash
tuist cache --external-only
Loading and constructing the graph
It might take a while if the cache is empty
Hashing cacheable targets
Targets to be cached: MarkdownUI, cmark-gfm, cmark-gfm-extensions
Loading and constructing the graph
It might take a while if the cache is empty
Using cache binaries for the following targets: NetworkImage
Generating workspace TestTuist.xcworkspace
Generating project cmark-gfm
Generating project swift-markdown-ui
Building cacheable targets
Building scheme Binaries-Cache-iOS for the simulator
[cmark-gfm] Write Auxiliary File cmark_gfm.DependencyMetadataFileList
[cmark-gfm-extensions] Write Auxiliary File cmark_gfm_extensions.DependencyMetadataFileList
[cmark-gfm-extensions] Write Auxiliary File cmark_gfm_extensions_vers.c
[cmark-gfm-extensions] Write Auxiliary File cmark_gfm_extensions.LinkFileList
[cmark-gfm] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[cmark-gfm-extensions] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[cmark-gfm-extensions] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[cmark-gfm] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[cmark-gfm] Write Auxiliary File cmark_gfm.LinkFileList
[cmark-gfm] Write Auxiliary File cmark_gfm.LinkFileList
[cmark-gfm] Write Auxiliary File cmark_gfm_vers.c
[cmark-gfm] Processing cmark-gfm-Info.plist
[MarkdownUI] Write Auxiliary File MarkdownUI.SwiftFileList
[MarkdownUI] Write Auxiliary File MarkdownUI.SwiftFileList
[MarkdownUI] Write Auxiliary File MarkdownUI.LinkFileList
[MarkdownUI] Write Auxiliary File module.modulemap
[MarkdownUI] Write Auxiliary File MarkdownUI-OutputFileMap.json
[MarkdownUI] Write Auxiliary File MarkdownUI_const_extract_protocols.json
[MarkdownUI] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[MarkdownUI] Write Auxiliary File MarkdownUI_const_extract_protocols.json
[MarkdownUI] Write Auxiliary File MarkdownUI.LinkFileList
[MarkdownUI] Write Auxiliary File 7187679823f38a2a940e0043cdf9d637-common-args.resp
[MarkdownUI] Write Auxiliary File MarkdownUI-OutputFileMap.json
[MarkdownUI] Write Auxiliary File MarkdownUI_vers.c
[MarkdownUI] Copy module.modulemap -> module.modulemap
[cmark-gfm-extensions] Compiling cmark_gfm_extensions_vers.c
[cmark-gfm-extensions] Compiling cmark_gfm_extensions_vers.c
[cmark-gfm-extensions] Compiling ext_scanners.c
[cmark-gfm] Compiling xml.c
[cmark-gfm] Compiling utf8.c
[cmark-gfm] Compiling syntax_extension.c
[cmark-gfm] Compiling scanners.c
[cmark-gfm] Compiling render.c
[cmark-gfm] Compiling registry.c
[cmark-gfm] Compiling references.c
[cmark-gfm] Compiling plaintext.c
[cmark-gfm] Compiling node.c
[cmark-gfm] Compiling man.c
[cmark-gfm] Compiling linked_list.c
[cmark-gfm] Compiling latex.c
[cmark-gfm] Compiling iterator.c
[cmark-gfm] Compiling inlines.c
[cmark-gfm] Compiling html.c
[cmark-gfm] Compiling houdini_html_u.c
[cmark-gfm] Compiling houdini_html_e.c
[cmark-gfm] Compiling houdini_href_e.c
[cmark-gfm] Compiling commonmark.c
[cmark-gfm] Compiling cmark_ctype.c
[cmark-gfm] Compiling cmark.c
[cmark-gfm] Compiling buffer.c
[cmark-gfm] Compiling blocks.c
[cmark-gfm] Compiling arena.c
❌ /Users/nuomi1/Documents/GitHub/nuomi1/TestTuist/Tuist/.build/checkouts/swift-cmark/extensions/tasklist.h:6:1: missing '#include "cmark-gfm.h"'; 'cmark_syntax_extension' must be declared before it is used

[cmark-gfm-extensions] Compiling table.c
[cmark-gfm-extensions] Compiling strikethrough.c
[cmark-gfm-extensions] Compiling core-extensions.c
[cmark-gfm] Building library cmark_gfm
[cmark-gfm-extensions] Compiling autolink.c
The 'xcodebuild' command exited with error code 65 and message:
** BUILD FAILED **


The following build commands failed:
	CompileC /var/folders/yn/hnb5wsln1jj_wpllk4fgd6hh0000gn/T/TemporaryDirectory.mU46wn/derived-data/Build/Intermediates.noindex/cmark-gfm.build/Debug-iphonesimulator/cmark-gfm-extensions.build/Objects-normal/x86_64/tasklist.o /Users/nuomi1/Documents/GitHub/nuomi1/TestTuist/Tuist/.build/checkouts/swift-cmark/extensions/tasklist.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'cmark-gfm-extensions' from project 'cmark-gfm')
	Building workspace TestTuist with scheme Binaries-Cache-iOS and configuration Debug
(2 failures)

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

15.1.1 (24B2091)

### Tuist version

4.36.0

### Xcode version

16.1 (16B40)

**Comment by lilidotshi** [comment] 2024-12-11 17:58
I believe this is related: https://github.com/tuist/tuist/issues/6879

**Comment by nuomi1** [comment] 2024-12-12 06:12
> I believe this is related: #6879

Yes, it's the same problem.

**Comment by fortmarek** [comment] 2024-12-13 09:59
Thanks for reporting! Closing as a duplicate of: https://github.com/tuist/tuist/issues/6879

We hope to have a fix for this soon.

**Closed by fortmarek** 2024-12-13 09:59 UTC
Labels: type:bug, domain:cache
