### ISSUE TITLE
Tuist install fails when dependencies are removed

### ISSUE THREAD

**Issue by anlaital-oura** [tuist/tuist#5941] opened 2024-02-16 08:16 UTC
### What happened?

It is not possible to remove a dependency after caching without running `tuist clean` or `rm -rf`'ing the checkout directory manually. This happens because Tuist generates some directories and files in the checkout directory.

### How do we reproduce it?

1. Add dependency to `swift-syntax`
2. Run `tuist install && tuist cache`
3. Remove dependency to `swift-syntax`
4. Run `tuist install` and it will fail

### Error log

```sh
Removing https://github.com/apple/swift-syntax.git
error: 'swift-syntax': repository '/.../.build/checkouts/swift-syntax' has uncommited changes
```

### macOS version

14.3.1

### Tuist version

4.2.3

### Xcode version

15.2

**Comment by kapitoshka438** [comment] 2024-02-16 09:34
Duplicate of https://github.com/tuist/tuist/issues/5489

Calling `tuist install` again works for me. I'm fetching dependencies this way as a workaround:
```
if ! tuist install; then tuist install; fi
```

**Comment by fortmarek** [comment] 2024-02-17 13:06
Thanks for attaching the duplicate. I'm closing this, but we'll look into it and hopefully fix it soon 🙏

**Closed by fortmarek** 2024-02-17 13:06 UTC
Labels: type:bug
