### ISSUE TITLE
Carthage dependencies using binary JSON format are broken

### ISSUE THREAD

**Issue by dcramps** [tuist/tuist#5024] opened 2023-02-03 00:52 UTC
### What happened?

Carthage binary JSON dependencies do not download, giving a `'Dependency' is not a valid configured external dependency for platform ios` error on `tuist generate`

### How do we reproduce it?

See this [minimal example](https://github.com/tuist/tuist/files/10574554/CarthageExample.zip)

With `Dependencies.swift` containing Carthage dependencies for GooglePlaces (binary JSON) and Alamofire (GitHub), only the Alamofire dependency is configured correctly.

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage:[
        .binary(path: "https://dl.google.com/geosdk/GooglePlaces.json", requirement: .upToNext("7.2.0")),
        .github(path: "https://github.com/Alamofire/Alamofire", requirement: .upToNext("5.0.0")),
    ],
    swiftPackageManager: [],
    platforms: [.iOS])
```

```swift
import ProjectDescription

let project = Project(
    name: "CarthageExample",
    targets: [
        Target(
            name: "CarthageExample",
            platform: .iOS,
            product: .app,
            bundleId: "com.dc.CarthageExample",
            infoPlist: .default,
            dependencies: [
                .external(name: "GooglePlaces"),
                .external(name: "AlamoFire"),
            ])
    ])

```

`tuist fetch` gives
```
❯ tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Carthage dependencies.
*** No Cartfile.resolved found, updating dependencies
*** Downloading binary-only framework GooglePlaces at "https://dl.google.com/geosdk/GooglePlaces.json"
*** Fetching Alamofire
*** Checking out Alamofire at "5.6.4"
*** No cache found for Alamofire, building with all downstream dependencies
*** No cache found for GooglePlaces, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/sb/xr77pr555j58rd5wbb2j7d1h0000gp/T/carthage-xcodebuild.EpvzOZ.log
*** Downloading binary-only framework GooglePlaces at "https://dl.google.com/geosdk/GooglePlaces.json"
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Carthage dependencies installed successfully.
Dependencies resolved and fetched successfully.
```

`tuist generate` gives:
```
❯ tuist generate
Resolved cache profile 'Development' from Tuist's defaults
`GooglePlaces` is not a valid configured external dependency for platform ios
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

Looking into the Dependencies directory, there is no reference to GooglePlaces outside of Cartfile and Cartfile.resolved
It seems as though the JSON format is not supported by tuist. If that's the case, I wouldn't expect that `tuist fetch` gives a success message.

### Error log

`GooglePlaces` is not a valid configured external dependency for platform ios

### macOS version

13.2

### Tuist version

3.15

### Xcode version

14.2

**Comment by danyf90** [comment] 2023-02-04 20:30
Unfortunately that's not supported right now. Duplicate of https://github.com/tuist/tuist/issues/3174

**Closed by danyf90** 2023-02-04 20:30 UTC
Labels: type:bug

**Comment by szymon-heetch** [comment] 2023-07-24 15:24
Hey 👋 Any ETA to support that?
