### ISSUE TITLE
"disableBundleAccessors" options not working

### ISSUE THREAD

**Issue by liam-eun** [tuist/tuist#6448] opened 2024-06-27 13:29 UTC
### What happened?

Slack: https://tuist-community.slack.com/archives/C018QG7U7SN/p1719447838533249

## Problem
1. "Module/derived/TuistBundle+(ModuleName).swift" is not generated when "disableBundleAccessors" flags is false. (I'm not sure why, but if I set the disableSynthesizedResourceAccessors flag to false, the file is generated.)
2.  generated "Module/derived/TuistPlists+(ModuleName).swift" has compilation error.
```
public enum IPhoneKeySetting {
...
    public static let _18: [String] = ["i", "I", "ㅑ", "ㅑ", "\"] // "\" is problem
...
    public static let _21: [String] = ["a", "A", "ㅁ", "ㅁ", """] // """ is problem
...
}
```

### How do we reproduce it?

[ios_app_with_framework_and_disabled_resources.zip](https://github.com/user-attachments/files/16027711/ios_app_with_framework_and_disabled_resources.zip)

1. download this fixture and unzip
2. "tuist edit" and edit Framework1/project.swift
```
let project = Project(
    name: "Framework1",
    options: .options(
        disableBundleAccessors: false,
        disableSynthesizedResourceAccessors: true
    ),
...
```
3. "tuist generate" and see result
-> "Framework1/Derived/Sources/TuistBundle+Framework1.swift" is not generated...
-> you can generate "TuistBundle+Framework1.swift" and "TuistPlists+Framework1" by changing disableSynthesizedResourceAccessors flag to false but "TuistPlists+Framework1" has copilation error

### Error log

1. "Framework1/Derived/Sources/TuistBundle+Framework1.swift" missing issue -> Cannot find module Framework1
2. generated "TuistPlists+Framework1.swift" file has compilation error.

### macOS version

14.3.1

### Tuist version

4.19.0

### Xcode version

15.3.0

**Comment by fortmarek** [comment] 2024-06-28 10:16
Hey @liam-eun 👋 

Thanks again for including the reproducible sample. The problem is we don't generate resource accessors for internal, pure Objective C targets. I created a dedicated issue for that: https://github.com/tuist/tuist/issues/6456

You seemed to have been on track to figuring out a workaround. Your sample does include the `Empty.swift` file and if the target would have Swift sources, we _would_ generate the Swift resource accessor.

However, the `Empty.swift` is not picked up as the `Framework1` definition does not include the following line:
```swift
sources: "Sources/**",
```

After that line is added to the `Framework1`'s `Project.swift` file, you should be able to build `Framework1` in the newly generated project.

I am closing this as this is a known limitation and we can continue the conversation for how to support Objc resource accessors for internal targets in the separate issue.

Feel free to reopen if the workaround doesn't work for you.

**Closed by fortmarek** 2024-06-28 10:16 UTC
Labels: type:bug

**Comment by liam-eun** [comment] 2024-06-30 00:21
Thank you. My problem was resolved by your solution. 
(make empty.swift in sources and parameter `sources: "sources"`)
