### ISSUE TITLE
Dependencies.swift not compatible Firebase 9.1.0 & 9.2.0 subdependency gtm-session-fetcher

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#4573] opened 2022-06-27 07:04 UTC
## Describe the bug and the expected behavior

With the release of Firebase 9.1.0 & 9.2.0 the package GTMSessionFetcher got bumped to use any version between 1.7.2 and < 3.0.0 [diff](https://github.com/firebase/firebase-ios-sdk/compare/v8.15.0...9.1.0#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR168)

When running a new tuist project (3.7.0) or running `tuist fetch --update` with Firebase as a dependency, `tuist fetch` picks up the latest version 2.0.0 for the gtm-session-fetcher.

```
{
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "19605024d59eaefdb1f6a2cb11ebe75df4421126",
        "version" : "2.0.0"
      }
    },

```

When running then `tuist generate` and try to build the project the following error occurs:

`'GTMSessionFetcher/GTMSessionFetcher.h' file not found`

However with version 1.7.2 of `gtm-session-fetcher`it builds fine.

I can see that  https://github.com/google/gtm-session-fetcher repository has change the way it declares on the `Package.swift`the `sources` and now uses a `publicHeadersPath` (to be honest not sure if it's related but it looks like, maybe Tuist doesn't handle this correctly?) [diff](https://github.com/google/gtm-session-fetcher/compare/v1.7.2...v2.0.0#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR35)

Trying a project with Firebase 9.1.0 or 9.2.0 as a dependency with regular SPM without tuist, the project builds fine, so I think there was no point to open the bug to Firebase iOS project.

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project 
[app_with_spm_dependencies.zip](https://github.com/tuist/tuist/files/8989385/app_with_spm_dependencies.zip)

2. Run `tuist fetch`
3. Run `tuist generate`
4. See the error `'GTMSessionFetcher/GTMSessionFetcher.h' file not found`

### Error log

```
/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/gtm-session-fetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcherLogging.h:16:9: 'GTMSessionFetcher/GTMSessionFetcher.h' file not found
```

### Error screenshots

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3817679/175879204-92037a6e-0fe8-45a3-aeb2-c31d4d29423b.png">

### Additional context

- macOS version: 12.4
- Tuist version: 3.7.0
- Xcode version: 13.4.1

**Comment by danyf90** [comment] 2022-06-27 07:24
Tuist should handle it, but there is probably something else. I'll try to have a look when I have time 🙏

**Comment by Alexsilvacodes** [comment] 2022-06-29 10:27
We are currently experiencing this same one, did not find any solution yet, will let you know if we find it

**Comment by danyf90** [comment] 2022-07-15 07:52
Tried with latest firebase (9.3.0) and seems to work locally, opened a PR to validate it in CI as well

**Comment by unxavi** [comment] 2022-07-18 06:37
@danyf90  I just tested this with Tuist 3.8.0 and Firebase 9.3.0 and the issues seems to be present if the gtm-session-fetcher.git resolves to version 2.0.0

```Creating working copy for https://github.com/google/gtm-session-fetcher.git
Working copy of https://github.com/google/gtm-session-fetcher.git resolved at 2.0.0```

This is the package.resolved I get 

```{
  "pins" : [
    {
      "identity" : "abseil-cpp-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/abseil-cpp-SwiftPM.git",
      "state" : {
        "revision" : "d302de612e3d57c6f4afaf087da18fba8eac72a7",
        "version" : "0.20220203.1"
      }
    },
    {
      "identity" : "boringssl-swiftpm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/boringssl-SwiftPM.git",
      "state" : {
        "revision" : "79db6516894a932d0ddaff3b05b9da1e4f6c4069",
        "version" : "0.9.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "8467858fc4cee858511380ac0f9ea5a17d007b5d",
        "version" : "9.3.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "f54f60d0164d887e1174fa51ab2efe48a8e9d178",
        "version" : "9.3.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "b905c49326b72211531ed9d7baa02d724828a8dc",
        "version" : "9.1.4"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "f4abe56ce62a779e64b525eb133c8fc2a84bbc1f",
        "version" : "7.7.1"
      }
    },
    {
      "identity" : "grpc-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/grpc/grpc-ios.git",
      "state" : {
        "revision" : "2af4f6e9c2b18beae228f50b1198c641be859d2b",
        "version" : "1.44.2-grpc"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "19605024d59eaefdb1f6a2cb11ebe75df4421126",
        "version" : "2.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "3e4e743631e86c8c70dbc6efdc7beaa6e90fd3bb",
        "version" : "2.1.1"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "e1499bc69b9040b29184f7f2996f7bab467c1639",
        "version" : "1.19.0"
      }
    }
  ],
  "version" : 2
}
```

Could it be that the CI is not resolving to the lastest version or has some chace o lockfile?

**Comment by danyf90** [comment] 2022-07-18 07:02
> Could it be that the CI is not resolving to the lastest version or has some chace o lockfile?

That's possible, could you please create a branch in which you replicate the issue on the `app_with_spm_dependecies` fixture? 🙏

**Comment by unxavi** [comment] 2022-07-19 16:03
@danyf90  I believe this one should fail https://github.com/tuist/tuist/pull/4625

**Comment by danyf90** [comment] 2022-08-01 09:30
@unxavi, for your last comment on https://github.com/tuist/tuist/pull/4625, if you have some time to play with the generated Xcode project and you manage to make it compiling by changing settings manually from Xcode it would be useful for anyone who try to have a look at the issue 🙏

**Comment by danyf90** [comment] 2022-08-21 09:29
Closing as duplicate of https://github.com/tuist/tuist/issues/4688

**Closed by danyf90** 2022-08-21 09:29 UTC
Labels: domain:dependencies-swift
