### ISSUE TITLE
Github Pages docs are all 404s

### ISSUE THREAD

**Issue by stevelandeyasana** [tuist/tuist#4696] opened 2022-08-26 17:18 UTC
### What happened?

I'm trying to look at the manifests reference, but all the links are broken. For example:

https://tuist.github.io/tuist/main/documentation/projectdescription/project

![Screen Shot 2022-08-26 at 10 17 32 AM](https://user-images.githubusercontent.com/38225497/186958151-51ad6980-3370-45c7-b1f8-1d3d5bae86ac.png)

This has been true for a few days now, I think.

### How do we reproduce it?

Visiting the link should be sufficient

### Error log

n/a

### macOS version

n/a

### Tuist version

main

### Xcode version

n/a

**Comment by ramden** [comment] 2022-08-28 22:00
Wanted to report the same bug. This ticket deserves high prio

**Comment by fortmarek** [comment] 2022-08-30 19:04
Hey, we're investigating this. The underlying issue can be observed [here](https://github.com/tuist/tuist/runs/8057405048?check_suite_focus=true#step:12:572). We unfortunately are not able to reproduce this locally as the issue is most likely tied to the fact that we run the docc generation on Ubuntu instead of macOS. If you have an idea what might be wrong, help would be greatly appreciated!

**Comment by fortmarek** [comment] 2022-08-30 20:04
This has been now fixed by moving from Ubuntu to macOS runner. Thanks for having the patience 🤞

**Closed by fortmarek** 2022-08-30 20:04 UTC
Labels: type:bug

**Comment by Saik0s** [comment] 2022-09-01 23:11
This problem is happening again.

**Comment by ramden** [comment] 2022-09-04 09:40
Yes. Not fixed 😔
