### ISSUE TITLE
Project with cached Realm dependency fails to build

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [tuist/tuist#4203] opened 2022-02-28 21:07 UTC
**Describe the bug**
I have configured SPM dependencies in Dependencies.swift. And successfully cached them using `tuist cache warm`. But after opening the project `tuist generate`, it is not possible to build the project
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Realm/Realm.h"
        ^
/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-cocoa/include/Realm/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-cocoa/include/Realm/Realm.h:21:9: note: did not find header 'RLMArray.h' in framework 'Realm' (loaded from '/Library/Developer/Xcode/DerivedData/App-bljxpuzydgowkacdedheagpsioon/Build/Products/Debug-iphoneos')
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'
```

**To Reproduce**

1. Setup SPM packages in Decencies.swift with Realm 
```swift
let spm = SwiftPackageManagerDependencies([
         .remote(url: "https://github.com/realm/realm-cocoa.git", requirement: .exact("10.17.0"))
])

let dependencies = Dependencies(
    swiftPackageManager: spm,
    platforms: [.iOS]
)
```
2. Run `tuist fetch`
3. Run `tuist cache warm -x`
4. Run `tuist generate -x`
5. Build project in Xcode

**Expected behavior**
The project is built without errors

**Screenshots**
<img width="649" alt="image" src="https://user-images.githubusercontent.com/39379705/156058044-d80b3bc7-7661-4df3-b9ef-f7c7241b779b.png">

**Desktop (please complete the following information):**

OS: macOS 12.0.1
Tuist version 3.0
M1 Mac

**Comment by danyf90** [comment] 2022-03-01 08:52
Duplicate of https://github.com/tuist/tuist/issues/3928

**Closed by danyf90** 2022-03-01 08:52 UTC
