### ISSUE TITLE
📦 [Dependencies.swift][SPM] 'No such module' with custom configurations

### ISSUE THREAD

**Issue by lucasmpaim** [tuist/tuist#4129] opened 2022-02-08 14:20 UTC
**Describe the bug**
When building with a custom configuration using SPM packages with `Dependencies.swift`, we receive a 'No such module' error.

**To Reproduce**

1. Create a project with custom configurations
2. Add SPM packages using `Dependencies.swift` file
3. Create a local framework that depends of the SPM
4. Build the main project using a custom configuration
5. See error

**Expected behavior**
A successfully build

**Desktop (please complete the following information):**

- OS: Monterey (12.1)
- Version 2.7.2

**Additional context**

I found this issue #3599 and has applied the changes of #3683, but the problem still happening.

<details>
  <summary>tuist generate output</summary>
<p>

```bash
Using bundled version at path /Users/lucasmpaim/banco/ios/.tuist-bin
Built ProjectDescriptionHelpers in (0.343s)
Target 'Bid' has been linked from target 'AppApp', target 'CoreRepository', target 'CoreRepositoryInterface', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'Bid' has been linked from target 'CoreRepositoryInterface' and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'Bid' has been linked from target 'CoreRepository' and target 'CoreRepositoryInterface', it is a static product so may introduce unwanted side effects.
Target 'DateHelper' has been linked from target 'AppApp', target 'AppCore', target 'AppNetwork', target 'Credits', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'DateHelper' has been linked from target 'AppCore', target 'AppNetwork', and target 'Credits', it is a static product so may introduce unwanted side effects.
Target 'DateHelper' has been linked from target 'AppCore', target 'AppNetwork', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'DateHelper' has been linked from target 'AppCore' and target 'AppNetwork', it is a static product so may introduce unwanted side effects.
Target 'InputMask' has been linked from target 'AppApp' and target 'AppUI', it is a static product so may introduce unwanted side effects.
Target 'JWTDecode' has been linked from target 'AppApp' and target 'AppNetwork', it is a static product so may introduce unwanted side effects.
Target 'KeychainAccess' has been linked from target 'AppApp', target 'AppCore', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'KeychainAccess' has been linked from target 'AppCore' and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'Lottie' has been linked from target 'AppApp' and target 'AppCore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppApp', target 'AppCore', target 'AppExtract', target 'AppNetwork', target 'AppPermissions', target 'AppUI', target 'Credits', target 'DataLayer', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore' and target 'AppExtract', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore', target 'AppNetwork', target 'AppUI', target 'Credits', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore', target 'AppNetwork', target 'DataLayer', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore', target 'AppNetwork', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore' and target 'AppPermissions', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore', target 'AppUI', and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore' and target 'AppUI', it is a static product so may introduce unwanted side effects.
Target 'PromiseKit' has been linked from target 'AppCore' and target 'ObjectStore', it is a static product so may introduce unwanted side effects.
Target 'Realm' has been linked from target 'AppApp', target 'CoreRepository', target 'CoreRepositoryInterface', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'Realm' has been linked from target 'CoreRepositoryInterface' and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'Realm' has been linked from target 'CoreRepository' and target 'CoreRepositoryInterface', it is a static product so may introduce unwanted side effects.
Target 'RealmCore' has been linked from target 'AppApp', target 'CoreRepository', target 'CoreRepositoryInterface', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'RealmCore' has been linked from target 'CoreRepositoryInterface' and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'RealmCore' has been linked from target 'CoreRepository' and target 'CoreRepositoryInterface', it is a static product so may introduce unwanted side effects.
Target 'RealmSwift' has been linked from target 'AppApp', target 'CoreRepository', target 'CoreRepositoryInterface', and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'RealmSwift' has been linked from target 'CoreRepositoryInterface' and target 'DataLayer', it is a static product so may introduce unwanted side effects.
Target 'RealmSwift' has been linked from target 'CoreRepository' and target 'CoreRepositoryInterface', it is a static product so may introduce unwanted side effects.
Target 'SnapKit' has been linked from target 'AppApp', target 'AppExtract', target 'AppUI', and target 'Credits', it is a static product so may introduce unwanted side effects.
Target 'SnapKit' has been linked from target 'AppUI' and target 'Credits', it is a static product so may introduce unwanted side effects.
Target 'SwiftRichString' has been linked from target 'AppApp', target 'AppCore', target 'AppUI', and target 'Credits', it is a static product so may introduce unwanted side effects.
Target 'SwiftRichString' has been linked from target 'AppCore', target 'AppUI', and target 'Credits', it is a static product so may introduce unwanted side effects.
Target 'SwiftRichString' has been linked from target 'AppCore' and target 'AppUI', it is a static product so may introduce unwanted side effects.
The project 'NetAnalyser' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'CryptoSwift' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'SnapKit' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'MarqueeLabel' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'JWTDecode' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'Lottie' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'PromiseKit' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'SDWebImage' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'IQKeyboardManagerSwift' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'SwiftRichString' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'UXCam' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'RealmDatabase' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'Realm' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'KeychainAccess' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'Alamofire' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'DateHelper' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'Adjust' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
The project 'InputMask' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
Generating workspace App.xcworkspace
Generating project AppExtract
Generating project AppPermissions
Generating project AppFlags
Generating project AppLogger
Generating project AppCrypto
Generating project AppCore
Generating project App
Generating project AppSelfie
Generating project AppUI
Generating project CoreRepository
Generating project CoreTesting
Generating project Credits
Generating project DataLayer
Generating project FeatureFlags
Generating project AppNetwork
Generating project ObjectStore
Generating project ProjectConfig
Generating project ReleaseFlags
Generating project Alamofire
Generating project CryptoSwift
Generating project DateHelper
Generating project IQKeyboardManagerSwift
Generating project JWTDecode
Generating project KeychainAccess
Generating project MarqueeLabel
Generating project NetAnalyser
Generating project PromiseKit
Generating project SDWebImage
Generating project SnapKit
Generating project SwiftRichString
Generating project InputMask
Generating project UXCam
Generating project Adjust
Generating project Lottie
Generating project RealmDatabase
Generating project Realm
Project generated.
Total time taken: 4.516s
```
</p>
</details>

<details>
  <summary>Dependencies.swift</summary>
<p>

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: [],
    swiftPackageManager: SwiftPackageManagerDependencies(
        [
            .remote(url: "https://github.com/SnapKit/SnapKit", requirement: .exact("5.0.1")),
            .remote(url: "https://github.com/melvitax/DateHelper", requirement: .exact("4.4.1")),
            .remote(url: "https://github.com/malcommac/SwiftRichString.git", requirement: .exact("3.6.0")),
            .remote(url: "https://github.com/krzyzanowskim/CryptoSwift", requirement: .exact("1.4.0")),
            .remote(url: "https://github.com/mxcl/PromiseKit.git", requirement: .exact("6.16.3")),
            .remote(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", requirement: .exact("4.2.2")),
            .remote(url: "https://github.com/auth0/JWTDecode.swift.git", requirement: .exact("2.4.0")),
            .remote(url: "https://github.com/airbnb/lottie-ios.git", requirement: .exact("3.1.5")),
            .remote(url: "https://github.com/cbpowell/MarqueeLabel.git", requirement: .exact("4.0.2")),
            .remote(url: "https://github.com/Alamofire/Alamofire", requirement: .exact("5.1.0")),
            .remote(url: "https://github.com/RedMadRobot/input-mask-ios", requirement: .exact("6.0.0")),
            .remote(url: "https://github.com/lucasmpaim/NetAnalyser.git", requirement: .exact("0.0.3")),
            .remote(url: "https://github.com/hackiftekhar/IQKeyboardManager.git", requirement: .exact("6.5.8")),
            .remote(url: "https://github.com/SDWebImage/SDWebImage", requirement: .exact("5.12.1")),
            .remote(url: "https://github.com/adjust/ios_sdk", requirement: .exact("4.29.3")),
            .remote(url: "https://github.com/uxcam/ios-sdk", requirement: .exact("3.3.0")),
            
            .remote(
                url: "https://github.com/realm/realm-swift.git",
                requirement: .exact("10.22.0")
            )
            
        ],
        baseSettings: Settings.settings(
            configurations: [
                .debug(name: "Prod-Debug"),
                .debug(name: "QA-Debug"),
                .debug(name: "Debug"),
                .release(name: "Prod-Release"),
                .release(name: "QA-Release"),
                .release(name: "Release")
            ]
        )
    ),
    platforms: [.iOS]
)
```
</p>
</details>

When I made a build with `Debug` configuration, everything works file, but when I use a custom configuration like `Prod-Debug` I receive errors like: 

```bash
❌  /Users/lucasmpaim/banco/ios/AppPackages/AppCore/Sources/AppCore/DateHelper/Private/DateHelperFormatter.swift:9:8: no such module 'DateHelper'

import DateHelper
```
For the packages, I just create the configurations with the same name than my root project and local packages without the .xcconfig files, also failed with a empty .xcconfig file.

Something weird, is that I receive warnings about the project:

```bash
The project 'DateHelper' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Prod-Debug (debug), Prod-Release (release), QA-Debug (debug), QA-Release (release), Release (release)]
```
but when I look the generated project all configurations are there

<details>
<summary>SPM Screenshot</summary>

<img width="944" alt="Captura de Tela 2022-02-08 às 11 17 23" src="https://user-images.githubusercontent.com/7849484/153005044-66924360-7ea8-4cf4-a563-0e1af73ca1b9.png">

</details>

<details>
<summary>Root Project Screenshot</summary>
<img width="600" alt="Captura de Tela 2022-02-08 às 11 19 31" src="https://user-images.githubusercontent.com/7849484/153005439-c41a8386-83e2-4e89-84d8-56449abf4584.png">
</details>

Demo: https://github.com/lucasmpaim/TuistDependencyDemo

**Comment by danyf90** [comment] 2022-02-08 14:45
Hello @lucasmpaim 👋 
If you have custom configurations, you need to pass the same configurations in the `baseSettings` inside `Dependencies.swift`.

Please let us know if this fixes your problem

**Comment by lucasmpaim** [comment] 2022-02-08 15:03
Hey @danyf90 , I have set the same pair of config (names and `xcconfig` files) from exactly same extension and I still receiving the same error

**Comment by lucasmpaim** [comment] 2022-02-08 15:17
Another thing that I notice, Debug and Release configurations are not replaced or merged.

Because on my debug xcconfig file, have this line:

```bash
CODE_SIGN_ENTITLEMENTS=$(SRCROOT)/../../Entitlements/Bari-DEV.entitlements
```

but this not work for the place where the SPM project are located, on fact, this fail on the custom config, but not on debug/release.

**Comment by lucasmpaim** [comment] 2022-02-08 20:14
I have created a minimal project to reproduce this bug.

https://github.com/lucasmpaim/TuistDependencyDemo

**Comment by mgray88** [comment] 2022-02-10 14:28
2nd this. I'm also still experiencing the issue in #3599. While tuist does create the configurations for the SPM projects, it doesn't bring over any of the configuration values from the configurations they're derived from.

So in my Dependencies.swift I have the following in `baseSettings`:

```swift
configurations: [
  .debug(name: "Debug"),
  .release(
  	name: "AdHoc",
  	settings: SettingsDictionary()
  	  .gccPreprocessorMacro("ADHOC=1")
      .swiftCompilationCondition("ADHOC")
  ),
  .release(name: "Release"),
  .release(
    name: "QA",
    settings: SettingsDictionary()
	  .gccPreprocessorMacro("QA=1")
	  .swiftCompilationCondition("QA")
  ),
]
```

**Comment by fortmarek** [comment] 2022-02-10 18:59
Thanks @lucasmpaim for the investigation. 

It is definitely possible to add this flag.

I wonder how the project would behave if the configuration was not named `Prod-Debug`? I remember that Xcode searches for `Debug` in the name and then automatically sets some settings as it does for regular `Debug` scheme.

**Comment by mflknr** [comment] 2022-03-16 09:39
Any news on this one? I have a similar issue when creating custom configs like above mentioned. One is named "Debug" the other "Tests". Both use the exact same .xcconfig files but tests will not be able to compile due to not finding external modules.

**Comment by vandadnp** [comment] 2022-03-31 11:33
Hi and thank you for Tuist, I appreciate the hard work that has gone into creating Tuist

We have the same issue unfortunately and our builds are failing because of this. Any updates please?

Thank you again
/v

**Comment by lucasmpaim** [comment] 2022-03-31 11:48
> Hi and thank you for Tuist, I appreciate the hard work that has gone into creating Tuist
> 
> We have the same issue unfortunately and our builds are failing because of this. Any updates please?
> 
> Thank you again /v

Adding the new entry on `FRAMEWORK_SEARCH_PATHS` as describe here: https://github.com/tuist/tuist/issues/4129#issuecomment-1035220493, don't work?

This workaround has worked for me, but I have to made some extra work to don't have a duplicated binaries on the project.

**Comment by danyf90** [comment] 2022-03-31 13:03
I think it has been fixed by @mstfy  in [3.1.0](https://github.com/tuist/tuist/blob/0df862aba54b01fbc931468ef439f3596b19db5f/CHANGELOG.md?plain=1#L16), have you tried it out?

**Comment by vidugloeck** [comment] 2022-04-07 13:08
I have a [tiny sample project](https://github.com/vidugloeck/TuistCustomBuildConfigBug) ( it has dependency on AlamoFire + custom 'Beta' configuration) that reproduces the issue with `3.1.0`. I initially created the sample project for #4250 

@danyf90 could you have a look at it?

**Comment by danyf90** [comment] 2022-04-07 13:27
@vidugloeck I see you are not defining the custom config in the Dependencies.swift file

**Comment by nagra** [comment] 2022-05-03 07:15
@vidugloeck it would be much appreciated if you could provide the sample bit of code you added to fix the sample project 🙏. 

I think that's the missing link here, I'm not entire surely what needs to be added in that respect.

**Comment by vidugloeck** [comment] 2022-05-03 08:09
Hi @nagra, you can find the fix here in the [sample project]( https://github.com/vidugloeck/TuistCustomBuildConfigBug/blob/main/Tuist/Dependencies.swift#L7-L11).

**Comment by danyf90** [comment] 2022-05-03 08:16
Closing as should be fixed in 3.1.0, if not, feel free to reopen it or open a new one

**Comment by nagra** [comment] 2022-05-03 08:16
> Hi @nagra, you can find the fix here in the [sample project](https://github.com/vidugloeck/TuistCustomBuildConfigBug/blob/main/Tuist/Dependencies.swift#L7-L11).

Ah okay, I tried this in a simple project, but wasn't working. Will try it again later today and see if it works 🤞.

**Closed by danyf90** 2022-05-03 08:16 UTC

**Comment by PatilManoj1717** [comment] 2022-07-08 15:12
I am facing similar issue, can you help on this [#4597](https://github.com/tuist/tuist/issues/4597)
