### ISSUE TITLE
[Dependencies.swift]: cannot use external dependencies from ObjectiveC code

### ISSUE THREAD

**Issue by MariusDeReus** [tuist/tuist#4180] opened 2022-02-22 08:15 UTC
**Describe the bug**
Our project uses the well known `CocoaLumberjack` framework for logging. We come from CocoaPods and are converting to Tuist and its Dependencies. Our main project still has quite some ObjC classes that need access to this framework.
When we use CocoaPods, the framework is build containing a folder `Headers` with all the ObjC headers that can then be imported with `#import <CocoaLumberjack/CocoaLumberjack.h`.
Using pure SPM (without Tuist) results in a build of the framework with a `.swiftmodule` that can be imported in ObjC with `@import CocoaLumberjack`.
Using Tuist dependencies the build framework has none of both and we have no way to use the framework from ObjC. (unless we oversee a possible setting/option).

**To Reproduce**
- Add: 
````
let packages = ProjectDescription.SwiftPackageManagerDependencies(
    [.remote(url: "https://github.com/CocoaLumberjack/CocoaLumberjack", requirement: .upToNextMajor(from: "3.7.4"))]
````
to `Dependencies.swift`
- (BTW, also tried to add `"CocoaLumberjack": .framework` to the `productTypes` parameter, that did not make a difference.
- run `tuist fetch dependencies`
- run `tuist generate --open`
- build the project and go to the build folder in Finder
- There look for the CocoaLumberjack framework build result and see if it has headers or swift module (it hasn't)

**Expected behavior**
We expected there would be a way to add this external dependency and use it from ObjC classes.
For what its worth: using the deprecated way to add SPM packages to a target with `.package(...)` and not dependencies.swift, it works as expected.  

**Screenshots**
Attached 3 screenshots with the build result when importing the dependency with CocoaPods, pure SPM and Tuist Dependencies.

**Desktop (please complete the following information):**
- OS: macOS 12.2, 
- Xcode: 13.2.1
- Version 2.7.2

Build after using Dependencies.swift:
<img width="311" alt="Imported via Tuist dependencies" src="https://user-images.githubusercontent.com/9931253/155090356-dcbcc8fe-37b0-4ac4-b308-78af08e413d2.png">

Build after using CocoaPods:
<img width="368" alt="Imported via CocoaPods" src="https://user-images.githubusercontent.com/9931253/155090360-ec163291-459b-4a8f-8ca6-0d7015b59f44.png">

Build after using pure SPM, or deprecated Tuist package dependency:
<img width="357" alt="Imported via SPM" src="https://user-images.githubusercontent.com/9931253/155090368-20152b1f-253a-43c9-babb-cf047d8f0dee.png">

**Comment by danyf90** [comment] 2022-02-22 08:19
Thanks for reporting the issue 👍 
Could you also provide a sample project to replicate it? 🙏

**Comment by MariusDeReus** [comment] 2022-02-22 09:53
Yes @danyf90, here it is.
[TestTuist.zip](https://github.com/tuist/tuist/files/8115541/TestTuist.zip)

**Comment by MariusDeReus** [comment] 2022-02-22 10:55
Just discovered that the legacy way of adding Swift packages works correctly. Added this to the description above and added a sample project using this way.

**Comment by MariusDeReus** [comment] 2022-03-15 16:32
@danyf90 without the intention to be pushy; is this something that will be fixed in the foreseeable future? It seems something I cannot work around, so it blocks using Tuist for our project. 
Using the deprecated way of using package dependencies causes errors when I use `tuist test`. Moreover, multiple subprojects depend on this same dependency, so I really need to use the new Dependencies.swift for this.
Is this something I could help with, or is this too deep in the core of Tuist?

**Comment by danyf90** [comment] 2022-03-15 17:23
Hello @MariusDeReus 👋 
I think the error is the same as in https://github.com/tuist/tuist/issues/3762 (i.e. modulemap not properly handled by ObjC modules).
We would need some time to understand how we can fix it, if you want to dedicate some time to it it would be great.
If you need any guidance just ask me on slack 🚀

**Comment by danyf90** [comment] 2022-03-17 17:10
Explanation and workaround for this reported in https://github.com/tuist/tuist/pull/4255

**Comment by danyf90** [comment] 2022-04-12 09:47
Closed as duplicate of https://github.com/tuist/tuist/issues/3762

**Comment by danyf90** [comment] 2022-04-12 09:48
Closed as duplicate of https://github.com/tuist/tuist/issues/3762

**Closed by danyf90** 2022-04-12 09:47 UTC

**Comment by Buju77** [comment] 2022-10-14 17:22
@MariusDeReus Hi, I am currently facing the exact same issue. I'm trying to migrate to Tuist and also have the CocoaLumberjack dependency.

However I am unable to make it work. Xcode still complains that it can't find `<CocoaLumberjack/CocoaLumberjack.h>`. I've read the note about ObjC in #4255 but I still don't understand it fully.

I've tried various different variants with no success:

```swift
let targetSettings: Settings = .settings(
    base: [
        "OTHER_LDFLAGS": "-ObjC -framework \"CocoaLumberjack\"",
        "HEADER_SEARCH_PATHS": ["$(inherited)",
                                "Tuist/Dependencies/SwiftPackageManager/.build/checkouts/CocoaLumberjack/**",
//                                "Tuist/Dependencies/SwiftPackageManager/.build/checkouts/CocoaLumberjack/Sources/**",
//                                "Tuist/Dependencies/SwiftPackageManager/.build/checkouts/CocoaLumberjack/Sources/CocoaLumberjack/include/CocoaLumberjack",
//            "\"Tuist/Dependencies/SwiftPackageManager/.build/checkouts/CocoaLumberjack/Sources/CocoaLumberjack/Supporting Files\""],
    ],
    configurations: [
        .debug(name: "Debug", xcconfig: "Tuist/xcconfigs/RTLogging.xcconfig"),
        .release(name: "Release", xcconfig: "Tuist/xcconfigs/RTLogging.xcconfig"),
    ]
)

// and then setting it
        Target(
            name: "RTLogging",
            platform: .iOS,
            product: .framework,
            ...
            settings: targetSettings
        ),
```

Do I need to replace every `#import <CocoaLumberjack/CocoaLumberjack.h>` statement in my code with `@import CocoaLumberjack;` for tuist to work?

**Comment by sanghyeok-kim** [comment] 2024-06-03 12:20
@pepicrft 
Is there still nothing resolved in Tuist regarding this?
Is setting `HEADER_SEARCH_PATHS` for headers of all Objc libraries like in #3762 the only solution for now?

**Comment by sanghyeok-kim** [comment] 2024-06-04 09:00
If anyone experiencing this issue, **update Tuist to version `4.1.0` or later.**

[`4.1.0`](https://github.com/tuist/tuist/releases/tag/4.1.0) version fixes this issue 🙂
(there are exceptions depending on the package,
but you should be able to find the header path for most libraries that contain Objc headers).

- #5887
