### ISSUE TITLE
Linebreaks in  ExecutionAction.scriptText are not preserved

### ISSUE THREAD

**Issue by alexanderwe** [tuist/tuist#2650] opened 2021-03-12 11:45 UTC
**Describe the bug**
When I provide a string value to the `ExecutionAction.scriptText`  property, the line breaks are not respected and the script gets squashed into one line when I look at the action in Xcode.

**To Reproduce**

For example create an `ArchiveAction` which contains a post action which script text contains line breaks. 

```swift
let postArchiveTest = """
# https://github.com/firebase/firebase-ios-sdk/issues/6472
LOGFILE="${ARCHIVE_PATH}/static-frameworks.log"
echo "Removing static frameworks from ${WRAPPER_NAME} archive" > $LOGFILE
find "${ARCHIVE_PRODUCTS_PATH}/Applications/${WRAPPER_NAME}" -name '*.framework' -print0 | while IFS= read -r -d '' fm; do
    name=$(basename "${fm}" .framework)
    target="${fm}/${name}"
    echo "Checking: ${fm}" >> $LOGFILE
    if file "${target}" | grep -q "current ar archive"; then
        rm -rf "${fm}"
        echo "Removed static framework: ${fm}" >> $LOGFILE
    fi
done
"""

let archiveAction = ArchiveAction(configurationName: "Debug",
                                  revealArchiveInOrganizer: true,
                                  postActions: [
                                    .init(title: "Fix IPA bug", scriptText: postArchiveTest, target: "MyTarget")
                                  ]
)
```
Add this archiveAction to any scheme you like. After executing `tuist generate` and examining the scheme and the created post archive action, the script is just in one line, whereas I would expect it to be "multilined"

**Expected behavior**
Line Breaks should be preserved. 

**Screenshots**
<img width="1027" alt="Screenshot 2021-03-12 at 12 44 27" src="https://user-images.githubusercontent.com/12934015/110936119-b0a1e180-8330-11eb-88a4-cf6f1ed00f00.png">

**Desktop (please complete the following information):**

- OS: macOS 11.2.2 (20D80)
- Version 1.3.2

**Comment by tiarnann** [comment] 2021-03-16 20:28
The issue causing this is in the `AEXML` package itself. There is a fix in this PR that was made back in early January https://github.com/tadija/AEXML/pull/177 but it might be another while until it is merged 😅

**Comment by kwridan** [comment] 2021-03-17 08:03
Thanks for raising this @alexanderwe! and thank you @tiarnann for finding the root cause.

You are right it might take some time, we could potentially doe the escaping in Tuist while this issue is resolved upstream. Will take a look at this.

**Comment by alexanderwe** [comment] 2021-03-17 08:33
@tiarnann, @kwridan Thanks a lot to you both for taking a look into this issue "

As a workaround for this issue I referenced a shell script in my `$SRCROOT` which then contains the necessary line breaks. 

```shell

ArchiveAction(configurationName: "Debug",
                         revealArchiveInOrganizer: true,
                         postActions: [
                           .init(title: "Fix IPA bug", scriptText: "sh \"$SRCROOT/Scripts/FixIpaBug.sh\"", target: "MyTarget)")
                         ]
)
```

**Comment by kwridan** [comment] 2021-03-17 08:37
> we could potentially doe the escaping in Tuist while this issue is resolved upstream. Will take a look at this.
ah no that isn't possible (at least with the naive idea I had) - If we attempt add the escaping ourselves, it will itself get escaped 😅

> As a workaround for this issue I referenced a shell script in my $SRCROOT which then contains the necessary line breaks.

Ya that is the best option atm 👍

**Comment by alexanderwe** [comment] 2021-03-17 08:43
Oh I see 😄 

Alright, then I keep my workaround as long as tadija/AEXML#177 is not fixed. Should we keep this issue open since the underlying error is not resolved yet ?

**Comment by pepibumur** [comment] 2021-03-17 10:14
> Alright, then I keep my workaround as long as tadija/AEXML#177 is not fixed. Should we keep this issue open since the underlying error is not resolved yet ?

I'd say let's keep it to make sure we don't forget about this.

**Comment by nnsnodnb** [comment] 2021-09-13 11:29
[tuist/XcodeProj](https://github.com/tuist/XcodeProj) v8.2.0 released.
This issue has been fixed by this version.

**Closed** 2021-09-13 21:18 UTC
Labels: type:bug, domain:generation

**Comment by alexanderwe** [comment] 2021-09-14 20:01
@nnsnodnb, @adellibovi  Thanks a lot for the fix
