### ISSUE TITLE
`tuist cache warm` fails if DerivedData location is configured as Relative in Xcode settings

### ISSUE THREAD

**Issue by mihaicris-adoreme** [tuist/tuist#3254] opened 2021-08-02 08:22 UTC
**Describe the bug**
Tuist caching fails if the user has the setting for location of DerivedData folder as **Relative**

**To Reproduce**
1. Change the Location of DerivedData Folder to Relative
2. Give `tuist cache warm`
Command fails with message 
`Couldn't find framework '{{Framework_Name}}.framework' in the derived data directory: /Users/{{User_Name}}/Library/Developer/Xcode/DerivedData`

**Expected behaviour**
Caching command should succeed.

**Note**
3 Change the Location of DerivedData Folder to Default
4. Give `tuist cache warm`
Command succeeds.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**

- OS: 11.5.1 (20G80)
- Swift : Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
- Xcode 12.5.1
- Tuist: 1.47.0

**Additional context**
Maybe the DerivedData path used by Tuist is hardcoded?

**Comment by fortmarek** [comment] 2021-08-03 06:25
Hi @mihaicris-adoreme!

I think the issue is that for warming the cache, we use [this](https://github.com/tuist/tuist/blob/main/Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift#L36) function - which uses `xcodebuild` under the hood. It also gets passed a `derivedDataPath` which is inferred from `DeveloperEnvironment`: https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Utils/DeveloperEnvironment.swift#L37

AFAICT, we should be taking the relative path into the account but it might be worth looking into what the `DeveloperEnvironment` returns. I can take a look into it further at some later point, this is just after some quick investigation - let me know if you'd like to debug this, I can try to give you some more pointers how to do that.

**Comment by mihaicris-adoreme** [comment] 2021-08-05 14:37
Hi @fortmarek,

I started looking into this, and I noticed:

`if let customLocation = try? System.shared.capture("/usr/bin/defaults", "read", "com.apple.dt.Xcode IDECustomDerivedDataLocation")`
This method is not giving a proper value (it returns an empty string at runtime), from the terminal it returns "DerivedData" but sometimes also an empty string so it doesn't look reliable to me, also it cannot be used as an absolute path.
I've made a change to get the DerivedData path with xcodesettings command instead to get the absolute value of the DerivedData folder (maybe there is an utility in the codebase to make this simpler):

```swift
if let xcodeBuildSettings = try? System.shared.capture(["xcodebuild", "-showBuildSettings"]),
           let buildDirRow = (xcodeBuildSettings.components(separatedBy: "\n").first { $0.contains("BUILD_DIR = ")}) {
            let customPath = buildDirRow.drop { $0 != "/" }
            location = AbsolutePath(String(customPath)).upToComponentMatching(regex: "DerivedData")
        } else {
            // Default location
            location = fileHandler.homeDirectory.appending(RelativePath("Library/Developer/Xcode/DerivedData/"))
        }
```
It still doesn't work because tuist is creating the cached frameworks in one folder but look for them later to move them to .cache in another location

If that the sources are located at `/Users/{{username}}/test-tuist` and DerivedData setting is set to Relative then tuist will build the target framework in 
`/Users/{{username}}/test-tuist/DerivedData/**TestTuist**/Build/Products/Debug-iphonesimulator`

but later looks for them in 
`/Users/mihai.c/test-tuist/DerivedData/**TestTuist-ewbogjpuwbutbkcnzslqzsyxmfoc**/Build/Products/Debug-iphonesimulator
`

I think I need to pass the hash string to xcodebuild to create the correct path name with the hash in the target name.

**Comment by fortmarek** [comment] 2021-08-10 06:21
> For example, If the sources are located at /Users/{{username}}/test-tuist and DerivedData setting is set to Relative then tuist will build the target framework in:
/Users/{{username}}/test-tuist/DerivedData/TestTuist/Build/Products/Debug-iphonesimulator

Yeah, we're missing the hash string after `TestTuist` there. We use [this](https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Utils/DerivedDataLocator.swift) component for locating derived data, so you might have to change the logic there.

**Comment by kabirkhaan** [comment] 2022-05-17 22:05
Hello, i will love to contribute on this

**Comment by fortmarek** [comment] 2022-05-18 07:13
Hey @kabirkhaan, that's great to hear 🚀 

This issue already contains investigation and some tips to look into. I would suggest you try to reproduce the issue locally and step through what tuist does.

Afterwards, feel free to post any questions, here or on Slack 👀  We have some [documentation for contributors](https://docs.tuist.io/contributors/get-started) to get you started.

**Comment by kabirkhaan** [comment] 2022-05-29 13:43
### Investigation Report
**Unable to reproduce**

Steps:
- Change the derived data path
- run `./fourier generate tuist`
- run `tuist cache warm`

### Furture Details

_Derived data path is working fine_ with respect to following
- https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Utils/DeveloperEnvironment.swift#L37
I tried to change the code by reading the `com.apple.dt.Xcode .plist` and get the value of `IDECustomDerivedDataLocation` same result.

- With respect to my investigation I don't think so `Absolute Path` have any impact
- I went throw the code  the following code from [this class](https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Utils/DerivedDataLocator.swift) as per suggestion but unable to find the logic where it produce `empty hash`
```
 guard let firstHalf = partitions.first,
              let secondHalf = partitions.last
        else {
            throw HashingError.invalidPartitioning
        }
```

**Comment by fortmarek** [comment] 2022-05-30 19:52
Hey @kabirkhaan 👋 

Thanks for looking into this. We can potentially close this if we are no longer able to reproduce. @mihaicris-adoreme, could you confirm this? 🙏

**Comment by danyf90** [comment] 2022-08-06 17:33
Closing this as it seems to be no longer reproducible, feel free to reopen it if you still face the issue

**Closed by danyf90** 2022-08-06 17:33 UTC
Labels: type:bug, good first issue, domain:cache, hacktoberfest
