### ISSUE TITLE
Adding a dependency using a SwiftPM plugin doesn't execute said plugin

### ISSUE THREAD

**Issue by kiliankoe** [tuist/tuist#5011] opened 2023-01-26 11:53 UTC
### What happened?

Sorry for the overly complex title, the gist of my problem is this: I have a dependency on a SwiftPM package. This package uses SwiftGen as a new SwiftPM plugin to generate asset wrappers on the fly.

```swift
let package = Package(
    // ...
    dependencies: [
        .package(url: "https://github.com/SwiftGen/SwiftGenPlugin", from: "6.6.0")
    ],
    targets: [
        .target(
            name: "TargetName",
            dependencies: [],
            plugins: [
                .plugin(name: "SwiftGenPlugin", package: "SwiftGenPlugin")
            ]),
    ]
)
```

I'd expect Xcode to run this plugin once the package is being built, but that doesn't happen. Instead I see a whole bunch of build errors when building the app project telling me that it `cannot find 'Asset' in scope`, `Asset` being the type that's generated by SwiftGen.

Is there any other way I can trigger running the SwiftPM plugin?

### How do we reproduce it?

Depend on a package that relies on a SwiftPM plugin to generate assets.

I've created a minimal sample project here: 
[SamplePackageAndApp.zip](https://github.com/tuist/tuist/files/10508885/SamplePackageAndApp.zip)

It contains an empty app generated from the default SwiftUI tuist template that depends on an included local package that contains nothing but an asset catalog with a color and uses the aforementioned SwiftGen plugin to generate the Asset type for that.

### Error log

```sh
 SampleApp ❯ tuist build
Building scheme SampleApp
** BUILD FAILED **


The following build commands failed:
	SwiftCompile normal arm64 Compiling\ SamplePackage.swift /Users/kilian/Desktop/SamplePackage/Sources/SamplePackage/SamplePackage.swift (in target 'SamplePackage_ios' from project 'SamplePackage')
	CompileSwift normal arm64 /Users/kilian/Desktop/SamplePackage/Sources/SamplePackage/SamplePackage.swift (in target 'SamplePackage_ios' from project 'SamplePackage')
	SwiftCompile normal arm64 Compiling\ SampleAppApp.swift /Users/kilian/Desktop/SampleApp/Targets/SampleApp/Sources/SampleAppApp.swift (in target 'SampleApp' from project 'SampleApp')
(3 failures)
[SampleAppKit] Processing SampleAppKit-Info.plist
[SampleAppUI] Processing SampleAppUI-Info.plist
[SamplePackage_ios] Compiling TuistBundle+SamplePackageIos.swift
[SamplePackage_ios] Compiling SamplePackage.swift
❌ /Users/kilian/Desktop/SamplePackage/Sources/SamplePackage/SamplePackage.swift:5:32: cannot find 'Asset' in scope
        print("Sample Color: \(Asset.sampleColor.name)")
                               ^~~~~
[SampleAppUI] Compiling ContentView.swift
[SampleApp] Compiling TuistBundle+SampleApp.swift
[SampleAppKit] Compiling SampleAppKit.swift
[SampleApp] Compiling TuistAssets+SampleApp.swift
The 'xcodebuild' command exited with error code 65
```

### macOS version

12.6

### Tuist version

3.15.0

### Xcode version

14.2

**Comment by danyf90** [comment] 2023-01-26 12:10
Duplicate of https://github.com/tuist/tuist/issues/4909

Good to know that there is a bounty of 100$ on the issue in case you want to fix it!

**Closed by danyf90** 2023-01-26 12:10 UTC
Labels: type:bug

**Comment by kiliankoe** [comment] 2023-01-26 12:14
Ah thank you @danyf90, I wasn't able to find something related through searching earlier. I guess I should've typed "plug-in" instead of "plugin" 😬

**Comment by danyf90** [comment] 2023-01-26 12:15
> Ah thank you @danyf90, I wasn't able to find something related through searching earlier. I guess I should've typed "plug-in" instead of "plugin" 😬 

No worries!
