### ISSUE TITLE
Feature request: Add support for swift package manager registry service

### ISSUE THREAD

**Issue by bc-lee** [tuist/tuist#5398] opened 2023-09-07 03:42 UTC
### What problem or need do you have?

# Feature request

[Swift Package Registry Service](https://github.com/apple/swift-evolution/blob/6fea4962167a6141cf1c233ebad466ad701b9b65/proposals/0292-package-registry-service.md)  is a new feature introduced in Swift 5.7(Xcode 14.0). Before this, swift package manager resolves packages using Git URL, or local path. It allows developers to download packages without accessing git repositories. It also provides a way to manage access control for private packages.

When using a registry service, developers can use a package by specifying the organization name and package name. For example, these kinds of expression can be resolved by the swift package manager:
```swift
dependencies: [
   .package(id: "mona.LinkedList", .upToNextMinor(from: "1.1.0")),
   .package(id: "mona.RegEx", .exact("2.0.0"))
]
```

Refer to https://github.com/apple/swift-package-manager/pull/3787, https://github.com/apple/swift-package-manager/pull/4244 for more details.

Currently, tuist only supports Git URL and local path. [Link](https://github.com/tuist/tuist/blob/0f12ab4017af516e241e2f3642d02136d61e6875/Sources/ProjectDescription/Package.swift#L7)

```swift
public enum Package: Equatable, Codable {
    case remote(url: String, requirement: Requirement)
    case local(path: Path)

    private enum Kind: String, Codable {
        case remote
        case local
    }
}
```

I think it would be great if tuist supports the registry service.

### macOS version

13.5.1

### Tuist version

3.25.0

### Xcode version

14.3

**Comment by regularberry** [comment] 2023-11-08 17:09
We're able to successfully specify a swift package that's in a registry due to the Package.swift change, but we still hit "The dependency kind registry is not supported." when trying to use it in Tuist.

I suspect "registry" needs to be added to https://github.com/tuist/tuist/blob/e6d9acb6fcf521c67eb14e9ae8b64d706e0a16d8/Sources/TuistDependencies/SwiftPackageManager/Utils/SwiftPackageManagerGraphGenerator.swift#L94

**Comment by danyf90** [comment] 2023-11-09 12:09
Thanks @regularberry , could you please provide a sample project?

**Comment by danyf90** [comment] 2023-11-12 20:55
Closing for missing reproducible project, please open a new one if you can reproduce it

**Closed by danyf90** 2023-11-12 20:55 UTC
Labels: type:need/problem

**Comment by regularberry** [comment] 2023-11-14 14:32
This is admittedly pretty niche. I'm only aware of Artifactory supporting this service as of now: https://forums.swift.org/t/accepted-with-modifications-se-0292-package-registry-service/49849

If GitHub/Swift Package Index supports it, it will be much easier to test. Right now I'm using my company's registry
