### ISSUE TITLE
GoogleSignIn could not build Objective-C module 'GoogleSignIn'

### ISSUE THREAD

**Issue by Banck** [tuist/tuist#4471] opened 2022-05-20 15:36 UTC
## Describe the bug and the expected behavior

Hello!
Trying to integrate GoogleSignIn with Dependencies.swift and getting these errors:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/6259254/169562294-c9bc080e-8dff-45bc-afa5-c89db5ce4a5f.png">

If change to spm packages - all is fine.
Tried to add "OTHER_LDFLAGS": "$(inherited) -ObjC" to my project's target - didn't help
I've created a simple test project with GoogleSignIn and Dependencies.swift:
[tuistTest.zip](https://github.com/tuist/tuist/files/8741578/tuistTest.zip)

### Additional context

- Tuist version: 3.4.0
- Xcode version: 13.4.0

**Comment by jesus-mg-ios** [comment] 2022-05-20 15:52
@Banck I think that it's not importing Foundation, because the unknown types: NSString, typedef, NS_ASSUME_NONNULL_BEGIN

**Comment by natanrolnik** [comment] 2022-05-23 10:03
@Banck we had this same problem yesterday. The temporary solution was pinning the version of GoogleSignIn to 6.1.0 using `exact("6.1.0")` instead of `upToNextMajor(...)`.

@danyf90 I would love to take a look and try to fix this, if you could give some pointers that would be great.

**Comment by fortmarek** [comment] 2022-05-23 21:28
This is unrelated to the issue but I was intrigued by the following:

> People running tuist fetch from scratch couldn't build, while those who had done it previously had no issues.

I'd suggest committing the SPM lockfile which should result in deterministic SPM resolving.

**Comment by danyf90** [comment] 2022-05-24 07:58
> I'd suggest committing the SPM lockfile which should result in deterministic SPM resolving.

That's true in theory, but in practice SPM doesn't always follow it as it should, so in case like this it's better to be explicit in the Dependencies.swift

**Comment by danyf90** [comment] 2022-08-21 09:29
Closing as duplicate of https://github.com/tuist/tuist/issues/4688

**Closed by danyf90** 2022-08-21 09:29 UTC
Labels: domain:dependencies-swift
