### ISSUE TITLE
Tuist doesn't generate resource accessors for local swift package targets

### ISSUE THREAD

**Issue by shahzadmajeed** [tuist/tuist#4448] opened 2022-05-13 16:26 UTC
## Bug description

I am using a local swift package in Dependencies.swift. Local swift package have several modules and some of them have resources like XIBs, Assets, LocalizedStrings. I aspect Tuist to generate resource accessors when local swift package is integrated in generated project. But it seems like default resource synthesizers are skipping local swift packages for XIB, Assets and Strings and they only generate Bundle file but not Assets+Target.swift or Strings+Target.swift.

PS: I didn't try a remote swift package and that might be the case for remote packages as well but again I didn't test that case.

## Reproduction steps

Use [sample project](https://github.com/shahzadmajeed/TuistProjects/tree/master/Issues/1 ) that describes the issue and project structure. It also have description on how to reproduce which I have copied below as well.

1. Use the attached sample project (to be provided when opening the issue)
2. Run tuist fetch
3. Run tuist generate
4. Notice that project `Thor` which is a local swift package will not contain Assets+Styles.swift, Strings+Styles.swift files for target `Styles`
5. Same happens to other local package targets that contain some resources

### Additional context

- Apple Silicon M1 Machine
- macOS version: 12.3.1 (21E258)
- Tuist version: 3.3.0
- Xcode version: 13.3.1

**Comment by shahzadmajeed** [comment] 2022-05-13 17:28
I wonder if this fixes my issue https://github.com/tuist/tuist/pull/3295

**Comment by danyf90** [comment] 2022-05-13 18:02
Your package uses default SPM resources, right? If yes, it should be fixed in tuist 3.4.0 that should be released soon

**Comment by danyf90** [comment] 2022-05-16 12:34
Please reopen if not fixed in 3.4.0

**Comment by shahzadmajeed** [comment] 2022-05-16 17:41
@danyf90 could you please explain what do you meany by default SPM resources? We have folders `Resources` in every spa target and we are doing this for each one of them

```swift
.target(name: name,
                dependencies: dependencies,
                resources: [.process("Resources")])
```

**Comment by shahzadmajeed** [comment] 2022-05-16 19:09
I tried following following guidelines and switched to default paths but still generated project didn't have Strings+Styles.swift & Assets+Styles.swift (same for other modules).

https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package
https://developer.apple.com/documentation/swift_packages/localizing_package_resources

**Comment by danyf90** [comment] 2022-05-16 20:30
ok, I see, but I'm not sure I'm following 🤔 
Can you point exactly where you define the resources, what you would expect, and what you get instead?
Also, having a smaller sampler project would help 🙏

**Comment by shahzadmajeed** [comment] 2022-05-17 03:12
I apologize for a complex sample project. I just committed a much simple version.

**Q: Can you point exactly where you define the resources?**
**A:** I have a local swift package called SPMModules with a target `Feature1` that have some assets, string, font and xib. See screenshot of local swift package below

![local_swift_package](https://user-images.githubusercontent.com/1209459/168719913-8edcbf37-01e0-465c-bd66-496736d7fc84.png)

**Q: What do you expect?**
**A:** I expect to see `Assets+Feature1`, `Strings+Feature1` and `Bundle+Feature1` in generated Xcode project under `Projects/SPMModules/Derived/Sources/`

**Q: What do I get?**
**A:** Generated project's `Projects/SPMModules/Derived` folder only contains `Bundle+Feature1`. See screenshot below
<img width="467" alt="generated_project" src="https://user-images.githubusercontent.com/1209459/168720497-200d5a32-0f43-44ac-8d63-b3efcef970d1.png">

Note: As you can see in above screenshot, app target `Workbench` contains `Assets+Workbench` & `Strings+Workbench`.

Am I wrong to expect `Assets+Feature1`, `Strings+Feature1` and `Bundle+Feature1` to be generated for local swift package module `Feature1`? Is this not a supported feature in tuist?

**Comment by fortmarek** [comment] 2022-05-17 06:55
> Is this not a supported feature in tuist?

My suspicion is that we don't generate resource accessors for SPM dependencies - and I'm not 100 % sure we should. The issue is that we _can_ generate those accessors for a local package but then if you start using the package outside Tuist's context, you will lose access to those.

@shahzadmajeed what is the reasoning behind using a local Swift package instead of a framework?

**Comment by shahzadmajeed** [comment] 2022-05-17 14:33
Also, didn't we add automatic resource accessor generation to tuist 3.4.0 in this PR https://github.com/tuist/tuist/pull/4413/files? Or is it only for `Bundle+Feature1` and won't generate `Assets+Feature1` and `Strings+Feature1`?

**Comment by danyf90** [comment] 2022-05-17 16:08
> I think both. Because generated `Assets+Feature1` is going to be part of Xcode framework, it can be used by both the framework itself and the targets/frameworks depending on it.

But the framework itself should still be a valid SPM package, so you shouldn't be using them there. That's why (I think) we are not generating resource accessors for SPM packages (not sure why you point that they are local, but it should be independent from that).

**Comment by shahzadmajeed** [comment] 2022-05-17 16:40
> But the framework itself should still be a valid SPM package, so you shouldn't be using them there.

A tuist project should only care about framework being valid i.e it have everything it need to compile. Since all generated code is added to framework target membership, it should be all good.

> That's why (I think) we are not generating resource accessors for SPM packages (not sure why you point that they are local, but it should be independent from that).

It is a valid concern for a local swift package because it might be shared with other non-tuist projects in same repo. But I don't understand why is it a concern for remote packages. There is no way remote code can be affected by this? Obviously in case of remote package, only the generated framework will be using generated resource accessors and remote package can't take advantage of that but that is fine and should be understood.

**Comment by fortmarek** [comment] 2022-05-18 07:11
> we found swift package based modules to be much more flexible/scalable than frameworks. Here is what I love about them

Valid points, although I'd say most of it tuist already covers. I understand why SPM local packages are great in a regular Xcode project but in tuist, many shortcomings of a regular framework are gone.

As for whether to include resource accessors for local Swift packages, I still think it should be a responsibility of the package itself to provide those. If we decide to support this use-case, it should probably be opt-in or at the very least opt-out?

**Comment by shahzadmajeed** [comment] 2022-05-18 14:29
And when I said first class citizens I'm point out other things like unit tests targets for local swift package modules as I pointed out here in slack https://tuistapp.slack.com/archives/C018QG7U7SN/p1652824809705459

I keep mentioning local package based modules here because I don't think remote packages are meant to be your responsibility. They are suppose to be created and maintained externally without affecting your project

**Comment by danyf90** [comment] 2022-05-18 14:50
The separation from the Tuist point of view is a bit different:
- everything that is specified as part of the Tuist project is a "first-class citizen": you get resource accessors, test targets/schemes, and everything else
- everything that is imported as a dependency (doesn't matter if local or remote, for Tuist it's just an SPM dependency), is considered "external to the Tuist project", and treated as such.

Following this philosophy, if you want them to be treated as the other Tuist targets, then they must be Tuist targets and not SPM packages.

For example, from your message I think you are still not using tuist caching, but when you'll start to use it, when running `tuist generate` the SPM dependencies will be imported as binary, which is probably something you don't want for your local modules.

**Comment by shahzadmajeed** [comment] 2022-05-18 15:46
> The separation from the Tuist point of view is a bit different:

Thank you for explaining this. I think dependencies can be categorized as internal vs. external to be a bit more flexible. Tuist already treats local swift package as an Xcode project when you run `tuist generate` which I like a lot because I can edit my local swift package based modules just like normal frameworks. I think the only thing it need to do is treat it as a tuist project and include everything from projects directory

> For example, from your message I think you are still not using tuist caching...
I am using caching. See this screenshot of project with local swift package generated with `tuist generate` where dependencies were cached:
<img width="470" alt="project" src="https://user-images.githubusercontent.com/1209459/169085498-1d80de3c-3628-4a19-8ce5-df084c21961c.png">

If I use `tuist generate --xcframeworks` then all binaries will be linked but that is true for tuist target as well which is good/fine.

**Comment by danyf90** [comment] 2022-05-18 16:02
> I am using caching. See this screenshot of project with local swift package generated with `tuist generate` where dependencies were cached:

You are seeing sources just because you have run `tuist cache warm --xcframework`, if you would have run also `tuist cache warm`, then a simple `tuist generate` would cache those out, and I don't think it's what you want.

For the behavior you are looking for, you need to define those modules as Tuist targets.


Regarding the concerns you have raised before:

> Easy file management -> You don't need to worry about file references. You just drop the folder or files and drag anywhere and SPM pick up files

I'm not sure I got your point here, defining the modules through tuist should be pretty straightforward

> Modularization -> Local swift packages reduce friction for working on modules just because you can open a Package.swift file and easily build any module using default schemes

With Tuist you would have a scheme for each target/module, so I guess it would be pretty much the same. If you want, you can also do `tuist generate Module` to have a focused project on that module

> Dependency management -> It is easy to setup and inspect module dependency on each other in a single Package.swift file

Not sure why it would be easy than the dependencies defined in Project.swift

> Code sharing (internally/externally) is very easy

If you need to share internally (meaning internally to the project), you can do the same with a tuist target.
If you need to share externally then yes, you would need to define a Package.swift, but at that point I would say that the module isn't part of the local tuist project and it's correct to treat it as a dependency

> I can keep going but I will stop here to comment on

If you have other points please bring them up 🙏

**Comment by shahzadmajeed** [comment] 2022-05-18 19:07
@danyf90  thank you for your detailed reply. 

You are right, we don't want to use binaries when running a simple `tuist generate` because my expectation is to use everything in editable mode where local packages can be developed in tandem with other frameworks/apps.

Regarding your comments on local swift package module benefits: We have lots of local swift package based modules in existing project and we would like to use them in new set of apps/Tuist based project as is. 

I understand that creating Tuist targets based on local spm modules is not tough, all you have to do is just provide paths to Sources, Resources and Tests. But, it also means that moving away from Tuist will be difficult because we would like to use spm modules instead of Xcode frameworks in that case. All that makes me think that it was better to use spm modules as is in a Tuist project.

But again, thank you for responding to my questions :)

**Comment by shahzadmajeed** [comment] 2022-05-19 03:14
So, because this is not a bug but just a limitation of tuist, should I close this thread and start a discussion for improvements?

**Comment by danyf90** [comment] 2022-05-19 07:29
Yes, let's close the issue and open a discussion 🚀

**Comment by danyf90** [comment] 2022-05-20 07:55
BTW that's strange, I had a look at the code and everything should be generated ([reference](https://github.com/tuist/tuist/blob/b5be7ac3736109439b8b5b60cf32a81767a93cf4/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L374-L387)).

We also have an issue caused by that generation: https://github.com/tuist/tuist/issues/4467

**Comment by shahzadmajeed** [comment] 2022-05-23 11:48
I see, good catch 👏. It would be great if we can enable all 3 options for dependencies or let developers customize that behavior

**Comment by shahzadmajeed** [comment] 2022-05-23 11:51
I looked at the other issue you mentioned. Renaming will solve conflict with Packages internal generated code. 

Seems like we are gonna do a separate PR for this?

**Comment by shahzadmajeed** [comment] 2022-05-23 12:37
Oh I didn't notice that false here means enable those accessors. We are not passing any synthesizer for package i.e 
'resourceSynthesizers: []'

Could this be the issue?

**Comment by danyf90** [comment] 2022-05-23 12:41
> Oh I didn't notice that false here means enable those accessors. We are not passing any synthesizer for package i.e 'resourceSynthesizers: []'
> 
> Could this be the issue?

Oh, of course :D
Passing `.default` there should fix the problem 🤔 

The problem is that then the generated code might conflict with resource accessors defined in the package itself (if any). We should probably make the `options` parameter defined there configurable in the Dependencies.swift file.

If you want to try to take care of it, feel free to write me on slack and I can provide some pointers 🚀

**Comment by shahzadmajeed** [comment] 2022-05-23 12:52
I agree about including a parameter. 

Sounds good. I will ping you on slack 👍

**Closed** 2022-05-29 10:40 UTC
Labels: type:bug, domain:dependencies-swift

**Comment by justin-er** [comment] 2023-05-01 17:04
> Valid points, although I'd say most of it tuist already covers. I understand why SPM local packages are great in a regular Xcode project but in tuist, many shortcomings of a regular framework are gone.

Not when the number of frameworks in a project goes high.
