### ISSUE TITLE
Extremely poor performance generating focused targets with cache

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6587] opened 2024-07-31 21:31 UTC
### What happened?

I have a large project consisting of hundreds of targets. When I run `tuist generate Framework1` it completes in an acceptable amount of time, but if I run `tuist cache` and then `tuist generate Framework1` it takes a really long time (I've never actually seen it finish).

I attempted to debug this issue myself but I understand the caching code is closed source and was [advised to submit a repro sample](https://tuist-community.slack.com/archives/C018QG7U7SN/p1721766864555789?thread_ts=1721763450.608289&cid=C018QG7U7SN).

### How do we reproduce it?

1. Download and extract the attached project ([repro2.zip](https://github.com/user-attachments/files/16447352/repro2.zip))
2. `tuist cache`
3. `tuist generate Framework1 --no-binary-cache` (should complete very quickly)
4. `tuist generate Framework1` (takes forever)

You can adjust the number of frameworks in the project with `tuist edit` and changing the `numFrameworks` constant. I tested with 10 and 20, both finished generating very quickly on my machine. At 30 it never finishes generating.

### Error log

`tuist generate Framework1` never finishes running

### macOS version

14.5

### Tuist version

4.22.0

### Xcode version

15.4

**Comment by fortmarek** [comment] 2024-08-01 13:13
Hey @hiltonc 👋 

I followed your steps but I am unable to reproduce 🤔 The generation time for `tuist generate Framework1` is 0.7s.

Can you also try `tuist cache --print-hashes`? That command _is_ opensource, so that might help to debug if it freezes.

**Comment by hiltonc** [comment] 2024-08-01 17:47
@fortmarek unfortunately no freeze on `--print-hashes`, completed in 0.686s.

It may be a difference in machines. I'm using a MacBook M1 Max w/ 32 GB.

Maybe if you increase `numFrameworks` to something like 50 or 100 it will repro?

**Comment by hiltonc** [comment] 2024-08-01 17:49
Looking in Activity Monitor, memory and disk usage are minimal. CPU is pegged at 99.4%.

**Comment by hiltonc** [comment] 2024-08-01 18:01
I finally waited long enough for it to complete:

```
tuist generate Framework1
Loading and constructing the graph
It might take a while if the cache is empty
Using cache binaries for the following targets: Framework8, Framework26, Framework10, Framework19, Framework12, Framework11, Framework17, Framework2, Framework24, Framework18, Framework25, Framework16, Framework7, Framework5, Framework13, Framework28, Framework3, Framework22, Framework20, Framework4, Framework9, Framework23, Framework6, Framework15, Framework21, Framework14, Framework30, Framework29, Framework27
Generating workspace Workspace.xcworkspace
Generating project Framework1
Project generated.
Total time taken: 818.056s
```

**Comment by fortmarek** [comment] 2024-08-01 19:58
I forgot to run `tuist cache`, my bad. You are right, thanks a lot for the repro this helped a ton.

Turns out returning early from the StaticProductsGraphLinter fixes the perf issue: https://github.com/tuist/tuist/commit/7c95819ddfa79059ae31bf5b59fe2adaba4d281d

Thanks to @ffittschen for discovering that.

Turns out, we've been doing DFS but we could visit multiple nodes twice. In this repro case, it seems the number of visits becomes exponential. 

Taking [pseudocode](https://www.programiz.com/dsa/graph-dfs) from here, the DFS should be done as follows:
> DFS(G, u)
    u.visited = true
    for each v ∈ G.Adj[u]
        if v.visited == false
            DFS(G,v)
...

In our case, we're doing the recursion [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L78) and saving the result for a dependency [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L101). We do return early [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L72-L74) if there is a saved result _but_, depending on your graph, the result might not be there even when we visited that node.

We should mark the node as visited immediately, so it's never visited twice. This [PR](https://github.com/tuist/tuist/pull/6592) does fix the perf issues and it seems all the `StaticProductsGraphLinterTests` pass. I'll double check it tomorrow and prepare it for review. This shall be fixed in the next release, thanks again for the report 😌

**Comment by hiltonc** [comment] 2024-08-01 20:50
That's great news, thank you for the quick investigation and fix!

**Closed** 2024-08-05 07:28 UTC
Labels: type:bug
