### ISSUE TITLE
When using `DefaultSettings.essential` mergeable libraries build settings not set

### ISSUE THREAD

**Issue by dmytro-anokhin** [tuist/tuist#6348] opened 2024-05-29 10:45 UTC
### What happened?

When generating a target with `DefaultSettings.essential` settings, build settings `MERGED_BINARY_TYPE` and `MERGEABLE_LIBRARY` not set.

```
let settings: Settings = .settings(
    base: [
        "PROJECT_BASE": "PROJECT_BASE",
    ],
    configurations: [
    ],
    defaultSettings: .essential
)

let project = Project(
    // ...
    targets: [
        .target(
            name: "App",
            destinations: .iOS,
            product: .app,
            // ...
            dependencies: [
                .target(name: "Framework"),
            ],
            settings: settings,
            mergedBinaryType: .automatic
        ),
        .target(
            name: "Framework",
            destinations: .iOS,
            product: .framework,
            // ...
            settings: settings,
            mergeable: true
        ),
    ]
    // ...
)
```

### How do we reproduce it?

See the sample project: https://github.com/dmytro-anokhin/tuist-default-settings-essental

1. `tuist generate`;
2. Explore **App** and **Framework** build settings.

Result:

1. `MERGED_BINARY_TYPE` on **App** target is not set;
2. `MERGEABLE_LIBRARY` on **Framework** target is not set.

Expected:

1. `MERGED_BINARY_TYPE = automatic`;
2. `MERGEABLE_LIBRARY = YES`.

### Error log

None

### macOS version

14.5

### Tuist version

4.15.0

### Xcode version

15.3

**Comment by woin2ee** [comment] 2024-06-24 12:39
I checked into this issue, I could see that settings filtered by predefined essential keys.
https://github.com/tuist/tuist/blob/acad9c493dba0fe7b29a19368333af519fb12efa/Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift#L218-L225
And, a summary of the `essential` settings is
> A minimal set of settings to make the project compile without any additional settings

I need advice on the correct behavior. IMHO, the current is right. When use the `recommended` settings, it solved.

**Comment by pepicrft** [comment] 2024-06-25 17:03
@woin2ee what are in your opinion the required changes to mitigate the issue?

**Comment by woin2ee** [comment] 2024-06-25 17:14
In my position that the current behavior is correct, I think the reason this issue came up is because there was no appropriate feedback.
What do you think about adding a log for this case? @pepicrft @dmytro-anokhin

**Comment by pepicrft** [comment] 2024-06-25 17:19
Gotcha! Thanks @woin2ee 🙏🏼. By log, do you mean documentation?

**Comment by kwridan** [comment] 2024-06-25 17:59
This is an interesting one - `DefaultSettings` originally was intended for settings you get out of box that aren't necessarily tied to a feature / manifest property (e.g. optimisation level, enabled warnings etc...) 

For the settings that are influenced by manifest related properties they are informally called "derived settings" https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L172 and those typically get applied regardless of the `DefaultSettings` level.

Given `mergedBinaryType` is a manifest property, I'd imagine the expectation is it would update the appropriate setting in response, this is similar to other items such as `productName`.

**Comment by woin2ee** [comment] 2024-06-26 00:47
Oh, I seem to have misunderstood about `DefaultSettings`. Thankfully, your explanation makes a lot of sense.

So, in this case, then `mergedBinaryType` and `mergeable` should be applied as manifest properties. and I think it can resolved by update https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L172 method.

**Closed** 2024-07-01 22:45 UTC
Labels: type:bug, good first issue
