### ISSUE TITLE
Support for Swift 6 Testing

### ISSUE THREAD

**Issue by bluprince13** [tuist/tuist#6828] opened 2024-10-07 21:46 UTC
### What problem or need do you have?

`tuist test` doesn't detect tests written using [Swift Testing](https://developer.apple.com/documentation/testing).

Example:
1. `git clone https://github.com/bluprince13/SwiftTuistTestSample`
2. `cd SwiftTuistTestSample`
3. `tuist test`

The test looks like:

```
import Foundation
import Testing

@Test func testSample() {
    #expect(2 + 2 == 4)
}
```

### macOS version

15.0

### Tuist version

4.27.0

### Xcode version

16

**Comment by fortmarek** [comment] 2024-10-08 10:48
Hey 👋 

The tests are actually run – you can confirm this by making the assertion fail.

The issue is `tuist test` pipes the output through `xcbeautify` and `xcbeautify` currently incorrectly swallows all Swift Testing output.

I'm gonna keep this issue opened but the issue needs to be first fixed in `xcbeautify`, see: https://github.com/cpisciotta/xcbeautify/issues/313

After a new `xcbeautify` is released, the only thing we'll need to in `tuist` is to update it to the latest version.

**Comment by bluprince13** [comment] 2024-10-08 20:03
> The tests are actually run – you can confirm this by making the assertion fail.

You are right. Thanks for responding!

**Closed** 2024-10-18 10:40 UTC
Labels: type:bug, p2
