### ISSUE TITLE
Resources bundle not generated for SPM dependency

### ISSUE THREAD

**Issue by ffittschen** [tuist/tuist#4505] opened 2022-05-29 16:11 UTC
## Describe the bug and the expected behavior

When integrating the [AppCenter SDK](https://github.com/microsoft/appcenter-sdk-apple) as a SPM dependency via the Dependencies.swift file, the generated product targets in the `AppCenter` project are missing the resources / resource bundles.

The AppCenter Package.swift file neither explicitly declares sources nor resources, so I'd assume that Tuist would find them via the `**/*.lproj` glob from the [`defaultResourcePaths`](https://github.com/tuist/tuist/blob/37af41b69a30187c380b32c4eeb70a1ce36953b4/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L633), but this doesn't seem to be the case.

As a result, there are missing strings (see second screenshot).

At first I thought this is related to #3785, as `SWIFTPM_MODULE_BUNDLE` is used [within the AppCenter code](https://github.com/microsoft/appcenter-sdk-apple/blob/d92e2b39bc88300d1fe2405dc16bc077847d0e51/AppCenterDistribute/AppCenterDistribute/MSACDistributeUtil.m#L21), but Tuist isn't even generating the resources bundle that SwiftPM would generate, which is why I don't think the bundle accessor is the problem.

## Reproduction steps
Sample project: [app_with_spm_dependencies.zip](https://github.com/tuist/tuist/files/8793727/app_with_spm_dependencies.zip)

Steps to reproduce the bug:

1. Use the attached sample project
2. Run `tuist fetch && tuist generate`
3. Open the `AppCenter` project in `Tuist > Dependencies > SwiftPackageManager > .build > checkouts`
4. See that no resource bundle targets are generated.

### Screenshots

<img width="450" alt="Screen Shot 2022-05-29 at 17 26 10@2x" src="https://user-images.githubusercontent.com/7734806/170877405-2ff8061f-c8e9-48aa-83bd-fa725f9e63af.png">

<img width="450" alt="AppCenterDistributeResources_missing" src="https://user-images.githubusercontent.com/7734806/170877624-0cc8093a-09e1-4e37-b261-b9e31789f8fb.png">

### Additional context

- macOS version: 12.3.1
- Tuist version: 3.4.0, but also https://github.com/tuist/tuist/commit/37af41b69a30187c380b32c4eeb70a1ce36953b4 (latest `main` at the time of issue creation)
- Xcode version: 13.3.1

**Comment by danyf90** [comment] 2022-05-29 17:44
IT seems there is an issue with automatic lproj resources. Duplicate of https://github.com/tuist/tuist/issues/4435

**Closed by danyf90** 2022-05-29 17:44 UTC

**Comment by ffittschen** [comment] 2022-05-30 06:31
After following the suggestion in https://github.com/tuist/tuist/issues/4435#issuecomment-1137393368, I forked AppCenter and added an explicit `[.process("Resources"]` to the `AppCenterDistribute` target in the Package.swift file. This results in the AppCenterDistributeResources target being generated. Looks like we can use this as a workaround until Tuist correctly generates the resources target.

<img width="450" alt="Screen Shot 2022-05-29 at 19 45 34@2x" src="https://user-images.githubusercontent.com/7734806/170930634-9902ffa6-9534-4e4a-a1e4-0bacb3967b58.png">

**Comment by ffittschen** [comment] 2022-05-30 07:25
I just had a look into it with the following findings:
- The `TuistCore.DependenciesGraph` returned from the `fetch` method in the `DependenciesController.swift` still contains the globs in the resources array of the target
- After calling `converter.convert(manifest: dependenciesManifest, path: path)` in the `fetchDependencies` of the `FetchService.swift`, the resources array doesn't contain any elements anymore.
- After adding a few breakpoints, I discovered that `*.lproj` is not considered being a resource in [this method](https://github.com/tuist/tuist/blob/8dd9ae027f4c56ed6820762605d41d916e31e3d8/Sources/TuistCore/Graph/ModelExtensions/Target%2BCore.swift#L41), as it is not a file, and its extension is not part of the `Target.validFolderExtensions`.

![Screen Shot 2022-05-30 at 09 21 34@2x](https://user-images.githubusercontent.com/7734806/170939486-0ed085f8-8800-44e7-8a13-b0f97df16206.png)
