### ISSUE TITLE
tuist generate fails when using cached binaries built with different macos version

### ISSUE THREAD

**Issue by hbanzon** [tuist/tuist#6403] opened 2024-06-13 13:44 UTC
### What happened?

* Using Tuist Cloud with cached binaries built using macos 14.5 on CI
* Developer is authenticated with Tuist Cloud from their local machine, running on macos 14.4
* Developer runs `tuist generate`

**Expected Results**
Workspace / Project is built properly.  

**Actual Results**
Developer received following error on their machine
```
The 'swift' command exited with error code 1 and message
/Users/jdeveloper/development/MyApp/Support/APIv3Performance/Project.swift:2:8: error: cannot load module 'ProjectDe ScriptionHelpers' built with SDK 'macosx14.4' when using SDK 'macosx14.5': /Users/jdeveloper/.cache/tuist/ProjectDescr iptionHelpers/2557aec/3362a37febde4d7fd02ae10a94f68c4c/ProjectDescriptionHelpers.swiftmodule
import ProjectDescriptionHelpers
```

### How do we reproduce it?

1. Tuist Cloud with Tuist cache warming set up in CI running on macos 14.5 and Xcode 15.4
2. Local Developer Environment set up with macos 14.4 and Xcode 15.4
3. tuist clean, then tuist generate

### Error log

```
The 'swift' command exited with error code 1 and message
/Users/jdeveloper/development/MyApp/Support/APIv3Performance/Project.swift:2:8: error: cannot load module 'ProjectDe ScriptionHelpers' built with SDK 'macosx14.4' when using SDK 'macosx14.5': /Users/jdeveloper/.cache/tuist/ProjectDescr iptionHelpers/2557aec/3362a37febde4d7fd02ae10a94f68c4c/ProjectDescriptionHelpers.swiftmodule
import ProjectDescriptionHelpersCurrent
```

### macOS version

14.4 (Local) and 14.5 (CI)

### Tuist version

4.17.0

### Xcode version

15.4

**Comment by fortmarek** [comment] 2024-06-17 08:58
Hey @hbanzon 👋 

The error seems to be coming from parsing the `Project.swift` file and should have no relation to the binary cache. Is it possible you are caching the `~/.cache/tuist` directory on the PR? If so, then most likely this is a duplicate of: https://github.com/tuist/tuist/issues/6374

**Comment by TheSPST** [comment] 2024-06-20 09:47
any update people are still facing this

**Comment by fortmarek** [comment] 2024-06-21 08:05
I put up a [PR](https://github.com/tuist/tuist/pull/6429) to fix this issue 🙏

**Closed** 2024-06-21 09:00 UTC
Labels: type:bug
