### ISSUE TITLE
Cross manifest application target is being filtered out from target dependencies

### ISSUE THREAD

**Issue by thebarndog** [tuist/tuist#6130] opened 2024-03-28 03:06 UTC
### What happened?

I'm building an independent watchOS app with a companion iOS app and to allow those two applications to talk to each other through the `WatchConnectivity` framework, there's a weird quirk that the watchOS app target has to be embedded into the iOS app target, without signing or else the session connection won't be established correctly. I have my folder and manifest structure set up like

```
- Apps
  - iOS
    - Project.swift
  - Watch
    - Project.swift
```

In the iOS app, I want to reference the other watch os target in my dependences using `.project(target: "WatchOSApp", path: .relativeToRoot("Apps/Watch")` but on project generation, the watch app isn't embedded as I would expect.

I was able to workaround this however by moving both my targets into the same manifest files so now my dependency is using `.target` rather than `.project`. It seems like the watch application target is being filtered out for some reason when it's coming from another project.

### How do we reproduce it?

[TestApp.zip](https://github.com/tuist/tuist/files/14783403/TestApp.zip)

The test app is split into two project manifests and the iOS target references the watch target as a dependency via `.project`. However it's not embedded in the generated project and subsequent checks with the watch session object will fail to connect: 

<img width="662" alt="Screenshot 2024-03-27 at 11 01 04 PM" src="https://github.com/tuist/tuist/assets/3139429/0561c14a-f321-41b4-aa80-1e96bd27340f">

If those targets are consolidated down to a single manifest, it works. 

[WorkingExample.zip](https://github.com/tuist/tuist/files/14783445/WorkingExample.zip)

<img width="678" alt="Screenshot 2024-03-27 at 11 05 47 PM" src="https://github.com/tuist/tuist/assets/3139429/3749d1bf-e4a3-4d1e-8ffe-d05c50966926">

So it seems like it's just something about using `.project` over `.target` and the fact that it's defined in a different manifest

### Error log

N/A

### macOS version

14.1.2

### Tuist version

4.8.1

### Xcode version

15.3

**Comment by kwridan** [comment] 2024-03-28 05:54
Thanks for raising this @thebarndog 

I believe this is somewhat by design, currently only direct target dependencies within the same project of an Application can be embed as additional applications or extensions.

This was modelled after how the projects were set up in Xcode when adding those products. 

Did you previously have a setup where they were in separate projects?

**Comment by kwridan** [comment] 2024-03-28 11:05
Thanks @shahzadmajeed 

>  We have extension targets which do almost nothing but defer their implementation to Braze sdk so it doesn't make sense to repeat them for every app. 

Doesn't there need to be a unique extension target per app? For example, there are rules around the bundle IDs for each, my understanding is they can't be shared between multiple apps.

They can all have common dependencies or helpers in `ProjectDescriptionHelpers` to reduce repetition if needed.

**Comment by shahzadmajeed** [comment] 2024-03-28 12:07
You can control bundle id via. User defined build settings

**Comment by kwridan** [comment] 2024-04-02 12:22
Thanks for the replies

> You can control bundle id via. User defined build settings

Was this working as a separate project before adopting Tuist? (i.e. had the extension in separate projects)

> I figured that was the case but maybe there needs to be special handling for adding a watchOS target to an iOS application since that's a legitimate use case for watch app development.

Same question, did this work before adopting tuist? (having the watch app target in a different project).

Note: to my knowledge there are still distinct development paths for watch apps, one is standalone and another is bundled within an iOS app, it's only the latter that we're currently discussing if I followed along.

**Comment by pepicrft** [comment] 2024-05-14 17:20
@thebarndog if this is a valid Xcode setup, then I recommend the following steps:
- Add a fixture to the [fixtures directory](https://github.com/tuist/tuist/tree/main/fixtures) with this particular scenario
- Add an [acceptance tests](https://github.com/tuist/tuist/blob/main/Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift#L10) and make it fail
- Make it work by revising the [logic that generates the linking build phase](https://github.com/tuist/tuist/blob/4ecde1dbb3fea6d5664eb870deb919ce0b8e4bd5/Sources/TuistGenerator/Generator/LinkGenerator.swift#L382)
- Let us know and we'll be happy to review the PR

**Comment by TamarMilchtaich** [comment] 2024-09-02 07:22
We came across another use case where this issue is present - using a test host target located in a different project. The configuration looked like this:
```
.project(target: "TestHost", path: "../TestHost"),
```

In this scenario, the problem isn’t related to linking, but rather involves adding this target as a Target Dependency (ensuring the target is added as a dependency and configuring the relevant build settings should be sufficient to set it as a test host).

Could you please provide any pointers on where we might locate the relevant code to address this?

**Comment by TamarMilchtaich** [comment] 2024-10-31 21:13
This issue should be solved by: https://github.com/tuist/tuist/pull/6820

**Comment by fortmarek** [comment] 2024-11-01 07:52
Closing, we can reopen if needed 🤞

**Closed by fortmarek** 2024-11-01 07:52 UTC
Labels: type:bug, good first issue, p3, size:M
