### ISSUE TITLE
Tuist cannot resolve AsyncAlgorithms dependecy

### ISSUE THREAD

**Issue by dankinsoid** [tuist/tuist#4422] opened 2022-05-05 10:01 UTC
## Tuist cannot resolve AsyncAlgorithms dependecy
Error:
Couldn't find target '_CAsyncSequenceValidationSupport' at '/Users/danil/TuistApp/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/swift-async-algorithms'

## Reproduction steps

Steps to reproduce the bug:

1. Generate empty tuist project
2. Create Dependency.swift file:
```swift 
public let dependensies = Dependencies(
	swiftPackageManager: [
		.package(url: "https://github.com/apple/swift-async-algorithms.git", from: "0.0.1"),
	]
)
```
3. Add external dependency to framework targets:
```swift
.external(name: "AsyncAlgorithms")
``` 
4. tuist fetch
5. tuist generate
6. Error

### Error log

``` 
Couldn't find target '_CAsyncSequenceValidationSupport' at '/Users/danil/TuistApp/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/swift-async-algorithms'
```

### Additional context

- macOS version: 12.0.1
- Tuist version: 3.3.0
- Xcode version: 13.3.1

P.S. It would be great to have AppCode integration, at least tuist edit

**Comment by dankinsoid** [comment] 2022-05-05 10:05
I also want to note that tuist print incorrect errors, I got 
```
`SomeDependency` is not a valid configured external dependency
```
where SomeDependency is any dependency, but not AsyncAlgorithms, I had to generate empty project and check every dependency

**Comment by denizdogan** [comment] 2022-05-08 09:51
FWIW, I guess it comes from this switch: https://github.com/tuist/tuist/blob/65c73825750b0062cab80bda0ce0ece162bb41c5/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L234

The _CAsyncSequenceValidationSupport target has been defined as `.systemLibrary` which is not handled for some reason.

**Comment by fortmarek** [comment] 2022-05-10 06:48
This is probably going to be the same issue as [here](https://github.com/tuist/tuist/issues/3477). We should look into handling the `.systemLibrary` which is, indeed, not handled right now. If you wanted to try to fix it, let us know 🙌

**Comment by danyf90** [comment] 2022-05-23 11:39
Closed as duplicate of https://github.com/tuist/tuist/issues/3477 🙏

**Closed by danyf90** 2022-05-23 11:39 UTC
