### ISSUE TITLE
[Dependencies.swift] Issues depending on AppCenter SDK

### ISSUE THREAD

**Issue by luispadron** [tuist/tuist#4024] opened 2022-01-20 23:00 UTC
**Describe the bug**

When importing `AppCenterDistribute` from the `AppCenter` [package](https://github.com/microsoft/appcenter-sdk-apple) there are a number of errors:

1. It looks like we're parsing the option [here](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/Package.swift#L34) incorrectly as `APP_CENTER_C_VERSION="4.4.1"` in the Xcode project build settings which leads to a compiler error. This can be resolved by instead changing the setting to be `APP_CENTER_C_VERSION="\"4.4.1\""`. I'm guessing the first quotes get stripped during Xcode build phase and as such the variable is read as a float and not the expected string, by wrapping it another set of quotes we get the correct string type.
2. Once the above is resolved we see some duplicate header errors (these don't show up using the legacy package mechanism in Tuist) 
   
```
/Users/luis.padron/development/AppCenterBugExample/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/appcenter-sdk-apple/AppCenter/AppCenter/include/MSACDevice.h:16:1: Duplicate interface definition for class 'MSACDevice'
```

**To Reproduce**

1. Download zip
2. Run `tuist dependencies fetch`
3. Run `tuist focus`
4. See error 1
5. Fix error 1
6. See error 2

[AppCenterBugExample.zip](https://github.com/tuist/tuist/files/7909003/AppCenterBugExample.zip)

**Comment by apps4everyone** [comment] 2022-02-25 16:54
Any news here? 

Attached a demo project with OHHTTPStubs and AppCenter. (the last two external dependencies we have problems with)
[TuistDemo.zip](https://github.com/tuist/tuist/files/8142897/TuistDemo.zip)

Help / Fix would be very mich appreciated. @danyf90 maybe you could take a look into this as Dependency expert thx?

**Comment by danyf90** [comment] 2022-02-25 17:05
Are you still getting the same error as the initial message? I think point `1` has been solved, isn't it?

**Comment by apps4everyone** [comment] 2022-02-25 17:35
<img width="648" alt="Screenshot 2022-02-25 at 14 33 46" src="https://user-images.githubusercontent.com/1915802/155760873-7236b07c-b260-4f35-9a78-bc3d2dfbea69.png">
getting multiple error, also tried to also `import AppCenter` but there is no product with this name in Package.swift.

**Comment by apps4everyone** [comment] 2022-02-25 17:38
also tries with master from https://github.com/microsoft/appcenter-sdk-apple/commit/09e5806231aba77ce6533a0a4ac7c02a6a5968a2 with other header paths but maybe I did something wrong. Not sure if this is a Tuist or AppCenter problem. But the "normal" SPM integration works, therefore I think this is a Dependency.swift bug.

https://github.com/microsoft/appcenter-sdk-apple/commit/09e5806231aba77ce6533a0a4ac7c02a6a5968a2

**Comment by apps4everyone** [comment] 2022-03-07 13:18
any news here? @danyf90 @luispadron did the example help? https://github.com/tuist/tuist/files/8142897/TuistDemo.zip
thx

**Comment by apps4everyone** [comment] 2022-04-06 13:21
sadly no update here, unfortunately way to complex to solve with a PR for none core tuist contributors like me. Did someone even look into the requested example?

**Comment by apps4everyone** [comment] 2022-04-06 13:28
could it be missing `cSettings` in tuist? https://developer.apple.com/documentation/swift_packages/target/3112788-csettings

**Comment by apps4everyone** [comment] 2022-04-06 13:30
or not escaped `"` like in GCC_PREPROCESSOR_DEFINITIONS? https://github.com/tuist/tuist/pull/3995/files

**Comment by danyf90** [comment] 2022-04-06 13:49
I would suggest you start from the generated projects, and the simpler error to understand what's going on.
For example, from the screenshot I would check whether `PLClashReportTextFormat` compiles on its own. If it doesn't, we have narrowed down the problem to that dependency. If it does I would try `CrashReporter` which depends on it and so on.
Then, still from Xcode, you can try to see if you see something wrong in the project settings and see if you can manage to make it compile changing them manually in Xcode.

All of this requires no deep knowledge of Tuist and, if investigated on your side, would make solving the issue in Tuist much simpler and quicker 🙏

**Comment by apps4everyone** [comment] 2022-04-06 14:15
it does compile as normal SPM in Xcode. so this is unfortunately a tuist bug. I have tried multiple times to improve or fix things in tuist but looks like tuist is way to complex for me without any hints from the core team. That's why I added the example as requested. I am asking for directions from more experienced team members before I try again. But it looks like no one even opened the example. Sadly I get the impression asking for an example project is the standard phrase for every bug report but no one cares afterwords. 

PS: sorry for my frustrated words, but this (no feedback) unfortunately happened to multiple of my issues/questions and PR's. I would not ask here if this would not be a blocker for me and others (Slack) for my transition to Dependencies.swift

**Comment by apps4everyone** [comment] 2022-04-06 14:18
I see for `.c`: headerSearchPaths.append("$(SRCROOT)/\(mainRelativePath.pathString)/\(setting.value[0])")
this might not wirk with:
`**` anf `/../` in
https://github.com/microsoft/appcenter-sdk-apple/blob/develop/Package%40swift-5.3.swift#L8-L51

**Comment by danyf90** [comment] 2022-04-12 07:49
What I asked was to open the generated Xcode project, and try to play a bit with it changing settings or similar, to see if you can get more insights on the issue, or reduce the issue to a smaller project, so that when someone has some time to dedicate to it, it's simpler and quicker for them.

It's not the first time you came up with frustrated words, so I would suggest you to try to be more collaborative, as I can assure you that attitude won't help you get any more help.

**Comment by mikeger** [comment] 2022-07-25 15:50
@apps4everyone following custom config make tuist build AppCenter for me:
```swift
                 "AppCenterAnalytics": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                 ],
                 "AppCenterDistribute": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                 ],
                 "AppCenterCrashes": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                    "HEADER_SEARCH_PATHS": "$(inherited) $(SRCROOT)/Vendor/PLCrashReporter/include $(SRCROOT)/AppCenterCrashes/**"
                 ]
```

**Comment by mikeger** [comment] 2022-07-26 08:15
@apps4everyone this config makes AppCenter compile for me (in `Dependencies.swift`):
```swift
        targetSettings: [
                 "CrashReporter": [
                     "ALWAYS_SEARCH_USER_PATHS": "NO",
                     "USE_HEADERMAP": "YES",
                 ],
                 "AppCenterAnalytics": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                 ],
                 "AppCenterDistribute": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                 ],
                 "AppCenterCrashes": [
                    "ALWAYS_SEARCH_USER_PATHS": "NO",
                    "USE_HEADERMAP": "YES",
                    "HEADER_SEARCH_PATHS": "$(SRCROOT)/Vendor/** $(SRCROOT)/AppCenter/AppCenter/Internals $(SRCROOT)/AppCenter/AppCenter/Internals/Model $(SRCROOT)/AppCenter/AppCenter/Internals/Model/Util $(SRCROOT)/AppCenter/AppCenter/Internals/Util $(SRCROOT)/AppCenter/AppCenter/Internals/Channel $(SRCROOT)/AppCenter/AppCenter/Internals/Model/CommonSchema $(SRCROOT)/AppCenter/AppCenter/Internals/Context/Device $(SRCROOT)/AppCenter/AppCenter/Internals/Context/Session $(SRCROOT)/AppCenter/AppCenter/Internals/Context/UserId $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Model $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/include $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals/Util $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals/Model"
                 ]
             ]
```

**Comment by apps4everyone** [comment] 2022-07-26 08:21
Hey, @mikeger. Thx for sharing. Interesting fix. Maybe this help's to find the place with the missing underlying path's and header map flag in tuist. We currently stoped transition to Dependencies.swift because of other problems, but we maybe retry next weeks. For AppCenter we currently use the XCFramework release as SPM binary from Microsoft to also reduce compile time.

**Comment by danyf90** [comment] 2022-07-26 08:40
Thanks @mikeger !

May I ask what the `HEADER_SEARCH_PATHS` would be for `AppCenterCrashes` if you don't specify them in Dependencies.swift?

**Comment by mikeger** [comment] 2022-07-26 09:34
@danyf90 I think `$(SRCROOT)/Vendor/**` is missing, I could try substituting it with `**` as specified in the `Package.swift` of AppCenter

**Comment by danyf90** [comment] 2022-08-21 09:28
Closing as duplicate of https://github.com/tuist/tuist/issues/4688

**Comment by shahzadmajeed** [comment] 2022-12-13 20:14
> ```swift
>                     "HEADER_SEARCH_PATHS": "$(SRCROOT)/Vendor/** $(SRCROOT)/AppCenter/AppCenter/Internals $(SRCROOT)/AppCenter/AppCenter/Internals/Model $(SRCROOT)/AppCenter/AppCenter/Internals/Model/Util $(SRCROOT)/AppCenter/AppCenter/Internals/Util $(SRCROOT)/AppCenter/AppCenter/Internals/Channel $(SRCROOT)/AppCenter/AppCenter/Internals/Model/CommonSchema $(SRCROOT)/AppCenter/AppCenter/Internals/Context/Device $(SRCROOT)/AppCenter/AppCenter/Internals/Context/Session $(SRCROOT)/AppCenter/AppCenter/Internals/Context/UserId $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Model $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/include $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals/Util $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/Internals/Model",
> ```

@mikeger did it compile for you with following code

```swift
import AppCenter
import AppCenterAnalytics
import AppCenterCrashes

public struct SDKInitializeService: SDKInitializeServiceProtocol {

    public func initialize(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) {

        LogDebug { "SDKInitializeService.initialize called for app: \(application) with launch arguments: \(String(describing: launchOptions))" }
        AppCenter.start(withAppSecret: "your_secret_key", services: [Analytics.self, Crashes.self])
    }
}
```
Your build settings work for me if I don't include services in param i.,e `AppCenter.start(withAppSecret: "your_secret_key", services: [])` but adding `[Analytics.self, Crashes.self]` throws compiler error

**Comment by mikeger** [comment] 2022-12-13 20:18
@shahzadmajeed unfortunately I gave up on Tuist at that time. I think supporting those popular libraries is a most basic requirement, I think.

**Comment by shahzadmajeed** [comment] 2022-12-13 20:20
I had to add `OTHER_LDFLAGS: $(inherited) -lc++` to my target that depends on AppCenter as a dependency and now it is working fine.

**Comment by shahzadmajeed** [comment] 2022-12-13 23:00
So, I have been able to reduce above settings to the following:

`In Dependencies.swift`

```swift
public static var targetSettings: [String: SettingsDictionary] {
            [
                "CrashReporter": [
                    "USE_HEADERMAP": "YES",
                ],
                "AppCenterAnalytics": [
                    "USE_HEADERMAP": "YES",
                ],
                "AppCenterDistribute": [
                    "USE_HEADERMAP": "YES",
                ],
                "AppCenterCrashes": [
                    "USE_HEADERMAP": "YES",
                    "HEADER_SEARCH_PATHS": "$(SRCROOT)/Vendor/** $(SRCROOT)/AppCenter/AppCenter/** $(SRCROOT)/AppCenterCrashes/AppCenterCrashes/**",
                ],
            ]
        }
```

Added following for my target `In Project.swift`

```swift
var baseSettingsForMyTarget: SettingsDictionary {
     SettingsDictionary().otherLinkerFlags(["$(inherited) -ObjC -lc++"])
}
```

**Comment by shahzadmajeed** [comment] 2022-12-13 23:01
Hopefully, this will be helpful for narrowing down the problem further.

**Comment by fortmarek** [comment] 2024-02-15 08:50
Reopening as this dependency still does not build with the latest fixes.

**Closed** 2024-02-17 11:06 UTC
Labels: type:bug
