### ISSUE TITLE
Project with latest Firebase SDK (10.22.0) failed to build when using Tuist.

### ISSUE THREAD

**Issue by JohnnyTseng** [tuist/tuist#6036] opened 2024-03-06 10:01 UTC
### What problem or need do you have?

When you upgrade to Firebase Apple SDK v10.22.0 (https://github.com/firebase/firebase-ios-sdk/releases/tag/10.22.0)
and install via SPM using Tuist, the project fails to build and shows an error message like `DispatchQueue' has no member 'promises'`.

![Screenshot 2024-03-06 at 17 59 14](https://github.com/tuist/tuist/assets/2656519/92060be2-a303-4bb0-b1d1-f11ceeb2db88)

There are already several discussions in the Firebase repo:

1. https://github.com/firebase/firebase-ios-sdk/issues/12427
2. https://github.com/google/promises/issues/228

Most of the users who were affected are using Tuist. However, there is one user reporting they are not using Tuist but still encounter the issue.

### macOS version

14.3.1

### Tuist version

3.41.0

### Xcode version

15.3

**Comment by kapitoshka438** [comment] 2024-03-06 11:20
I'm not sure about Tuist 3.41.0 but Firebase 10.22.0 works fine with Tuist 4.4.0

**Comment by pepicrft** [comment] 2024-03-06 13:13
As @kapitoshka438 pointed out. Some of the issues integrating Packages, specially those that contain Objective-C code, have been addressed in recent Tuist 4 versions and therefore I'd recommend updating Tuist.

**Comment by fortmarek** [comment] 2024-03-06 17:36
I tried with the latest version of Tuist and can't reproduce the issue. We can reopen this if anybody runs into an issue building latest Firebase with the latest Tuist version.

**Closed by fortmarek** 2024-03-06 17:36 UTC
Labels: type:need/problem
