### ISSUE TITLE
AppAuth-iOS could not build Objective-C module 'AppAuth'

### ISSUE THREAD

**Issue by rafaelhziliao** [tuist/tuist#4562] opened 2022-06-22 16:20 UTC
## Describe the bug and the expected behavior
Hi everyone!
I'm trying to integrate [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) with Dependencies.swift and getting errors but when I change to SPM packages - all is fine.
I'm providing 2 sample apps one where the errors occur and another not.  

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project not_working
2. Run `tuist fetch`
3. Run `tuist generate`
4. Build the project
5. See the error

### Error screenshots
![Error](https://user-images.githubusercontent.com/31957007/175081242-926c0b61-0ba8-4835-92be-1819543f96b4.png)

![target_analyze](https://user-images.githubusercontent.com/31957007/175081266-6d083134-5868-4fbf-8dd0-57024ee8b25b.png)

### Additional context

- macOS version: 12.3.1
- Tuist version: 3.6.0
- Xcode version: 13.4.1

[not_working.zip](https://github.com/tuist/tuist/files/8959562/not_working.zip)
[working.zip](https://github.com/tuist/tuist/files/8959563/working.zip)

**Comment by icedice** [comment] 2022-06-28 08:32
Did you manage to solve this? I'm facing the same issue...

**Comment by danyf90** [comment] 2022-06-28 08:40
Thanks for reporting and for the sample projects @rafaelhziliao, we will try to have a look 🙏

**Comment by rafaelhziliao** [comment] 2022-06-28 11:20
Hi @icedice sadly not, at the moment I'm using this dependency as a package

**Comment by rafaelhziliao** [comment] 2022-06-28 11:21
Hey, @danyf90 thanks for helping!

**Comment by cooksimo** [comment] 2022-07-26 04:59
I have the same problem. It looks like all the headers are missing from the project that tuist generates

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1697654/180926840-74e9f09b-cffb-467a-bc2e-bca39d3e1758.png">

**Comment by danyf90** [comment] 2022-08-21 09:30
Closing as duplicate of https://github.com/tuist/tuist/issues/4688

**Closed by danyf90** 2022-08-21 09:30 UTC
Labels: domain:dependencies-swift
