### ISSUE TITLE
sdkroot set inconsistently with "real" Xcode

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#2131] opened 2020-12-10 20:41 UTC
When I look at the project-level settings, it looks like the generated project is for macOS:
![image (2)](https://user-images.githubusercontent.com/1033839/101826287-ca971280-3afc-11eb-8a16-ae16bd9a6aca.png)

When I look at the Target, it’s overridden to iOS:
![image (3)](https://user-images.githubusercontent.com/1033839/101826324-db478880-3afc-11eb-95b1-c67275b6d957.png)

When I generate a new, empty iOS project directly in Xcode, the Project settings reflect iOS:
![image (4)](https://user-images.githubusercontent.com/1033839/101826392-ee5a5880-3afc-11eb-9477-8c279b5c0720.png)

In an Xcode-created project, the setting `SDKROOT = iphoneos;` is added to two of the `XCBuildConfiguration` groups. Those groups are referenced like so

``` xml
		D252833E258122E900133432 /* Build configuration list for PBXProject "JustAniOSApp" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				D2528355258122EF00133432 /* Debug */,
				D2528356258122EF00133432 /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
```

In the tuist-generated project, those settings are also written into a pair of `XCBuildConfiguration`s, but those are referenced like so
``` xml
		D6D60577070A390A19563F0A /* Build configuration list for PBXNativeTarget "JustATuistApp" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				35E4B6B7130F4EC7845A7F41 /* Debug */,
				95D4BC425536AFF20734BD15 /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
```
(PBXProject vs. PBXNativeTarget)

It looks to me like `SDKROOT` is supplied to the *target* settings via 

[private static func targetSettings(platform: Platform) -> BuildSettings](https://github.com/tuist/XcodeProj/blob/a8cef4417ef3a23e54fb2ffe3bab6ca7f72266ba/Sources/XcodeProj/Utils/BuildSettingsProvider.swift#L163)

but I don't think that's completely correct. To get to the bottom of this, I created one Xcode project of each “flavor” from within Xcode itself, then looked at where `SDKROOT` gets defined relative to the Project or Target. This is what I observe:
![image (5)](https://user-images.githubusercontent.com/1033839/101826972-b30c5980-3afd-11eb-956a-5861f57681b8.png)

So, I think there needs to be some introspection at project generation time, where the “best” combination of `SDKROOT` settings are set.

**Comment by kwridan** [comment] 2020-12-11 07:01
Thanks for flagging this @kalkwarf 

Did you experience any issues that were caused by this inconsistency? 

The default settings created by Xcode depend on the initial target chosen - for example if the first target created with a new project is a macOS app, the project will have the macOS SDROOT. Subsequently adding a new iOS target will only have the SDKROOT set at the target level.

![Screenshot 2020-12-11 at 06 56 42](https://user-images.githubusercontent.com/11914919/101873163-5ef58980-3b7e-11eb-9009-5f5339cef5d0.png)

Tuist sets the SDKROOT at the target level as a project could host multiple different targets for different platforms.

![Screenshot 2020-12-11 at 06 54 51](https://user-images.githubusercontent.com/11914919/101873231-7cc2ee80-3b7e-11eb-9891-29f7eb614502.png)

**Comment by kwridan** [comment] 2020-12-11 07:03
ps. Thanks for the detailed write up looking into this 👍

**Comment by danyf90** [comment] 2022-04-09 20:30
Closing as it doesn't seem to be a problem, feel free to reopen it if you think it is 🙏

**Closed by danyf90** 2022-04-09 20:30 UTC
