### ISSUE TITLE
Build failures with SPM and Dependencies.swift

### ISSUE THREAD

**Issue by jsorge** [tuist/tuist#3563] opened 2021-10-14 16:50 UTC
**Describe the bug**
Running `tuist dependencies fetch` with Swift packages yields some build errors (with tuist v2.0.2). Included are the console output, as well as my Dependencies.swift file.

Console output:
<details>
  <pre> The project 'Branch' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'leveldb' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'abseil' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'SDWebImage' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'GoogleDataTransport' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'GTMSessionFetcher' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'SwiftProtobuf' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'Facebook' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'PhoneNumberKit' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'Promises' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'ButtonMerchant' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'Firebase' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'GoogleAppMeasurement' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'Atlantis' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'BoringSSL-GRPC' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'nanopb' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'gRPC' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'SnapshotTesting' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
The project 'GoogleUtilities' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Distribution (release), Release (release)]
Target PhoneNumberKit cannot contain resources. staticFramework targets do not support resources
Target FirebaseInAppMessaging_iOS cannot contain resources. staticFramework targets do not support resources
Fatal linting issues found</pre>
</details>

Dependencies.swift:

<details>
<pre>
import ProjectDescription

let dependencies = Dependencies(
    carthage: [
        .github(path: "braintree/braintree_ios", requirement: .exact("4.36.1")),
        .git(path: "https://gitlab.corp.zulily.com/site/bv-ios-sdk", requirement: .branch("zu-fixes")),
    ],
    swiftPackageManager: [
        .remote(
            url: "https://github.com/BranchMetrics/ios-branch-deep-linking-attribution.git",
            requirement: .exact("1.39.3")
        ),

        .remote(
            url: "https://github.com/button/button-merchant-ios.git",
            requirement: .exact("1.4.1")
        ),

        .remote(
            url: "https://github.com/firebase/firebase-ios-sdk.git",
            requirement: .exact("8.8.0")
        ),

        .remote(
            url: "https://github.com/facebook/facebook-ios-sdk.git",
            requirement: .exact("9.2.0")
        ),

        .remote(
            url: "https://github.com/pointfreeco/swift-snapshot-testing.git",
            requirement: .upToNextMajor(from: "1.8.2")
        ),

        .remote(
            url: "https://github.com/jsorge/PhoneNumberKit.git", // https://github.com/marmelroy/PhoneNumberKit.git
            requirement: .exact("3.4.0")
        ),

        .remote(
            url: "https://github.com/SDWebImage/SDWebImage.git",
            requirement: .upToNextMajor(from: "5.10.4")
        ),

        .remote(
            url: "https://github.com/ProxymanApp/atlantis.git",
            requirement: .upToNextMajor(from: "1.8.0")
        ),
    ],
    platforms: [.iOS]
)
</pre>
</details>

**Additional context**
The first batch of issues all seem to revolve around that our project uses 3 build configurations (Debug, Distribution, and Release), while the second (and fatal) issues revolve around some package dependencies that have resources with them.

**Comment by danyf90** [comment] 2021-10-18 14:43
@jsorge do you have the `disableBundleAccessors` option configured? https://github.com/tuist/tuist/issues/3313

**Comment by danyf90** [comment] 2021-10-18 14:56
Until we fix that issue, having `disableBundleAccessors` is not supported.

Regarding the first batch of errors (are they errors or warning?), we probably need a way to tell the SPM mapping which configurations it should generate, as for now it just generates the default ones

**Comment by danyf90** [comment] 2021-11-19 18:31
Closed as duplicate of the 2 issues (`disableBundleAccessors` and custom configurations)

**Closed by danyf90** 2021-11-19 18:31 UTC
Labels: type:bug, dependencies, domain:dependencies-swift
