### ISSUE TITLE
Is it possible to support multiple platforms for test target

### ISSUE THREAD

**Issue by Binlogo** [tuist/tuist#6426] opened 2024-06-21 02:14 UTC
### What problem or need do you have?

It seems like tests target only single platform supported at this moment.

**Error output**: 

> Testing scheme CargoXCFramework-Workspace
> Only single platform targets supported. The target AppTests specifies multiple supported platforms (macos, ios).

**Project description file**:

```swift
import ProjectDescription

let project = Project(
    name: "Project",
    targets: [
        .target(
            name: "App",
            destinations: [.iPhone, .iPad, .mac, .macCatalyst],
            product: .app,
            bundleId: "cargo.xcframework.App",
            infoPlist: .default,
            sources: ["App/Sources/**"],
            resources: ["App/Resources/**"],
            dependencies: [
                .xcframework(path: "../mymath-lib/target/MyMath.xcframework")
            ]
        ),
        .target(
            name: "AppTests",
            destinations: [.iPhone, .mac],
            product: .unitTests,
            bundleId: "cargo.xcframework.AppTests",
            infoPlist: .default,
            sources: ["App/Tests/**"],
            resources: [],
            dependencies: [.target(name: "App")]
        ),
    ]
)
```

### macOS version

14.5

### Tuist version

4.17.0

### Xcode version

15.4

**Comment by fortmarek** [comment] 2024-06-21 07:07
Hey @Binlogo 👋 

This is a known limitation. I'm closing this as a duplicate of https://github.com/tuist/tuist/issues/5920 but this feature definitely needs to be built.

**Closed by fortmarek** 2024-06-21 07:07 UTC
Labels: type:need/problem
