### ISSUE TITLE
Dealing with static linked libraries in SPM packages

### ISSUE THREAD

**Issue by malcommac** [tuist/tuist#4678] opened 2022-08-12 07:54 UTC
Hi again,
As suggested in #4674 I've created an SPM definition for each of my application's framework.  
As I said each framework also imports several external dependencies.  

One of these frameworks, called IndomioAnalytics, declares [Braze SDK dependency](https://github.com/Appboy/appboy-ios-sdk).  
That's a snippet of `Package.swift`:

```swift
let package = Package(
    name: "IndomioAnalytics",
    platforms: [
        .iOS(.v14)
    ],
    products: [
        .library(
            name: "IndomioAnalytics",
            targets: ["IndomioAnalytics"])
    ],
    dependencies: [
        ...
     	.package(name: "Appboy", url: "https://github.com/Appboy/appboy-ios-sdk.git", .exact("4.5.0"))
    ],
    targets: [
        .target(
            name: "IndomioAnalytics",
            dependencies: [
                ...
                .product(name: "AppboyKit", package: "Appboy"),
                .product(name: "AppboyUI", package: "Appboy"),
                .product(name: "AppboyPushStory", package: "Appboy")
            ])
    ]
)
```

Now I've created my `Project.swift` for the main app host and added the dependency to it.  
That's the snippet of `Project.swift`:

```swift
import ProjectDescription
import Darwin

let project = Project(
    name: "Indomio",
    targets: [
        Target(
            name: "Indomio",
            ....
            dependencies: [
               ...
                .external(name: "IndomioAnalytics")
            ]
        )
    ],
    schemes: [
        Scheme(
            name: "Indomio",
            shared: true,
            buildAction: .buildAction(targets: ["Indomio"]),
            testAction: .targets(["Indomio"]),
            runAction: .runAction(executable: "Indomio")
        )
    ]
)
```

`Dependencies.swift`:

```swift
import ProjectDescription
let dependencies = Dependencies(
    swiftPackageManager: [
        ...
        .local(path: "../Frameworks/IndomioAnalytics"),
    ],
    platforms: [.iOS]
)
```

When I try to use `tuist fetch && tuist generate --no-cache` I got the following error:

```
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
The product AppboyKit of package Appboy cannot be found. <------------ ERROR
```

It seems happening only for this package *(in fact I must confess I saw it even with Firebase but each attempt in the last hour returned only AppBoy)*.

I've tried to see the `Package.swift` of AppBoy [here](https://github.com/Appboy/appboy-ios-sdk/blob/master/Package.swift) and I found AppboyKit is the only statically linked lib:

```
products: [
    .library(name: "AppboyKit", type: .static, targets: ["AppboyKit"]), <------------ STATICALLY LINKED
    .library(name: "AppboyUI", targets: ["AppboyUI"]),
    .library(name: "AppboyPushStory", targets: ["AppboyPushStory"])
  ],
```

Could be an issue?  
Should I handle it in some particular mode?

BTW The SPM package of IndomioAnalytics compiles with no errors at all.

### Additional context

- macOS version: 12.5
- Tuist version: 3.9.0
- Xcode version: 13.4.1

**Comment by danyf90** [comment] 2022-08-12 08:16
Might be some big in parsing the Package.swift.
Can you provide a project to reproduce the issue?

**Comment by malcommac** [comment] 2022-08-12 10:39
Yup, sure: [TestDependencies.zip](https://github.com/tuist/tuist/files/9315688/TestDependencies.zip)

```
Last login: Fri Aug 12 08:21:56 on ttys000
➜  TestProj tuist fetch && tuist generate --no-cache
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
Fetching https://github.com/Appboy/appboy-ios-sdk.git from cache
Fetched https://github.com/Appboy/appboy-ios-sdk.git (0.85s)
Computing version for https://github.com/Appboy/appboy-ios-sdk.git
Computed https://github.com/Appboy/appboy-ios-sdk.git at 4.5.0 (0.31s)
Fetching https://github.com/SDWebImage/SDWebImage.git from cache
Fetched https://github.com/SDWebImage/SDWebImage.git (1.00s)
Computing version for https://github.com/SDWebImage/SDWebImage.git
Computed https://github.com/SDWebImage/SDWebImage.git at 5.13.2 (0.30s)
Creating working copy for https://github.com/Appboy/appboy-ios-sdk.git
Working copy of https://github.com/Appboy/appboy-ios-sdk.git resolved at 4.5.0
Creating working copy for https://github.com/SDWebImage/SDWebImage.git
Working copy of https://github.com/SDWebImage/SDWebImage.git resolved at 5.13.2
[39/2571] Downloading binary artifacts
The product AppboyKit of package Appboy cannot be found.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
➜  TestProj 
```

**Comment by danyf90** [comment] 2022-08-12 18:04
Looks like the problem is in the `IndomioAnalytics` Package, tuist would expect `Appboy_iOS_SDK` instead of `Appboy` in `.package(name: "Appboy", url: "https://github.com/Appboy/appboy-ios-sdk.git", .exact("4.5.0"))`, does it work fine when building with SPM?
trying to `swift build` it I get a different error: `error: the library 'AppboyKit' requires macos 10.10, but depends on the product 'SDWebImage' which requires macos 10.11; consider changing the library 'AppboyKit' to require macos 10.11 or later, or the product 'SDWebImage' to require macos 10.10 or earlier.`

**Comment by shahzadmajeed** [comment] 2022-08-12 18:33
FWIW, I integrated Appboy in a sample project few days ago and it worked fine https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L18

You do have to refer to products as `appboy-ios-sdk` package though https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L42

**Comment by malcommac** [comment] 2022-08-12 18:52
Using `Appboy_iOS_SDK` seems it generate correctly the project.  
About your error, it's just because it's iOS only, not macOS, so I think it's okay (did you know if I can limit the generated schema to iOS only?).

I'll try now with the main project, but I have a doubt: even when using `.package(name: "CUSTOM_NAME", ...` I still must rely on the package name inside the original library's `Package.swift` file?  
I've also tried to set only the URL without the name (`.package(name: "Appboy_iOS_SDK", url: "https://github.com/Appboy/appboy-ios-sdk.git", .exact("4.5.0"))`), then set the dependency by using the name of the package (`.product(name: "AppboyKit", package: "Appboy_iOS_SDK")`) but I got this error from SPM:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/235645/184424627-17557e42-8a02-48f9-a890-46274b3bbfcf.png">

This is just a bit confusing. Should I use the same name of the package and re-add it even inside the `.package`'s name?

**Comment by malcommac** [comment] 2022-08-12 19:06
> FWIW, I integrated Appboy in a sample (NON-TUIST) project few days ago and it worked fine https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L18
> 
> You do have to refer to products as `appboy-ios-sdk` package though https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L42

I still not figure what `appboy-ios-sdk` is; the name of the repo? Why is not [`Appboy_iOS_SDK `](https://github.com/Appboy/appboy-ios-sdk/blob/master/Package.swift#L6) which is the name in the manifest?

**Comment by danyf90** [comment] 2022-08-12 19:06
I remember there was some change about that in a recent Xcode release, maybe in the Xcode 14 beta 🤔

**Comment by malcommac** [comment] 2022-08-12 19:17
Okay, I can confirm using the name of `Package.swift` both inside SPM, Tuist works correctly.  
The project is generated successfully.  
So it's not something related to the static linked lib.

Unfortunately, the `Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE` is back, but I think it's another story, related to #3785.
 
`/Users/daniele/Developer/Immobiliare/Indomio/Indomio/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/appboy-ios-sdk/AppboyUI/ABKUIUtils/ABKUIUtils.m:27:12: Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'`.

**Comment by shahzadmajeed** [comment] 2022-08-12 19:33
> > FWIW, I integrated Appboy in a sample (NON-TUIST) project few days ago and it worked fine https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L18
> > You do have to refer to products as `appboy-ios-sdk` package though https://github.com/shahzadmajeed/m1-dependency-testing/blob/master/DependencyManager/Package.swift#L42
> 
> I still not figure what `appboy-ios-sdk` is; the name of the repo? Why is not [`Appboy_iOS_SDK `](https://github.com/Appboy/appboy-ios-sdk/blob/master/Package.swift#L6) which is the name in the manifest?

It is not the package name (which it actually should be). It is repository path from the url

**Comment by danyf90** [comment] 2022-08-12 20:39
Closing this and keeping #3785 for the module bundle issue. If you want to try to fix it feel free to write on slack to get some directions on it 🙏

**Closed by danyf90** 2022-08-12 20:39 UTC
