### ISSUE TITLE
"Inspect implicit-imports" not found FirebasePerfomance

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#6903] opened 2024-10-21 19:59 UTC
### What happened?

When I run tuist inspect implicit-imports I get the output:
```bash
The following implicit dependencies were found:
 - MY_APP implicitly depends on: FirebasePerformance, FirebaseCore
```

The following lines of code are in the AppDelegate:
```swift
import FirebaseCore
import FirebasePerformance
```

In Tuist/Package.swift:
```swift
.package(
     url: "https://github.com/firebase/firebase-ios-sdk.git",
     exact: "10.23.0"
),
```

The application target declares two dependencies:
```swift
Target.target(
   name: "MY_APP",
   ....
  dependencies: [ 
       .external(name: "FirebaseCrashlytics"),
       .external(name: "FirebasePerformance")
  ]
```

### How do we reproduce it?

1. Create `Project.swift`
2. Add application `Target` with dependencies:
```swift
Target.target(
   name: "MY_APP",
   ....
  dependencies: [ 
       .external(name: "FirebaseCrashlytics"),
       .external(name: "FirebasePerformance")
  ]
```
3. Add Firebase package to `Tuist/Package.swift`
4. Add import-s in AppDelegate
5. Run `tusit install; tuist generate`
6. Run `tuist inspect implicit-imports `

### Error log

```sh
The following implicit dependencies were found:
 - MY_APP implicitly depends on: FirebasePerformance, FirebaseCore
```

### macOS version

14.7

### Tuist version

4.30.0

### Xcode version

14.3

**Comment by jeffremer** [comment] 2024-10-29 22:59
@fortmarek I was able to reproduce this in the `multiplatform_app_with_sdk` fixture by adding `import FirebasePerformance` to `AppDelegate.swift`. The `App` target in that fixture already links `FirebasePerformance`. 

Attached is an isolated version of that fixture with that change.

1. Download and unzip the attachment
2. From the within the folder run `tuist install && tuist inspect implicit-imports`

Here's what I get on `tuist@4.31.0`…

![Screenshot 2024-10-29 at 3 58 59 PM](https://github.com/user-attachments/assets/dbf1a16f-3189-4c65-8f8a-05696b8e9205)

**Comment by fortmarek** [comment] 2024-10-30 08:02
@rofle100lvl do you think you'd have time to look into this? 🙏

**Comment by jeffremer** [comment] 2024-10-30 18:06
@rofle100lvl, @fortmarek in the example I provided `FirebasePerformance` _is_ explicitly linked (as well as `FirebasePerformanceTarget`) and it does throw that implicit-import error.

Any thoughts on a workaround for this? The first thing I thought of when encountering it was wondering if something like a `swiftlint` style inline ignore for certain cases would be handy. Or an option to ignore external dependencies in `inspect implicit-imports`. I'd love to keep using `inspect implicit-imports` in CI as a check, but this issue is a blocker.

**Comment by jeffremer** [comment] 2024-10-30 18:11
Funny, in a desperate attempt to mollify `inspect-imports` I tried back-ticking the import and that helps…

```
import `FirebasePerformance`
```

**Comment by rofle100lvl** [comment] 2024-10-31 08:50
@jeffremer Firstly, Jeff, thank you for the trick with back-ticking. It's a nice and easy way to temporarily bypass imports if something breaks.

Secondly, here comes the question. The Package.swift contains the library "A". This library contains target "A", and target "A" includes target "B" as a dependency. Should we consider target B explicitly imported after Tuist project generation? In my opinion, we should not consider target B as explicit. However, in the example with FirebasePerformance, we can see in the generated project (screenshot above) that target FirebasePerformance and target FirebasePerformanceTarget are linked explicitly to target App. However, if you check the dependencies of target App in GraphTraverser, you would only see FirebasePerformanceTarget. @fortmarek, what are your thoughts?

**Comment by stefanomondino** [comment] 2024-10-31 20:41
hey @rofle100lvl , just wanted to add my current experience to this thread.
With just FirebaseCrashlytics and/or FirebaseAnalytics, I get an error that Firebase (or FirebaseCore) is imported implicitly. 

`FirebaseCore` is used to bootstrap the Firebase app  (the classic `FirebaseApp.configure()` everybody is using when dealing with default Firebase), and it's also showing in @Ernest0-Production logs up there.

If I try to link my app target to Firebase or FirebaseCore, I get this -> `Firebase is not a valid configured external dependency` - don't know if it's related to another bug here #6272 

The problem is that I'd love to include this command in my unit-test pipeline to block a "broken" setup before it's merged, but this Firebase issue (i think) it's blocking many people from using it.

Do you think that we could add an exclude list to the command? I agree with you - there's something wrong with Firebase, but it's unlikely that anybody there will take risks to fix such a complex setup of inter-dependant frameworks and libraries.
What do you think?

**Comment by jeffremer** [comment] 2024-10-31 20:46
Same/similar with FirebaseCore vs. Firebase for us.

> Do you think that we could add an exclude list to the command?

An exclude list, or explicit ignore syntax (something better than my backticking workaround), and possibly a wholesale option to exclude external dependencies would be pretty useful for us. Generally we've only had problems with implicit internal dependencies - I can't think of an instance where an external one has bit us yet 🤜 🪵.

**Comment by stefanomondino** [comment] 2024-10-31 20:47
@jeffremer 5 seconds after replying, I've checked the Package.swift and realized that Firebase is now on version 11.4 and I was still on 10.x

Updating to latest version fixed the issue for me (I had to import FirebaseCore and not Firebase though)

**Comment by rofle100lvl** [comment] 2024-11-01 09:01
@jeffremer I will make exclude-external-dependencies mode this weekend. You are right, that this mode should be presented

**Comment by jeffremer** [comment] 2024-11-01 16:04
> @jeffremer I will make exclude-external-dependencies mode this weekend. You are right, that this mode should be presented

Fantastic, thank you 🙏 `inspect implicit-imports` has been a huge help so far, we really appreciate the work you, @fortmarek, and crew are doing ❤️

**Comment by hiltonc** [comment] 2024-11-03 21:15
I've updated Firebase to 11.4.0, yet I still have this problem. I'm importing `FirebaseFirestore`, but `InspectImplicitImportsService` gets `FirebaseFirestoreTarget` from the graph traverser.

I'm using `inspect implicit-imports` in a pre-commit git hook and want to validate external dependencies. For now I can use backticks in the `import FirebaseFirestore` as a workaround, but I'm hoping we can come up with a solution that enables it to work without the hack.

**Closed** 2024-11-22 09:07 UTC
Labels: type:bug, p2
