### ISSUE TITLE
Embedded Framework not loaded || Mutliple commands produce

### ISSUE THREAD

**Issue by muellerando** [tuist/tuist#586] opened 2019-10-21 14:18 UTC
**Describe the bug**
I have got this carthage dependency:
`				.framework(path: "../Carthage/Build/iOS/UICKeyChainStore.framework"),
`
The Project builds nicely in xcode. But when i try to run the App i got following error:

```
dyld: Library not loaded: @rpath/UICKeyChainStore.framework/UICKeyChainStore
  Referenced from: /Users/meu4abt/Library/Developer/CoreSimulator/Devices/E464A7A3-2812-44C5-B3EA-19E905CFB237/data/Containers/Bundle/Application/303BB4ED-AEEB-4452-9035-7F331E01FD5C/COBI.app/COBI
  Reason: image not found
```
If I try to change to Library to be embedded, xcode build complains: `Multiple commands produce: ....`

Does anyone has got an idea what could be the problem?
PS: I tried `Embedd & Sign` && `Embedd without signing`

**Comment by pepibumur** [comment] 2019-10-21 15:56
Hey @muellerando, thanks for reporting this. Would you mind [creating a reproducible](https://docs.tuist.io/contribution-tuist#how-to-make-a-minimal-reproduction) project that helps us reproduce the issue?

**Comment by pepibumur** [comment] 2019-11-01 10:46
This should be fixed [here](https://github.com/tuist/tuist/pull/610), would you mind doing the following in your project and check out if the issue is still happening?

1. Run `tuist local 8df4e6464b4561808bd76225537dd75cf21aaa79` in the project directory.
2. Then run `tuist generate`. It'll take a while because it'll compile the latest version from master.
3. Open the generated project and try to compile the app.

If that works we'll close the issue :)

**Comment by pepibumur** [comment] 2019-11-12 15:51
@fortmarek already reported that the fix works so I'm closing this. If it happens to you again feel free to reopen the issue @muellerando

**Closed by pepibumur** 2019-11-12 15:51 UTC
Labels: status:needs-reproduction, type:bug
