### ISSUE TITLE
Tuist Test does not include watchOS Unit tests.

### ISSUE THREAD

**Issue by Narsail** [tuist/tuist#6358] opened 2024-06-01 18:20 UTC
### What happened?

My project does include unit tests for frameworks, an iOS and watchOS target. Running `tuist test` does run all my iOS framework and app tests but does ignore the watchOS target.

### How do we reproduce it?

1. Checkout this sample project: https://github.com/Narsail/TuistTestingExample
2. Run 
```
tuist clean
tuist generate --no-open
tuist test
```

### Error log

<img width="1240" alt="Screenshot 2024-06-01 at 20 19 03" src="https://github.com/tuist/tuist/assets/7859096/41265f7a-587e-4aa2-8303-f0d7182816d4">

^ As seen in the screenshot, it only runs the **testsIOSDummyTests** but not the **testWatchOSDummyTests**.

### macOS version

14.4.1

### Tuist version

4.15.0

### Xcode version

15.3

**Comment by woin2ee** [comment] 2024-06-17 04:17
I tried to reproduce it to resolve, but in my case, all of both test targets were tested via `tuist test`, didn't not ignore the watchOS target. It looks like we need more information to resolve it

**Log**
<img width="600" alt="image" src="https://github.com/tuist/tuist/assets/81426024/61e19eba-259f-46dd-9a59-ab242791615e">
...
<img width="600" alt="image" src="https://github.com/tuist/tuist/assets/81426024/81236bff-76cf-4941-bab7-c73514242781">

**Comment by pepicrft** [comment] 2024-06-25 17:13
@Narsail would you mind revisiting the reproducible project and provide more detailed steps to reproduce the issue?

**Comment by Narsail** [comment] 2024-06-26 09:11
Oh, I totally forgot about this. I think I observed at some point that it did test the watchOS target. I assume that it depends on whether the simulator is available by Xcode. Based on that I would close the issue. Sorry for troubling you folks.

**Comment by fortmarek** [comment] 2024-06-28 10:37
Thanks for getting back to us.

Closing – we can reopen if somebody runs into this again and is able to provide reproduction steps.

**Closed by fortmarek** 2024-06-28 10:37 UTC
Labels: type:bug
