### ISSUE TITLE
Tuist Edit command doesn't work after generating project

### ISSUE THREAD

**Issue by raulbatista94** [tuist/tuist#5903] opened 2024-02-09 08:34 UTC
### What happened?

After adding a new dependency (in this case RevenueCat SDK) the tuist edit command stopped working unless I run `tuist clean`. If I run `tuist fetch` and `tuist generate` then it stopps working again so every time that I want to edit something i must run `tuist clean` then edit what I need and then run `tuist fetch & tuist generate`.

### How do we reproduce it?

1. Add dependencies ( in my case this appeared after adding RevenueCat SDK)
2. Generate the whole project.
3. Try running `tuist edit`
4. Nothing happens after running this command. Seems that it gets stuck checking files.

### Error log

This is what happens when I run the command with --verbose
```
Checking if /Users/raulbatista/.tuist exists... true
Checking if /Users/raulbatista/.tuist/Versions exists... true
Checking if /Users/raulbatista/Projects/verge-ios/Tuist exists... true
Checking if /Users/raulbatista/Projects/verge-ios/Tuist/Config.swift exists... false
Traversing /Users/raulbatista/Projects/verge-ios to locate Config.swift
Checking if /Users/raulbatista/Projects/verge-ios/Config.swift exists... false
Traversing /Users/raulbatista/Projects to locate Config.swift
Checking if /Users/raulbatista/Projects/Config.swift exists... false
Traversing /Users/raulbatista to locate Config.swift
Checking if /Users/raulbatista/Config.swift exists... false
Traversing /Users to locate Config.swift
Checking if /Users/Config.swift exists... false
Traversing / to locate Config.swift
Checking if /Config.swift exists... false
Checking if /Users/raulbatista/Projects/verge-ios/Tuist exists... true
Checking if /Users/raulbatista/Projects/verge-ios/Tuist/Config.swift exists... false
Traversing /Users/raulbatista/Projects/verge-ios to locate Config.swift
Checking if /Users/raulbatista/Projects/verge-ios/Config.swift exists... false
Traversing /Users/raulbatista/Projects to locate Config.swift
Checking if /Users/raulbatista/Projects/Config.swift exists... false
Traversing /Users/raulbatista to locate Config.swift
Checking if /Users/raulbatista/Config.swift exists... false
Traversing /Users to locate Config.swift
Checking if /Users/Config.swift exists... false
Traversing / to locate Config.swift
Checking if /Config.swift exists... false
xcode-select -p
/Applications/Xcode15.0.1.app/Contents/Developer

Checking if /Applications/Xcode15.0.1.app/Contents/Info.plist exists... true
Reading contents of text file at path /Users/raulbatista/Projects/verge-ios/.tuistignore
Checking if /Users/raulbatista/.tuist/Versions/3.27.1/libProjectDescription.dylib exists... false
Checking if /Users/raulbatista/.tuist/Versions/3.27.1/ProjectDescription.framework exists... true
Checking if /Users/raulbatista/Projects/verge-ios/Tuist exists... true
Dispatching persisted event with ID '073D2AE3-2112-4401-BCD1-22C139F1FAF9' to 'TuistAnalytics'
Checking if /Users/raulbatista/.tuist/Queue/1707463856.TuistAnalytics.073D2AE3-2112-4401-BCD1-22C139F1FAF9.json exists... true
Deleting item at path /Users/raulbatista/.tuist/Queue/1707463856.TuistAnalytics.073D2AE3-2112-4401-BCD1-22C139F1FAF9.json
Checking if /Users/raulbatista/.tuist/Queue/1707463856.TuistAnalytics.073D2AE3-2112-4401-BCD1-22C139F1FAF9.json exists... true
```

### macOS version

14.1

### Tuist version

3.27.1

### Xcode version

15.0.1

**Comment by pepicrft** [comment] 2024-02-12 06:16
Hey @raulbatista94 do you mind trying with the most recent Tuist version? This is a very common use case that we validate through the usage of Tuist, so I'd be surprised if it's broken in recent versions. If the problem persists, would you mind including a small project where we can reproduce the issue?

**Comment by fortmarek** [comment] 2024-02-19 17:33
Closing due to a missing repro case. Happy to take a look if you can provide one 🙏

**Closed by fortmarek** 2024-02-19 17:33 UTC
Labels: type:bug, needs-reproduction
