### ISSUE TITLE
📦 [Dependencies.swift][SPM] Fix ZipArchive dependency

### ISSUE THREAD

**Issue by fbp93** [tuist/tuist#3463] opened 2021-09-16 15:50 UTC
**Describe the bug**
The ZipArchive dependency doesn't build correctly when imported via Dependencies.swift.

**To Reproduce**

1. Download the attached [project](https://github.com/tuist/tuist/files/7179178/Sample.zip)
2. Run tuist dependencies fetch and tuist generate --open
3. Build from Xcode
4. Compilation fails with error `Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ZipArchive/SSZipArchive/include/ZipArchive.h:24:9: 'SSZipArchive.h' file not found`

**Package**
This Package.swift can be used to replicate the same scenario with SPM (which is working fine):

```swift
// swift-tools-version:5.4.0

import PackageDescription

let package = Package(
  name: "Sample",
  platforms: [.iOS(.v9)],
  products: [
    .library(
      name: "Sample",
      targets: ["Sample"]
    ),
  ],
  dependencies: [
    .package(
      name: "ZipArchive",
      url: "https://github.com/ZipArchive/ZipArchive.git",
      from: "2.3.0"
    ),
  ],
  targets: [
    .target(
      name: "Sample",
      dependencies: [
        .product(name: "ZipArchive", package: "ZipArchive"),
      ],
      path: "Sources"
    ),
  ]
)

```

**Comment by danyf90** [comment] 2022-08-21 09:29
Closing as duplicate of https://github.com/tuist/tuist/issues/4688

**Closed by danyf90** 2022-08-21 09:29 UTC
Labels: domain:dependencies-swift
