### ISSUE TITLE
tuist test doesn't use cached targets

### ISSUE THREAD

**Issue by Alex-Ozun** [tuist/tuist#5482] opened 2023-10-06 12:08 UTC
### What problem or need do you have?

When `tuist test` skips testing for unmodified targets it still compiles them instead of using cached `xcframework`s when they are available. 

## Steps to reproduce (Option 1):

Go to the minimum reproduction project: https://github.com/Alex-Ozun/TuistTestCaching

## Steps to reproduce (Option 2):

Given this graph:

![graph](https://github.com/tuist/tuist/assets/8514453/0000bc65-c252-4290-9625-109420ec10bc)

1. Warm cache
```bash
tuist cache warm --xcframeworks
``` 
`FeatureA` should now be cached. 

2. Run tests. Both `App` and `FeatureA` are expected to be compiled and tested.
```bash
tuist test --clean
``` 

3. Modify `App` module to invalidate `App`'s cached tests. `FeatureA` caches are still valid. 

4. Run tests again.  
```bash
tuist test --clean
``` 

## Expected result:
 
Since `FeatureA` was not modified, we expect it to be replaced by the cached `xcframework` from Step 1, thus skipping BOTH compilation and testing.

## Actual result:

`FeatureA` is only skipped for testing, but is STILL compiled. You can observe that the last step produces compilation logs for `FeatureA`:  
```
FeatureATests has not changed from last successful run, skipping...
Generating project FeatureA
[...]
[FeatureA] Processing FeatureA-Info.plist
[FeatureA] Compiling FeatureA_vers.c
[FeatureA] Touching FeatureA.framework
```

### Potential solution

If this is not a bug but a missing functionality I think we should be able to add it, potentially under a dedicated flag e.g. `test test --use-cache` or something like this. I believe the implementation should be relatively straightforward given all the systems required are already in place.

### macOS version

13.5

### Tuist version

3.28.0

### Xcode version

14.3.1

**Comment by danyf90** [comment] 2023-10-06 12:23
Duplicate of https://github.com/tuist/tuist/issues/5034

**Closed by danyf90** 2023-10-06 12:23 UTC
Labels: type:need/problem
