### ISSUE TITLE
Embed Precompiled Frameworks for Carthage

### ISSUE THREAD

**Issue by asalom** [tuist/tuist#897] opened 2020-01-20 09:33 UTC
**Describe the bug**
When adding a dependency of type `.framework` coming from Carthage, tuist adds a build phase named `Embed Precompiled Frameworks` with not only the framework but also a file with the extension `.bcsymbolmap` which name changes machine to machine, after running `carthage bootstrap/update`. This will prevent the project from compiling if we share Xcode's project files with someone else.

**To Reproduce**
1. Run `carthage update --platform ios` on the following `Cartfile`
```
github "ReactiveCocoa/ReactiveCocoa"
```

2. Run `tuist generate` on the following `Project.swift`
```swift
import ProjectDescription

let code = Target(name: "Carthage",
                  platform: .iOS,
                  product: .app,
                  bundleId: "es.alexsalom.Carthage",
                  infoPlist: "Sources/Info.plist",
                  sources: ["Sources/**"],
                  dependencies: [
                    .framework(path: "Carthage/Build/iOS/ReactiveCocoa.framework"),
                    .framework(path: "Carthage/Build/iOS/ReactiveSwift.framework")
                  ]
            )

let project = Project(name: "Carthage",
                      targets: [code]
)
```

3. Check the `Embed Precompiled Frameworks`
4. This project won't compile if you share it with someone else because of the missing `.bcsymbolmap` files.

**Screenshots**
<img width="939" alt="Screenshot 2020-01-20 at 10 24 04" src="https://user-images.githubusercontent.com/1466079/72714456-05076200-3b6f-11ea-9857-3cf5b196cbda.png">

**Comment by JulianAlonso** [comment] 2020-01-21 12:50
Same as above

**Comment by adellibovi** [comment] 2022-02-21 14:27
Hi @asalom and @JulianAlonso , I am closing this issue. The suggested approach is to use Carthage via `Dependencies.swift`, in that case, the issue is no longer present.

**Closed by adellibovi** 2022-02-21 14:27 UTC
Labels: type:bug
