### ISSUE TITLE
Unable to leverage `tuist test` with CocoaPods

### ISSUE THREAD

**Issue by Jake-Prickett** [tuist/tuist#2453] opened 2021-02-07 13:02 UTC
**Describe the bug**
When running `tuist test` on a project that leverages CocoaPods, the Pods are not integrated with the generated custom project for the test command.

**To Reproduce**

1. Have a project that leverages CocoaPods
2. Run `tuist test`
3. Observe build failures around importing CocoaPod dependency

**Expected behavior**
The temporary generated custom project/workspace should be updated after pod install instead of the local project.

**Desktop (please complete the following information):**

- OS: Catalina 10.15.7
- Version 1.33.0

**Additional context**
Sample project - [pod_test_project.zip](https://github.com/tuist/tuist/files/5939010/pod_test_project.zip)

There's a bit of working being done around this area currently and it seems to be changing (https://github.com/tuist/tuist/pull/2057, https://github.com/tuist/tuist/pull/2422) but please let me know if I can help fix this one! 👍

**Comment by fortmarek** [comment] 2021-02-08 14:12
Thanks @Jake-Prickett!

The cause of this will be the same as explained [here](https://github.com/tuist/tuist/issues/2478#issuecomment-775175666).

I will investigate this further, thanks for flagging this.

In the meantime, if you are using `tuist test`, you'll probably have to fallback to something like `xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourApp-Project` or use an older version of tuist. Sorry for the incovenience 😞

**Comment by fortmarek** [comment] 2021-02-10 19:55
So, the issue is [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/CocoaPodsInteractor.swift#L78). 

We specify the `--project-directory` when running `pod install` with a path to where your project is defined - not where the automation project will be generated. 

Unfortunately, changing `--project-directory` to the location of automation project will not be a feasible option, too, because then `pod` command will not be able to find `Podfile` as both `Podfile` and `.xcodeproj` should be located in the same location.

You can specify the `.xcodeproj` location but, unfortunately, that is only possible by modifying `Podfile` with adding `project /path/to/my.xcodeproj`

This means we have these three following options:
- Make a PR to `Cocoapods` to add the ability to specify `xcodeproj` location from the CLI. This would be the best option from our side but I doubt this will get accepted as the user would be able to specify `xcodeproj` by two different ways and then it'd be ambiguous which one would be chosen (but we can try to create an issue for this if the pods team has any thoughts on this)
- Edit `Podfile` temporarily to point to the location of generated project. This might work but just feels fragile, so I would not do this
- Copy `Podfile`, `Pods`, and `Podfile.lock` to the directory where automation project is generated and update the path for `--project-directory` option. This might be fine for most use cases but might get broken if you need to reference some other non-xcodeproj files in your project by their relative paths as they would not be there if we just copied the `Podfile` somewhere else.

I am not really using pods for a while now, so I might be missing something. This is a big issue as without it `tuist test` will be unusable for any project with Cocoapods which still a lot of project do use and will continue using, at least in the near future.

I will probably try to create an issue in Cocoapods repo later this week as they might help guide us in the right direction.

**Comment by Jake-Prickett** [comment] 2021-03-01 13:31
Apologies I haven't gotten the chance to follow-up on this one. 

The description of the problem makes perfect sense. My initial investigation led me to the file you shared as well. As for solutions, I honestly am not entirely sure on the best approach out of your suggestions. I agree that it is key to have Cocoapods operational as it is still heavily leveraged in the iOS community. I'd love to help out if possible. 

Have you made any progress on your end with the Cocoapods Issue?

As far as future proofing to prevent issues like this from being introduced, would it be a good idea to put a few acceptance tests in place focused around Cocoapods projects?

**Comment by fortmarek** [comment] 2021-03-09 17:17
> Have you made any progress on your end with the Cocoapods Issue?

Unfortunately, not 😞 

Looking at this again, I think the best solution might be a mix of option number two and three.

We can copy `Podfile`, `Podfile.lock` and `Pods` to the automation directory. Afterwards, we'll have to search and replace paths pointing to sources - afaict, these are prepended with `:path`, but there might be different use cases with which you can touch on sources relative from the original `Podfile` location.

LMK if you'd like to try to take this on - as mentioned early, I am a little bit rusty with CocoaPods but also might have time to look at this in the foreseeable future.

> As far as future proofing to prevent issues like this from being introduced, would it be a good idea to put a few acceptance tests in place focused around Cocoapods projects?

There is `ios_app_with_pods` fixture, we're just not running `tuist test` for it - which we should 👍

**Comment by Jake-Prickett** [comment] 2021-03-10 13:53
I have some time next week that I can dive into this a bit more 👍 Thanks @fortmarek!

**Comment by stherold** [comment] 2022-01-20 10:55
Short side question. How do you integrate cocoapods dependencies? I'm facing this issue right now :D

**Comment by fortmarek** [comment] 2022-01-21 18:10
Hey @stherold 👋 

The best way would be to wrap `tuist generate` command in a local script, so you can run `./generate`. The contents of the script would be equal to something like `tuist generate && pod install`. Bear in mind it will not unlock you to use `tuist test` unfortunately. We are thinking of providing post-generation hooks to make this easier.

**Comment by stherold** [comment] 2022-01-24 10:04
> The best way would be to wrap tuist generate command in a local script

@fortmarek thanks for the hint! This is exactly what I do right now nd it works quite well 👍

**Comment by Killectro** [comment] 2022-07-12 22:36
@fortmarek resurrecting this thread again to check in - does the plugin architecture released in 3.0 allow for the post-generation hooks you described? From what I can tell it doesn't but I'm still learning as I'm working on this!

Is it still the case that overall it's not possible to use `tuist test` if you use Cocoapods for 3rd-party dependencies? Is there a way to get `tuist test` to run the tests without generating the project? We have a `make tuist` lane that basically does the `tuist fetch && tuist generate && pod install` and it would be nice to be able to tack on something like `tuist test --skip-generation` in CI to have it just use the projects that have already been generated.

If it's not possible then it probably provides even more impetus for us to migrate away from Cocoapods for our dependencies, but obviously we'd love to be able to leverage the test caching and other benefits without needing to migrate away from Cocoapods to do it 😄

**Comment by fortmarek** [comment] 2022-07-13 20:11
> does the plugin architecture released in 3.0 allow for the post-generation hooks you described?

Unfortunately, it does not. However, if you are interested in contributing this, I'd be more than happy to guide you how to implement this once we decide on the direction (an RFC in the Github discussions would be necessary). As mentioned, providing post-generation hooks would allow you to start using `tuist test` with Cocoapods.

> Is it still the case that overall it's not possible to use tuist test if you use Cocoapods for 3rd-party dependencies? Is there a way to get tuist test to run the tests without generating the project? 

Unfortunately, that's a no for both. The main benefit of using `tuist test` is that it strips tests it does not need to re-run, so using it without generating the project does not make sense. If you are not interested in this functionality, you might want to, for the time being, keep using `xcodebuild` directly.

**Comment by danyf90** [comment] 2022-07-17 10:20
I think we can close this as we don't plan to add CocoaPods support to Dependencies.swift, which would be required for this.

@Killectro feel free to open a discussion in case you want to try implementing post generation hooks

**Closed by danyf90** 2022-07-17 10:20 UTC
Labels: type:bug, domain:automation

**Comment by leszko11** [comment] 2023-02-09 16:30
Hi @fortmarek @danyf90 👋🏼
Maybe I can help with this one?
