### ISSUE TITLE
TuistBundle+ header, file not found with Firebase In-App Messaging

### ISSUE THREAD

**Issue by theomendes** [tuist/tuist#6189] opened 2024-04-14 15:53 UTC
### What problem or need do you have?

Hello everyone, how are you?

I'm trying to set up Tuist in an existing project, and we use various dependencies. However, I'm encountering an issue with Firebase In-App Messaging. I've configured the dependencies using Package.swift, based on the `app_with_spm_dependencies` template. However, when I open the generated project and try to build, I receive the following error:

'TuistBundle+FirebaseInAppMessaging_iOS.h' file not found.

Upon analyzing the structure of the tuist-derived, I noticed that the file indeed was generated, but without the `_`, meaning if I use:

```swift
#import "TuistBundle+FirebaseInAppMessagingiOS.h"
```

the project builds successfully. Am I making a configuration mistake, or is it a bug in Tuist for dependencies with`_`?

Here's how I'm declaring:
```swift
let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", .upToNextMajor(from: "10.0.0")),
    ]
)
```

```swift
dependencies: [
    .target(name: "NotificationExtension"),
    .external(name: "FirebaseAnalytics"),
    .external(name: "FirebaseAuth"),
    .external(name: "FirebaseCrashlytics"),
    .external(name: "FirebaseDatabase"),
    .external(name: "FirebaseDynamicLinks"),
    .external(name: "FirebaseInAppMessaging-Beta"),
    .external(name: "FirebaseInstallations"),
    .external(name: "FirebaseMessaging"),
    .external(name: "FirebasePerformance"),
    .external(name: "FirebaseRemoteConfig")
],
```

Thanks in advance.

### macOS version

14.4

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by fortmarek** [comment] 2024-04-15 07:33
Hey!

This is most likely a duplicate of: https://github.com/tuist/tuist/issues/6099

The issue is resolved but not yet released. We will release a new version later today. If you are still running into this in 4.10.0, feel free to reopen 🙏

**Closed by fortmarek** 2024-04-15 07:33 UTC
Labels: type:need/problem
