### ISSUE TITLE
Local swift package unit tests not added to scheme

### ISSUE THREAD

**Issue by rogowski-smart** [tuist/tuist#6669] opened 2024-08-27 12:15 UTC
### What problem or need do you have?

Hello,

In our project we have added local swift package.  
Setup looks as below. Package is passed to `packages` property inside Project.
`packages: [
        .local(path: "../lib/Monitoring")
]`

In this project I have target and there I am passing its dependency:
`.package(product: "Monitoring"),`.

I would like to include tests from that package so they are executed as part of all tests in our Workspace. 
Inside Scheme in test action I am passing:
`.testableTarget(target: .target("MonitoringTests"))`. `Monitoring` and `MonitoringTests` products are exposed from local package. Unfortunately unit tests from our package are not visible when editing scheme. 
When I manually add test target from package, they become visible and will run.

Please let me know if there is something which I am doing wrong or if this is a bug.

Best regards,
Marek Rogowski

### macOS version

14.6.1

### Tuist version

4.12.1

### Xcode version

15.4

**Comment by fortmarek** [comment] 2024-08-30 08:06
Hola!

Closing as a duplicate of: https://github.com/tuist/tuist/issues/5912

@woin2ee has a PR in flight to implement this: https://github.com/tuist/tuist/pull/6436 🙂

**Closed by fortmarek** 2024-08-30 08:06 UTC
Labels: type:need/problem
