### ISSUE TITLE
Automatically fetch if necessary when generating

### ISSUE THREAD

**Issue by lordcodes** [tuist/tuist#4410] opened 2022-04-27 22:16 UTC
## Context

Currently, you only know you need to run 'fetch' when the 'generate' fails. 
This means all developers need to know to do this and need to do this.
It also means on CI you need to either always fetch or cache in advance and then assume they are in the cache, or write something to determine whether to fetch or not.
In comparison, Cocoapods, Bundler and other similar tools will fetch the dependency when you use the regular install command if the required dependency and version isn't found.

## Proposal

When running 'tuist generate', if a required external dependency version isn't found, 'tuist fetch' is ran and then the generate continues.

You may want this to either be an opt-in flag or an opt-out flag.

A more complicated option could handle this on a dependency by dependency basis like Cocoapods and Bundler, however, a simpler starting point is to just run the fetch of all once a missing dependency is found.

It may be possible to write a plugin that adds an extra command that achieves this result, however, to me it feels like this should be the general behaviour of install so thought I would check this first.

**Comment by danyf90** [comment] 2022-04-28 06:51
If we add something like this, it should be smarter and run also in other cases.
For example, if you bump a dependency or a plugin, generation might work fine but without doing the fetch you would still use the old version

**Comment by lordcodes** [comment] 2022-04-28 06:57
Ah of course, the version isn't specified where it's used, it's specified in the Dependencies.swift for the fetch.

**Comment by danyf90** [comment] 2022-05-24 15:08
> I like this proposal but I suggest an alternative course.. we should introduce the ability to define `workflows`
> 
> Use Yaml files or Swift (whatever makes sense) but something like:
> 
> ```swift
> generate_project_binaries_frameworks_workflow:
>    - command: fetch
>          - params: update 
>    - command: cache warm
>          - params: --xcframeworks 
>    - command: generate
>          - params: --no-open --xcframeworks  
> ```
> 
> you can allow a workflow to depend on another workflow for reusing pre-defines workflows. This could be a plugin with some executable

@shahzadmajeed  Isn't this exactly what tuist plugins allow you to do?

**Comment by danyf90** [comment] 2022-05-25 19:35
Also, apart from the configurability it's pretty much what [my plugin](https://github.com/danyf90/tuist-plugin-prepare) does :D

**Comment by lordcodes** [comment] 2022-05-25 22:21
The reason for this issue was for there to be a way to detect when fetch needs to take place. The idea being that instead of fetching just incase you need to it would fetch if it finds it needs to. Much like you get with Bundler for Ruby Gems, Cocoapods and SPM.
I wanted to avoid basically fetching every time on CI so a cache could be used as I noticed switching to Dependencies.swift with fetch massively increased CI time over using SPM via the syntax in Project.swift.
You could cache on master builds and then assume they are there for others but then they fail if you update a dependency, so instead I was wondering if it could just fetch automatically when it notices something is missing like other package managers do.

**Comment by fortmarek** [comment] 2022-05-27 10:31
> I wanted to avoid basically fetching every time on CI so a cache could be used as I noticed switching to Dependencies.swift with fetch massively increased CI time over using SPM via the syntax in Project.swift

The difference in the CI time between SPM in `Project.swift` and `Dependencies.swift` is only due to how effectively you cache them. SPM via `Project.swift` resolves its dependency whenever you run `tuist generate` (this also made the local development slower). 

> if it could just fetch automatically when it notices something is missing like other package managers do.

If we assume users don't play with the `Tuist/Dependencies` folder (which they shouldn't), we could:
- have a file in `Tuist/Dependencies/.fingerprint`
- this file would have a sha hash corresponding to the contents of `Dependencies.swift`
- if the file doesn't exist and user runs `tuist generate`, it would automatically run `tuist fetch` (and creating the fingerprint file at the end of the process)
- if you change something in`Dependencies.swift` and run `tuist generate`, it will notice change in the fingerprint, execute `tuist fetch` and update the file

wdyt @lordcodes @danyf90? Would you like to give this a go @lordcodes?

**Comment by danyf90** [comment] 2022-05-27 10:35
I agree, and we are doing something very similar in our tool which wraps tuist :D

There are some corner cases to consider, for example if you have a local dependency, you can't know if it's changed looking at Dependencies.swift, so you could skip the SPM fetch part, but you would still need to redo the SPM -> Tuist mapping of local dependencies, in case something is changed there

**Comment by lordcodes** [comment] 2022-05-27 11:34
This is an interesting idea, for my workflow it would make it possible with a plugin. Check file and run fetch if necessary and then run generate.

However, does seem like it might be useful to everyone built into the generate command like you described.

Will see if I have any time in the next week or so.

**Comment by fortmarek** [comment] 2022-05-27 12:14
> However, does seem like it might be useful to everyone built into the generate command like you described.

Yeah, in this case I think it's worth adding to `generate` directly.

**Comment by lordcodes** [comment] 2022-05-27 14:16
As always there are many more cases and edge cases than I realised when raising the idea!

**Comment by danyf90** [comment] 2022-08-12 10:40
Closing as duplicate of https://github.com/tuist/tuist/issues/3109

**Closed by danyf90** 2022-08-12 10:40 UTC
Labels: type:enhancement
