### ISSUE TITLE
Code Coverage Not Generated

### ISSUE THREAD

**Issue by stherold** [tuist/tuist#5960] opened 2024-02-20 15:24 UTC
## What happened?

We have all of our app in a local framework target which is linked to the app target. This framework target also contains the tests. Up to Tuist 3.28.0 generating the code coverage worked great but after the update to version 4.3.0 we get the error below. 

We use test plans where the coverage is explicitly turned on for the only this framework target.

[Here](https://stackoverflow.com/q/54431197/971329), [here](https://forums.developer.apple.com/forums/thread/734611) and [here](https://stackoverflow.com/questions/66653603/xcode-ui-tests-xcodebuild-fails-to-generate-coverage-profdata-on-xcode12-fail) are similar errors which led me to the assumption that this has to do with the dependencies. During the migration to Tuist 4.3.0 we had  to split up out Dependencies.swift file into a `<root>/Package.swift` and a `<root>/Cartfile`. I have the strange feeling it has to do with this...

I would be really thankful for any help here.

## How do we reproduce it?

1. Create an app project
2. Inside  create a normal framework target and link it to the main app.
3. Create a test target which tests code from the framework target.

## Error log

```sh
Failed to merge raw profiles in directory 
~/Library/Developer/Xcode/DerivedData/App-ejtxjgvamondbsabaaqpelmwijpv/Build/ProfileData/892AC812-C387-44CE-A3CD-A0E06834ED4B 
to destination 
~/Library/Developer/Xcode/DerivedData/App-ejtxjgvamondbsabaaqpelmwijpv/Build/ProfileData/892AC812-C387-44CE-A3CD-A0E06834ED4B/Coverage.profdata: 
Aggregation tool '/Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-profdata' 
failed with exit code 1: warning: 
~/Library/Developer/Xcode/DerivedData/App-ejtxjgvamondbsabaaqpelmwijpv/Build/ProfileData/892AC812-C387-44CE-A3CD-A0E06834ED4B/B2A70021-462A-4D5C-B079-09BD44C63C24-83360.profraw: 
invalid instrumentation profile data (file header is corrupt)
error: no profile can be merged
```

## Specifications

- **macOS** 14.3.1 (23D60)
- **Tuist** 4.5.0
- **Xcode** 15.3.0

**Comment by pepicrft** [comment] 2024-02-21 08:34
@stherold do you mind checking what the value of "Gather test coverage" is in 3.28.0 vs 4.3.0 for the scheme that you were using for running your tests? For context, schemes have that option, which is disabled by default, so I was wondering if we changed that default by mistake, or there's something else. I believe Xcode doesn't generate coverage data if that option is not enabled.

<img width="423" alt="image" src="https://github.com/tuist/tuist/assets/663605/88337dd6-148c-47fc-9c9c-a3c78cc3796d">

**Comment by stherold** [comment] 2024-02-21 16:19
@pepicrft, we use the `TestAction` as follows:
```swift
let testAction = TestAction.testPlans(
    ["\(sharedAppPath)/Tests/Default.xctestplan",
     "\(sharedAppPath)/Tests/Default-All-Langs.xctestplan",
     "\(sharedAppPath)/Tests/Screenshots.xctestplan"]
)
```

So we have 3 test plans and in those test plans the code coverage is configured correctly plus also the first one is sele ted as default test plan as we want it (at least for me it looks correct):

![image](https://github.com/tuist/tuist/assets/64915710/eb2d760c-1f61-4e14-bae8-cbe930c8790f)

But then after init of the TestAction I added the following 2 print statements which gave me the respective results:

```swift
print("🚨 Test Action Code Coverage: \(testAction.options.coverage)")
// 🚨 Test Action Code Coverage: false

print("🚨 Test Action Code Coverage Targets: \(testAction.options.codeCoverageTargets)")
// 🚨 Test Action Code Coverage Targets: []
```

I don't know the details of your implementation but maybe reading the coverage options should not be written to the Xcode scheme when `TestPlans` are used. Instead just leave it up to the test plan. In 3.28.0 this worked perfectly. Since you already have the 2 functions `static func testPlans()` and `static func targets()` you can make the TestAction an enum like this:

```swift
enum TestAction {
  	case .targets(<all the paramns here>)
	case .testPlans(<all the paramns here>)
}
```

Then, wherever `coverage` and `codeCoverageTargets` properties are used, you can check the `TestAction` case. For `.targets` you just use the properties and for `.testPlans` you don't set anything to the scheme since this is inferred by Xcode based on the test plan.

**Comment by Blackjacx** [comment] 2024-02-21 17:32
@pepicrft, we use the `TestAction` as follows:
```swift
let testAction = TestAction.testPlans(
    ["\(sharedAppPath)/Tests/Default.xctestplan",
     "\(sharedAppPath)/Tests/Default-All-Langs.xctestplan",
     "\(sharedAppPath)/Tests/Screenshots.xctestplan"]
)
```

So we have 3 test plans and in those test plans the code coverage is configured correctly plus also the first one is sele ted as default test plan as we want it (at least for me it looks correct):

![image](https://github.com/tuist/tuist/assets/64915710/eb2d760c-1f61-4e14-bae8-cbe930c8790f)

But then after init of the TestAction I added the following 2 print statements which gave me the respective results:

```swift
print("🚨 Test Action Code Coverage: \(testAction.options.coverage)")
// 🚨 Test Action Code Coverage: false

print("🚨 Test Action Code Coverage Targets: \(testAction.options.codeCoverageTargets)")
// 🚨 Test Action Code Coverage Targets: []
```

Result is the same when I only pass one TestPlan…

I don't know the details of your implementation but maybe reading the coverage options should not be written to the Xcode scheme when `TestPlans` are used. Instead just leave it up to the test plan. In 3.28.0 this worked perfectly. Since you already have the 2 functions `static func testPlans()` and `static func targets()` you can make the TestAction an enum like this:

```swift
enum TestAction {
  	case .targets(<all the paramns here>)
	case .testPlans(<all the paramns here>)
}
```

Then, wherever `coverage` and `codeCoverageTargets` properties are used, you can check the `TestAction` case. For `.targets` you just use the properties and for `.testPlans` you don't set anything to the scheme since this is inferred by Xcode based on the test plan. 

**EDIT**

I digged a bit in your code and I have the feeling that in the following location, you should not set `codeCoverageTargets` and `codeCoverageEnabled` when test plans are specified. I mean  basically anything in the huge function `schemeTestAction()` is setup by the test plan when one is specified but I think you override it.

https://github.com/tuist/tuist/blob/d8b4c0fa0627246cf234d8fafd9f5e9ead1d7653/Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift#L396-L418

**Comment by stherold** [comment] 2024-02-21 17:39
I trued to specify a workspace definition like this:

```swift
let workspace = Workspace(
    name: "Beiwagen",
    projects: [],
    fileHeaderTemplate: .none,
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .targets([.target(TargetType.common.name)]),
            testLanguage: SchemeLanguage(identifier: "en"),
            testRegion: "BZ"
        ),
        renderMarkdownReadme: true
    )
)

```

but then I get the following error:

```bash
We couldn't find a build configuration of variant 'debug' for caching. Make sure one exists in the project.

```

**Comment by Blackjacx** [comment] 2024-02-21 17:39
I trued to specify a workspace definition like this:

```swift
let workspace = Workspace(
    name: "Beiwagen",
    projects: [],
    fileHeaderTemplate: .none,
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .targets([.target(TargetType.common.name)]),
            testLanguage: SchemeLanguage(identifier: "en"),
            testRegion: "BZ"
        ),
        renderMarkdownReadme: true
    )
)

```

but then I get the following error:

```bash
We couldn't find a build configuration of variant 'debug' for caching. Make sure one exists in the project.

```

**Comment by pepicrft** [comment] 2024-02-21 18:09
> I digged a bit in your code and I have the feeling that in the following location, you should not set codeCoverageTargets and codeCoverageEnabled when test plans are specified. I mean basically anything in the huge function schemeTestAction() is setup by the test plan when one is specified but I think you override it.

That seems to be the issue. If you want to go ahead with a fix, feel free to clone the `tuist/tuist` codebase and run it against your project. You'll have to use the `tuist` scheme and change the working directory of the run action to point to your project's directory. Otherwise, we can do it, but I doubt we'll be able to prioritize it.

> I tried to specify a workspace definition like this:


This seems to be a different issue. Do you mind filing one and including as much details as you can, and ideally a reproducible project?

**Comment by Blackjacx** [comment] 2024-02-22 19:54
Hmm I added the following just below `let testPlans: [XCScheme.TestPlanReference]? = ...`

```swift
        if let testPlans, !testPlans.isEmpty {
            return XCScheme.TestAction(
                buildConfiguration: testAction.configurationName,
                macroExpansion: nil,
                testPlans: testPlans
            )
        }
```

Sadly no success the error persists 🤔 Do you have any ideas? I thought just setting the test plans would do it but there seems something else that controls coverage…

**Comment by stherold** [comment] 2024-03-12 10:51
> Otherwise, we can do it, but I doubt we'll be able to prioritize it.

Isn't that an issue for many people since TestPlans are quite common today?

**Comment by pepicrft** [comment] 2024-03-19 11:49
> Isn't that an issue for many people since TestPlans are quite common today?

We haven't seen this one reported many times. Could you include a project where I can reproduce the issue?

**Comment by Blackjacx** [comment] 2024-03-25 19:49
Aaaalright, I think I found the issue. Nothing goes over a [simple example project](https://github.com/tuist/tuist/files/14748807/tuist-example.zip) 😅 In the attached project you can see that the test coverage is actually generated. Please run `./bootstrap.sh` to generate the project. 

But when you uncomment the line to link the framework `Source` in  `Targets/TuistExample/Manifest/Project.swift` and run `./bootstrap` as well as the unit tests again, you'll get no code coverage. 

This seems to be an Xcode (+ dependency) issue with outdated frameworks. The best comment I read about it was [here](https://developer.apple.com/forums/thread/734611?login=true&page=1#783702022). 

Feel free to close this issue and many thanks for your support 👍

**Comment by fortmarek** [comment] 2024-03-26 00:52
Thanks for posting the solution. We could probably detect that and warn developers of those cases, but seems primarily it's something to fix on Apple's side to make this more clear. Glad it works for you now!

**Closed by fortmarek** 2024-03-26 00:52 UTC
Labels: type:bug

**Comment by stherold** [comment] 2024-03-26 09:42
Happy to use Tuist 4 👍

**Comment by Blackjacx** [comment] 2024-03-26 09:42
Happy to use Tuist 4 👍
