### ISSUE TITLE
Xcode 15 Update issues

### ISSUE THREAD

**Issue by leeari95** [tuist/tuist#5428] opened 2023-09-19 08:58 UTC
### What problem or need do you have?

After updating to Xcode 15 and running tuist fetch and tuist generate, I started to notice warnings that were not present when I was using Xcode 14.

```
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99.

DEFINES_MODULE was set, but no umbrella header could be found to generate the module map.

Ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz'
```
These warnings appear in the targets of external libraries.

### Potential solution

For the first warning, setting the IPHONEOS_DEPLOYMENT_TARGET to 12.0 in the settings when fetching dependencies with SPM resolved the issue. However, bundle targets that include resources still produce the same warning.

I haven't found a solution for the DEFINES_MODULE warning yet.

### macOS version

13.5.2

### Tuist version

3.20.0

### Xcode version

15.0

**Comment by zzt4** [comment] 2023-09-28 20:15
This looks like the same issue as last year with Xcode 14: https://github.com/tuist/tuist/issues/4765 Xcode 15 needs to have the minimum version bumped to iOS 12.0.

**Comment by mikchmie** [comment] 2023-09-29 07:06
What about the `DEFINES_MODULE` issue? I don't suppose it will get resolved by this ^ fix. 
For me, this warning is when building some frameworks from Firebase SPM package and [iziz/libPhoneNumber-iOS](https://github.com/iziz/libPhoneNumber-iOS).

**Comment by angelolloqui** [comment] 2023-10-04 14:17
It got resolved with 3.28.0 for me...

**Comment by mikchmie** [comment] 2023-10-10 09:57
3.28.0 didn't resolve the `DEFINES_MODULE` issue for me

**Comment by ammerzon** [comment] 2023-10-13 12:37
Same for me. With 3.28.0, the error still occurs.

**Comment by fortmarek** [comment] 2024-02-14 17:11
Closing as a duplicate of: https://github.com/tuist/tuist/issues/5513

A large part of these warnings should have been mitigated in the latest tuist versions, but there might be still a couple remaining. We hope to fix that soon.

**Closed by fortmarek** 2024-02-14 17:11 UTC
Labels: type:need/problem
