### ISSUE TITLE
Couldn't open Package.resolved inside .xcworkspace because there is no such file

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [tuist/tuist#5982] opened 2024-02-23 13:21 UTC
### What problem or need do you have?

I am trying to cache dependencies using the `tuist cache` command. 
**Sometimes** an error occurs on CI 
```
Using cache binaries for the following targets: ...
Generating workspace Project.xcworkspace
Generating project ...
Resolving package dependencies using xcodebuild
We received an error that we couldn't handle:
    - Localized description: The file “Package.resolved” couldn’t be opened because there is no such file.
    - Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Package.resolved” couldn’t be opened because there is no such file." UserInfo={NSFilePath=~/Project.xcworkspace/xcshareddata/swiftpm/Package.resolved, NSUnderlyingError=0x60000679c540 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
``` 

The whole lane looks like this: 
```
tuist install
tuist cache
tuist generate -n
```
Could you please support me on this point, I may have misunderstood the docs 🙏🏿 

### Potential solution

A possible solution is to call `tuist generate -n` twice

```
tuist install
tuist generate -n
tuist cache
tuist generate -n
```

### macOS version

13.6.3 (22G436)

### Tuist version

4.2.5

### Xcode version

15.2

**Comment by fortmarek** [comment] 2024-02-24 18:52
Hey!

It would be great to get a reproducible example, although I can see how that woukd be tricky. How do you define your SPM dependencies? Via Package.swift or the packages property?

**Comment by Bogdan-Belogurov** [comment] 2024-02-27 11:19
@fortmarek
Thanks for the reply! 🙏🏿
I define dependencies using Package.swift file in the root dir

**Comment by fortmarek** [comment] 2024-03-02 11:10
>  I define dependencies using Package.swift file in the root dir

I believe that's not possible – make sure you don't use the vanilla Xcode integration via `packages` property of `Project`. All your package dependencies should be linked in the Tuist manifests via `.external`. The line `Resolving package dependencies using xcodebuild` shouldn't be there if you use Tuist's SPM integration. You can learn more about it here: https://docs.tuist.io/tutorials/tuist/external-dependencies

**Comment by Bogdan-Belogurov** [comment] 2024-03-05 09:55
@fortmarek Oh, sorry 🙏🏿 You're right. I checked and we have only one dependency via SPM

**Comment by pepicrft** [comment] 2024-03-05 11:02
> @fortmarek Oh, sorry 🙏🏿 You're right. I checked and we have only one dependency via SPM

Does everything work if you follow @fortmarek's suggestion?

**Comment by pepicrft** [comment] 2024-05-14 11:12
I'm closing this one since there hasn't been any update and @fortmarek provided an answer. Feel free to re-open if the problem still persists @Bogdan-Belogurov

**Closed by pepicrft** 2024-05-14 11:12 UTC
Labels: type:need/problem
