### ISSUE TITLE
tuist cache warm --xcframeworks doesn't generate all xcframeworks

### ISSUE THREAD

**Issue by Dragna** [tuist/tuist#5645] opened 2023-12-07 10:01 UTC
### What happened?

I used one of the fixture project to test this `app_with_spm_dependencies`  and I don’t see any xcframework for ComposableArchitecture for instance, but I do see many empty folders with UUIDs for name in the BuildCache  folder.

### How do we reproduce it?

what I did 

- I’m using the latest version of tuist `3.35.2`
- I took the sample project `app_with_spm_dependencies`,
- here is the `Tuist/Dependencies.swift` file

```Swift
// swift-tools-version:5.9
import ProjectDescription
import ProjectDescriptionHelpers

let dependencies = Dependencies(
    swiftPackageManager: .init(
        baseSettings: .targetSettings,
        projectOptions: [
            "LocalSwiftPackage": .options(disableSynthesizedResourceAccessors: false),
        ]
    ),
    platforms: [.iOS, .tvOS]
) 

public static var targetSettings: Self {
        .settings(
            configurations: BuildEnvironment.allCases.map(\.targetConfiguration)
        )
    }
```

- I added a config file to cache in local

```Swift
// swift-tools-version:5.9
import ProjectDescription

let config = Config(
    cache: .cache(
        path: .relativeToRoot("Cache")
    ),
    swiftVersion: .init("5.9")
)
```

- I removed some dependencies from Tuist/Package.swift

```Swift
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire", from: "5.8.0"),
        .package(url: "https://github.com/facebook/facebook-ios-sdk", from: "16.1.3"),
        .package(url: "https://github.com/pointfreeco/swift-composable-architecture", .upToNextMinor(from: "1.5.0")),
        .package(url: "https://github.com/iterable/swift-sdk", from: "6.4.15"),
        .package(url: "https://github.com/Trendyol/ios-components", revision: "c9260bfe203a16a278eca5542c98455eece98aa4"),
        .package(path: "../../../LocalSwiftPackage"),
        .package(url: "https://github.com/groue/GRDB.swift", from: "6.16.0"),
        .package(path: "../../../StringifyMacro"),
    ]
)
```

- I used the command `tuist fetch`
- then `tuist cache warm --xcframeworks`
- then `tuist generate -x`

when warming the cache I can see some of the dependencies as xcframeworks, but not all.
with the tuist generate here is what I see
![Capture d’écran 2023-12-07 à 10 38 13](https://github.com/tuist/tuist/assets/960838/40604345-4e37-47d5-9661-99f64dd051bc)

and here is a screen of the cache folder (every product folder is open so we can see that we have data in some, but not others) : 
![Capture d’écran 2023-12-07 à 10 57 43](https://github.com/tuist/tuist/assets/960838/a2eb98c4-a1b9-4df8-bef1-0375e87a89e1)

if needed, [here](https://tuistapp.slack.com/archives/C018QG7U7SN/p1701941240060629) is a link to the thread discussion on slack

### Error log

no error log everything seems to be working fine 🙂 

### macOS version

14.1.2

### Tuist version

3.35.2

### Xcode version

15.0.1

**Comment by Dragna** [comment] 2023-12-07 12:14
I tested with the `3.34.0` version and I observe the same thing

**Comment by pepicrft** [comment] 2023-12-24 16:52
@Dragna, we are fixing a few regressions that arose after we added support for multi-platforms. You might be hitting some. To help with the debugging, I'd first suggest using `frameworks` instead of `xcframeworks` because we are dropping xcframeworks as a bundle for cache binaries because it's not the most sensible bundle format for caching. Do you mind trying with 3.36.5 and `tuist cache warm` and telling me how it behaves?

**Comment by fortmarek** [comment] 2024-07-16 16:52
Closing. Feel free to reopen if you are still running into this.

**Closed by fortmarek** 2024-07-16 16:52 UTC
Labels: type:bug
