### ISSUE TITLE
📦 [Dependencies.swift][SPM] Fix `GRDB.swift` dependency

### ISSUE THREAD

**Issue by IzaakSultan** [tuist/tuist#3477] opened 2021-09-20 08:53 UTC
**Describe the bug**
Tuist fails to generate a project when GRDB is included via Dependencies.swift

**To Reproduce**

1. Download the [attached project](https://github.com/tuist/tuist/files/7194462/Sample.zip)
2. Run `tuist dependencies fetch` and `tuist generate --open`
3. Generate fails with errors:
```
Couldn't find target 'CSQLite' at 'Sample/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GRDB.swift'
```

**Package**
This Package.swift can be used to replicate the same scenario with SPM (which is working fine):
```swift
// swift-tools-version:5.4.0

import PackageDescription

let package = Package(
    name: "Sample",
    platforms: [.iOS(.v10)],
    products: [
        .library(
            name: "Sample",
            targets: ["Sample"]
        ),
    ],
    dependencies: [
        .package(
            name: "GRDB",
            url: "https://github.com/groue/GRDB.swift",
            from: "5.11.0"
        ),
    ],
    targets: [
        .target(
            name: "Sample",
            dependencies: [
                .byName(name: "GRDB"),
            ],
            path: "Sources"
        ),
    ]
)

**Comment by danyf90** [comment] 2021-09-20 09:02
Assigning it to you while you have a look at it. Let me know if you need help 🙌

**Comment by bealex** [comment] 2021-11-07 12:10
Hi, any news here?

**Comment by danyf90** [comment] 2021-11-07 20:18
Hi 👋 
I think it's because the `systemLibrary(name: "CSQLite", providers: [.apt(["libsqlite3-dev"])]),` is currently not handled by tuist.
If you want to give it a try, I think it should probably work if we handle it as we do for a `linkedLibrary`.

You might try to change the GRDB Package.swift and link it as local package to check if it would work, and if it does you can go ahead with the change 🚀

**Comment by bealex** [comment] 2021-11-07 20:32
Thanks for the quick response. I'm totally new here, just wanted to port my project to Toist, and stumbled upon this thing and inability to specify different Info.plist files for different configurations.

Still looks quite interesting though. Hope I will find some way to spend more time and dig more in couple of days.

**Comment by AlexBabaevRMR** [comment] 2021-11-10 08:51
@danyf90 Can you help me please a little? Tried to clone/run Tuist from the sources (to find out how dependencies are working and eventually update the code), but got lost in all the targets and options. Do I need to generate xcodeworkspace with tuist itself? Do I run/edit SPM only? What target do I have to build and what arguments to use for the debug? Currently I kinda managed to run tuist CLI from SPM, but it does not build some frameworks and does not fully work.

Is there any document maybe on how to bootstrap this? Thanks! Sorry for dumbness :(

**Comment by bealex** [comment] 2021-11-10 08:53
@danyf90 Can you help me please a little? Tried to clone/run Tuist from the sources (to find out how dependencies are working and eventually update the code), but got lost in all the targets and options. Do I need to generate xcodeworkspace with tuist itself? Do I run/edit SPM only? What target do I have to build and what arguments to use for the debug? Currently I kinda managed to run tuist CLI from SPM, but it does not build some frameworks and does not fully work.

Is there any document maybe on how to bootstrap this? Thanks! Sorry for dumbness :(

**Comment by danyf90** [comment] 2021-11-10 08:57
Hey, right now on main there is a small problem with the project generation, hence you can just use the Package.swift directly opening it in Xcode.
From there, you first build the ProjectDescription scheme, and then you can run the `tuist` scheme, adding the command line parameters by editing the scheme.
If you are on Tuist Slack, feel free to ping me directly if you need more help 🚀

**Comment by bealex** [comment] 2021-11-10 11:18
OK, I got it working (at least it stopped complaining there), and stumbled upon next problem, with PhoneNumberKit, which, as far as I understood, roots here: https://github.com/tuist/tuist/issues/3112 and here https://github.com/tuist/tuist/issues/3563

(It is strange though, because Xcode successfully builds application with all dependencies as static (including PhoneNumberKit) and adding PhoneNumberKit bundle.)

Sounds like my project is kinda minefield for Tuist unfortunately :-(

**Comment by nhaarman** [comment] 2022-01-21 11:28
Hi! Is there a workaround for this?

**Comment by danyf90** [comment] 2022-01-21 12:44
> Hi! Is there a workaround for this?

Hi @nhaarman , it is still not working due to [this](https://github.com/tuist/tuist/issues/3477#issuecomment-962674125).
If you want to try to fix it, we can provide the info you need 🙏

**Comment by malcommac** [comment] 2022-03-03 14:58
Hi guys, I'm working to use Tuist in my project.
However I'm not sure what could be the workaround to this issue? Maybe should produce a precompiled binary?

**Comment by danyf90** [comment] 2022-03-03 16:12
Hey @malcommac 👋 
If you want to do the test I have suggested [here](https://github.com/tuist/tuist/issues/3477#issuecomment-962674125) and it works, it should be pretty simple to fix the PackageInfoMapper to handle this scenario.

Let us know if you need any help 🙏

**Comment by malcommac** [comment] 2022-03-04 07:35
Hi @danyf90 ,
Thank you. I've tried forking the repo and modifying the manifest from `systemLibrary` to `linkedLibrary` but it seems it does not exists:

```swift

let package = Package(
    name: "GRDB",
    platforms: [
        .iOS("10.0"),
        .macOS("10.10"),
        .tvOS("9.0"),
        .watchOS("2.0"),
    ],
    products: [
        .library(name: "GRDB", targets: ["GRDB"]),
    ],
    dependencies: [
    ],
    targets: [
        .linkedLibrary(
            name: "CSQLite",
            providers: [.apt(["libsqlite3-dev"])]),
        .target(
            name: "GRDB",
            dependencies: ["CSQLite"],
            path: "GRDB"),
        .testTarget(
            name: "GRDBTests",
            dependencies: ["GRDB"],
            path: "Tests",
            exclude: [
                "CocoaPods",
                "CustomSQLite",
                "Crash",
                "Performance",
                "SPM",
            ])
    ],
    swiftLanguageVersions: [.v5]
)
```

Am I missing something?

<img width="786" alt="Screenshot 2022-03-04 at 08 34 39" src="https://user-images.githubusercontent.com/235645/156719698-dcc4bb46-ba08-4e5d-a132-441114ef0006.png">

**Comment by danyf90** [comment] 2022-03-04 08:24
Sorry, let me try to clarify. I think you need to:
- remove the CSQLite `systemLibrary`
- remove the CSQLite target dependency
- add the linker setting as you have done (not sure about what should be the correct name of the library)

This could work if the CSQLite dependency is already available on macOS (I am assuming it because the provider is `apt` so I guess it's for linux). If it's not the case, we should check in the SPM code how such dependencies are handled and map that logic to tuist logic.

Regarding the error: `CSQLite is not a valid configured external dependency`, are you defining a dependency from CSQLite directly in your Dependencies.swift? Shouldn't you just depend on GRDB?

**Comment by malcommac** [comment] 2022-03-04 08:52
Thank you.
Yes the `CSQLite is not a valid configured external dependency` error is my mistake, during some attempts I've left the dependency inside `Dependencies.swift`.

The error is:

```bash
Couldn't find target 'CSQLite' at '.../Tuist/Dependencies/SwiftPackageManager/.build/checkouts/GRDB.swift'
```

The linker settings seems not work but I've found CSQLite is mapped into the sources: take a look [here](https://github.com/groue/GRDB.swift/tree/master/Sources/CSQLite).

**Comment by danyf90** [comment] 2022-03-04 10:03
I see 🤔 
Then it looks like the shortcut I suggested can't work and we need some additional logic inside Tuist 😞

If you want to try to implement it, I can provide the help you need 🙏 

Otherwise, until the issue is fixed you can define the dependency as a "legacy SPM dependency", by specifying it in the `packages` parameter of the `Project`, and as a `package` target dependency

**Comment by malcommac** [comment] 2022-03-04 13:19
Ok I tried with this way but I still get this:

```swift
[GRDB] Compiling FTS3Pattern.swift
❌ /Users/daniele/Library/Developer/Xcode/DerivedData/..../SourcePackages/checkouts/GRDB.swift/GRDB/Export.swift:3:19: no such module 'CSQLite'
@_exported import CSQLite
```

It does not happens linking a new project without Tuist but just using the XCode's SPM's Add Packages function.  
I also found an issue [on GRDB Issue Tracker](https://github.com/groue/GRDB.swift/issues/642) but, as I said, I didn't get a way to reproduce it in a standard environment.

How could I help?

**Comment by malcommac** [comment] 2022-03-10 08:36
Tell me if there's anything I can do to help 👍

**Comment by danyf90** [comment] 2022-03-10 11:24
Hey @malcommac 👋 
We would need to understand the actual SPM logic for `systemLibrary`, and implement it in tuist (most of the code should be in `PackageInfoMapper.swift`).

If you want to give it a try and need some help, feel free to write me on slack 🚀 🙌

**Comment by freak4pc** [comment] 2022-05-09 19:09
Is there an update on this? Huge blocker on our side. 
Trying to work with an xcframework seems to be much more flaky (relatively speaking).

**Closed** 2022-07-29 11:50 UTC
Labels: type:bug, domain:dependencies-swift
