### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by andreacipriani** [tuist/tuist#666] opened 2019-11-14 12:55 UTC
**Describe the bug**
Tuist reports an error with circular dependencies, but it doesn't seem to be the case.

**To Reproduce**

Follow the steps and the example proj in [this repo](https://github.com/andreacipriani/tuist-circular-dependency-example/blob/master/README.md)

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.14.6

**Comment by pepibumur** [comment] 2019-11-14 13:11
Thanks for reporting this @andreacipriani. I'll investigate it further but looking at your example it seems a bug because there's no circular dependency.
@kwridan since you are more familiar than me with that part of the codebase, can you think of anything that might be causing it?

**Comment by andreacipriani** [comment] 2019-11-14 13:18
Thanks @pepibumur, let me know if I can help, I prefer to open PRs rather than issues :)

**Comment by pepibumur** [comment] 2019-11-14 13:20
@andreacipriani you can pull the project and do `swift package generate-xcodeproj`. That'll generate an Xcode project that you can open. Then select the scheme `tuist` to run the command line tool from Xcode. Edit the scheme to indicate that you'd like to pass the `generate` argument and change the working directory to the directory where the project is. Then hit run and it should run the generation.

I'd try adding some breakpoints in [this class](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Graph/GraphCircularDetector.swift) or the code that consumes the API of that class. Then you should be able to find the root cause of this.

**Comment by kwridan** [comment] 2019-11-14 13:26
Hi @andreacipriani, thanks for flagging this.

I believe we have a fix for this going out in the next release #546. 

You can try using tuist master by running:

```sh
tuist local master
tuist generate
```

to see if the issue is still there using the latest master.

**Comment by pepibumur** [comment] 2019-11-14 13:35
Could you confirm if that fixes your issue @andreacipriani ?

**Comment by andreacipriani** [comment] 2019-11-14 14:11
Confirmed! It's fixed on `master` on my example proj 🙌🙌
Thanks everyone!

**Closed** 2019-11-15 13:56 UTC
Labels: type:bug
